# Generated by Django 5.1.8 on 2026-05-15 14:00
#
# Score uniqueness — add queue_item to every (source, label, annotator) partial
# unique index so the same annotator can score the same label on the same
# source independently per queue (one Score row per annotation-queue context).
# No data backfill: the new constraint is strictly more permissive than the
# old one, so every existing row stays valid.

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_last_timezone'),
        ('model_hub', '0099_annotationnotificationstate'),
        ('simulate', '0073_merge_20260416_1406'),
        ('tracer', '0077_merge_20260514_1559'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='score',
            name='unique_score_trace_label_annotator',
        ),
        migrations.RemoveConstraint(
            model_name='score',
            name='unique_score_span_label_annotator',
        ),
        migrations.RemoveConstraint(
            model_name='score',
            name='unique_score_session_label_annotator',
        ),
        migrations.RemoveConstraint(
            model_name='score',
            name='unique_score_call_label_annotator',
        ),
        migrations.RemoveConstraint(
            model_name='score',
            name='unique_score_run_label_annotator',
        ),
        migrations.RemoveConstraint(
            model_name='score',
            name='unique_score_row_label_annotator',
        ),
        migrations.RemoveConstraint(
            model_name='score',
            name='unique_score_trace_label_null_annotator',
        ),
        migrations.RemoveConstraint(
            model_name='score',
            name='unique_score_span_label_null_annotator',
        ),
        migrations.RemoveConstraint(
            model_name='score',
            name='unique_score_session_label_null_annotator',
        ),
        migrations.RemoveConstraint(
            model_name='score',
            name='unique_score_call_label_null_annotator',
        ),
        migrations.RemoveConstraint(
            model_name='score',
            name='unique_score_run_label_null_annotator',
        ),
        migrations.RemoveConstraint(
            model_name='score',
            name='unique_score_row_label_null_annotator',
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('trace__isnull', False)), fields=('trace', 'label', 'annotator', 'queue_item'), name='unique_score_trace_label_annotator'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('observation_span__isnull', False)), fields=('observation_span', 'label', 'annotator', 'queue_item'), name='unique_score_span_label_annotator'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('trace_session__isnull', False)), fields=('trace_session', 'label', 'annotator', 'queue_item'), name='unique_score_session_label_annotator'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(condition=models.Q(('call_execution__isnull', False), ('deleted', False)), fields=('call_execution', 'label', 'annotator', 'queue_item'), name='unique_score_call_label_annotator'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('prototype_run__isnull', False)), fields=('prototype_run', 'label', 'annotator', 'queue_item'), name='unique_score_run_label_annotator'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(condition=models.Q(('dataset_row__isnull', False), ('deleted', False)), fields=('dataset_row', 'label', 'annotator', 'queue_item'), name='unique_score_row_label_annotator'),
        ),
        # Null-annotator constraints stay at the pre-revamp grain. They
        # apply only to programmatic/auto scores (annotator IS NULL) and
        # adding ``queue_item`` to the field list would silently weaken
        # the index because Postgres treats NULL ≠ NULL — two auto-scores
        # with ``queue_item=NULL`` would both insert. Programmatic scores
        # remain one-per-(source, label).
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(condition=models.Q(('annotator__isnull', True), ('deleted', False), ('trace__isnull', False)), fields=('trace', 'label'), name='unique_score_trace_label_null_annotator'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(condition=models.Q(('annotator__isnull', True), ('deleted', False), ('observation_span__isnull', False)), fields=('observation_span', 'label'), name='unique_score_span_label_null_annotator'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(condition=models.Q(('annotator__isnull', True), ('deleted', False), ('trace_session__isnull', False)), fields=('trace_session', 'label'), name='unique_score_session_label_null_annotator'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(condition=models.Q(('annotator__isnull', True), ('call_execution__isnull', False), ('deleted', False)), fields=('call_execution', 'label'), name='unique_score_call_label_null_annotator'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(condition=models.Q(('annotator__isnull', True), ('deleted', False), ('prototype_run__isnull', False)), fields=('prototype_run', 'label'), name='unique_score_run_label_null_annotator'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(condition=models.Q(('annotator__isnull', True), ('dataset_row__isnull', False), ('deleted', False)), fields=('dataset_row', 'label'), name='unique_score_row_label_null_annotator'),
        ),
    ]
