# Generated by Django 5.1.8 on 2026-05-30 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0104_merge_20260526_0921'),
        ('tracer', '0079_merge_ch25_with_filter_contracts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='observation_span',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='tracer.observationspan'),
        ),
        migrations.AlterField(
            model_name='score',
            name='trace',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='tracer.trace'),
        ),
        migrations.AlterField(
            model_name='score',
            name='trace_session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='tracer.tracesession'),
        ),
    ]
