# Generated by Django 5.1.8 on 2026-05-30 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0105_decouple_score_telemetry_fk_constraints'),
        ('tracer', '0080_decouple_telemetry_fk_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueitem',
            name='observation_span',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_items', to='tracer.observationspan'),
        ),
        migrations.AlterField(
            model_name='queueitem',
            name='trace',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_items', to='tracer.trace'),
        ),
        migrations.AlterField(
            model_name='queueitem',
            name='trace_session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_items', to='tracer.tracesession'),
        ),
    ]
