# Generated by Django 5.1.8 on 2026-06-08 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0101_backfill_composite_v1_config_snapshots'),
        ('model_hub', '0106_decouple_telemetry_fk_constraints'),
    ]

    operations = [
    ]
