# Generated by Django 5.1.8 on 2026-07-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0112_eval_ground_truth_tenant_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationqueuelabel',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
