# Generated by Django 5.1.8 on 2026-07-15 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0115_eval_usage_version_backfill'),
        ('tracer', '0092_relax_external_eval_config_model_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueitem',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tracer.project'),
        ),
    ]
