# Generated by Django 5.1.8 on 2026-07-17 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_create_missing_org_memberships'),
        ('model_hub', '0117_backfill_queueitem_project'),
        ('simulate', '0077_relax_simulate_eval_config_model_choices'),
        ('tracer', '0093_register_eval_task_search_attributes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='tracer_project_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
