# Generated by Django 5.1.8 on 2026-07-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0120_backfill_score_tracer_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueitem',
            name='source_preview',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
