# Generated by Django 5.1.8 on 2025-10-30 10:00

import structlog

logger = structlog.get_logger(__name__)
from django.db import migrations
from tracer.utils.otel import ConversationAttributes, MessageAttributes


BATCH_SIZE = 1000
MAX_RETRIES = 3

# CH25-TODO: KEEP-PG. Django data migration — runs against the PG
# source-of-truth via apps.get_model() (the historical-model API). Data
# migrations cannot use CHSpanReader by design: they execute inside the
# migration framework's PG transaction and need to mutate the PG table
# directly. Updated rows propagate to CH via PeerDB CDC after the
# migration commits.
def add_transcripts_to_eval_attributes(apps, schema_editor):
    ObservationSpan = apps.get_model("tracer", "ObservationSpan")

    ## Gets all spans from voice observability projects
    spans_qs = (ObservationSpan.objects.filter(
                    parent_span_id__isnull=True,
                    project__source = 'simulator',
                )
                .select_related('project')
                .only(
                    'id',
                    'eval_attributes',
                    'project__source',
                    'project__id',
                ))
    
    total_spans = spans_qs.count()
    
    processed_count = 0
    updated_count = 0
    error_count = 0
    skipped_count = 0
    failed_spans = []

    ## Iterates over all spans and adds the provider transcripts to the eval attributes

    try:
        for batch_start in range(0, total_spans, BATCH_SIZE):
            batch_end = min(batch_start + BATCH_SIZE, total_spans)
            batch_spans = list(
                spans_qs[batch_start:batch_end].iterator(chunk_size=100)
            )
            spans_to_update = []

            for span in batch_spans:
                # Filter out spans that need to be updated

                try:
                    eval_attrs = span.eval_attributes or {}
                    provider_transcript = None
                    if not eval_attrs.get('provider_transcript'):
                        provider_transcript = []
                        i = 0
                        while True:
                            role = f"{ConversationAttributes.CONVERSATION_TRANSCRIPT}.{i}.{MessageAttributes.MESSAGE_ROLE}"
                            content = f"{ConversationAttributes.CONVERSATION_TRANSCRIPT}.{i}.{MessageAttributes.MESSAGE_CONTENT}"
                            if not eval_attrs.get(role) or not eval_attrs.get(content):
                                break
                            else:
                                provider_transcript.append({
                                    "role": eval_attrs.get(role),
                                    "content": eval_attrs.get(content),
                                })

                                i += 1
                    
                    if provider_transcript:
                        eval_attrs['provider_transcript'] = provider_transcript
                        span.eval_attributes = eval_attrs
                        spans_to_update.append(span)
                        updated_count += 1
                    
                    processed_count += 1
                except Exception as e:
                    error_count += 1
                    processed_count += 1
                    failed_spans.append({
                        "span_id": str(span.id),
                        "error": str(e),
                        "attempt":1
                    })
                    logger.warning(
                        f"Error processing span {span.id}: {str(e)}",
                        extra={
                            "span_id": str(span.id),
                            "batch": f"{batch_start}-{batch_end}"
                        }
                    )
                    continue

                # Try execept block for bulk update
            if spans_to_update:
                try:
                    ObservationSpan.objects.bulk_update(
                        spans_to_update,
                        ['eval_attributes'],
                        batch_size=BATCH_SIZE
                    )
                    logger.info(
                        f"Batch {batch_start}-{batch_end}: Updated {len(spans_to_update)} spans"
                    )
                except Exception as e:
                    logger.error(
                        f"Batch update failed for batch {batch_start}-{batch_end}: {str(e)}",
                        extra={"batch": f"{batch_start}-{batch_end}"}
                    )
                    # Fallback: try updating individually
                    for span in spans_to_update:
                        try:
                            span.save(update_fields=["eval_attributes"])
                        except Exception as individual_error:
                            failed_spans.append({
                                "span_id": str(span.id),
                                "error": str(individual_error),
                                "attempt": 2
                            })
                            logger.error(
                                f"Individual update failed for span {span.id}: {str(individual_error)}"
                            )
            logger.info(
                f"Progress: {processed_count}/{total_spans} spans processed "
                f"({updated_count} updated, {skipped_count} skipped, {error_count} errors)"
            )
        
        logger.info(
            "Migration completed",
            extra={
                "total": total_spans,
                "processed": processed_count,
                "updated": updated_count,
                "skipped": skipped_count,
                "errors": error_count
            }
        )

        if failed_spans:
            logger.warning(
                f"Migration completed with {len(failed_spans)} failed spans",
                extra={"failed_spans": failed_spans[:10]}  # Log first 10
            )
        
        if error_count > total_spans * 0.1:  # More than 10% failed
            logger.error(
                f"Migration completed with high error rate ({error_count}/{total_spans}). "
                "Please review failed spans and rerun migration."
            )

    except Exception as e:
         logger.critical(
            f"Migration failed with critical error: {str(e)}",
            exc_info=True
        )
class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0031_observationspan_tracer_obse_metadat_19717b_gin'),
    ]

    operations = [
        migrations.RunPython(add_transcripts_to_eval_attributes)
    ]
