# Generated by Django 5.1.8 on 2026-06-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0078_canonicalize_persisted_filter_contracts'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceerrorgroup',
            name='rca_at',
            field=models.DateTimeField(blank=True, help_text='When the last cluster-RCA run completed', null=True),
        ),
        migrations.AddField(
            model_name='traceerrorgroup',
            name='rca_confidence',
            field=models.CharField(blank=True, help_text='Synthesis confidence: H / M / L', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='traceerrorgroup',
            name='rca_evidence_trace_ids',
            field=models.JSONField(blank=True, default=list, help_text='Trace IDs the synthesis cited as evidence'),
        ),
        migrations.AddField(
            model_name='traceerrorgroup',
            name='rca_failures_at_run',
            field=models.IntegerField(blank=True, help_text='error_count snapshot at run time — drives the stale-result nudge', null=True),
        ),
        migrations.AddField(
            model_name='traceerrorgroup',
            name='rca_fix',
            field=models.TextField(blank=True, help_text="Agent's proposed fix (last run)", null=True),
        ),
        migrations.AddField(
            model_name='traceerrorgroup',
            name='rca_synthesis',
            field=models.TextField(blank=True, help_text="Agent's one-paragraph root-cause synthesis (last run)", null=True),
        ),
    ]
