# Generated by Django 5.1.8 on 2026-06-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0079_traceerrorgroup_rca_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceerrorgroup',
            name='rca_trace',
            field=models.JSONField(blank=True, default=None, help_text="The agent's investigation trail (reasoning + tool steps + synthesis) from the last run, so the Analyze tab can replay it on reload. Null until analyzed. The Falcon follow-up conversation is NOT persisted — only the agent's own run.", null=True),
        ),
    ]
