# Generated by Django 5.1.8 on 2026-05-30 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0079_merge_ch25_with_filter_contracts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorclustertraces',
            name='span',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_cluster_spans', to='tracer.observationspan'),
        ),
        migrations.AlterField(
            model_name='errorclustertraces',
            name='trace',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_cluster_traces', to='tracer.trace'),
        ),
        migrations.AlterField(
            model_name='evallogger',
            name='observation_span',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eval_logs', to='tracer.observationspan'),
        ),
        migrations.AlterField(
            model_name='evallogger',
            name='trace',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eval_logs', to='tracer.trace'),
        ),
        migrations.AlterField(
            model_name='evallogger',
            name='trace_session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eval_logs', to='tracer.tracesession'),
        ),
        migrations.AlterField(
            model_name='observationspan',
            name='end_user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracer.enduser'),
        ),
        migrations.AlterField(
            model_name='observationspan',
            name='trace',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='observation_spans', to='tracer.trace'),
        ),
        migrations.AlterField(
            model_name='spannotes',
            name='span',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tracer.observationspan'),
        ),
        migrations.AlterField(
            model_name='traceannotation',
            name='observation_span',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trace_annotation', to='tracer.observationspan'),
        ),
        migrations.AlterField(
            model_name='traceannotation',
            name='trace',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_labels', to='tracer.trace'),
        ),
        migrations.AlterField(
            model_name='traceerroranalysis',
            name='trace',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='error_analyses', to='tracer.trace'),
        ),
        migrations.AlterField(
            model_name='traceerroranalysistask',
            name='last_trace_analyzed',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_analyzed_by_task', to='tracer.trace'),
        ),
        migrations.AlterField(
            model_name='traceerrorgroup',
            name='success_trace',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Precomputed nearest success trace', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='success_for_groups', to='tracer.trace'),
        ),
        migrations.AlterField(
            model_name='tracescanresult',
            name='trace',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='tracer.trace'),
        ),
    ]
