# Generated by Django 5.1.8 on 2026-06-08 08:24

import django.contrib.postgres.operations
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    # ``atomic = False`` so AddIndexConcurrently runs in its own transaction;
    # CREATE INDEX CONCURRENTLY cannot run inside a transaction block.
    atomic = False

    dependencies = [
        ('tracer', '0080_traceerrorgroup_rca_trace'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='errorclustertraces',
            unique_together={('cluster', 'trace', 'span')},
        ),
        migrations.AddField(
            model_name='errorclustertraces',
            name='trace_session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_cluster_sessions', to='tracer.tracesession'),
        ),
        migrations.AddField(
            model_name='traceerrorgroup',
            name='eval_target_type',
            field=models.CharField(blank=True, choices=[('span', 'Span'), ('trace', 'Trace'), ('session', 'Session')], help_text='span/trace/session for eval clusters; null for scanner', max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='errorclustertraces',
            unique_together={('cluster', 'trace', 'span'), ('cluster', 'trace_session')},
        ),
        django.contrib.postgres.operations.AddIndexConcurrently(
            model_name='errorclustertraces',
            index=models.Index(fields=['trace_session'], name='tracer_erro_trace_s_e51a54_idx'),
        ),
    ]
