# Generated by Django 5.1.8 on 2026-05-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0080_decouple_telemetry_fk_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceSessionOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('trace_session_id', models.UUIDField(db_index=True)),
                ('project_id', models.UUIDField(db_index=True)),
                ('bookmarked', models.BooleanField(default=False)),
                ('display_name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'trace_session_overlay',
                'constraints': [models.UniqueConstraint(fields=('trace_session_id',), name='uniq_session_overlay')],
            },
        ),
    ]
