# Generated by Django 5.1.8 on 2026-06-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0081_rename_eval_task_filters_key'),
        ('tracer', '0082_decouple_trace_session_fk'),
    ]

    operations = [
    ]
