# Generated by Django 5.1.8 on 2026-06-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0081_alter_errorclustertraces_unique_together_and_more'),
        ('tracer', '0083_merge_20260610_1220'),
    ]

    operations = [
    ]
