# Generated by Django 5.1.8 on 2026-06-21 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0084_merge_20260611_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorclustertraces',
            name='trace_session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_cluster_sessions', to='tracer.tracesession'),
        ),
    ]
