# Generated by Django 5.1.8 on 2026-06-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0085_alter_errorclustertraces_trace_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracescanconfig',
            name='last_swept_at',
            field=models.DateTimeField(blank=True, help_text='Scan-sweep watermark (CH root-span created_at). The sweep scans (last_swept_at, now-grace] and advances this. NULL = never swept.', null=True),
        ),
    ]
