# Generated by Django 5.1.8 on 2026-06-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0084_alter_observabilityprovider_provider'),
        ('tracer', '0086_tracescanconfig_last_swept_at'),
    ]

    operations = [
    ]
