# Generated by Django 5.1.8 on 2026-06-27 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0086_tracescanconfig_last_swept_at'),
        ('tracer', '0087_eval_entry_baseline_backfill'),
    ]

    operations = [
    ]
