# Generated by Django 5.1.8 on 2026-07-02 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0084_rewrite_latency_ms_refs'),
        ('tracer', '0087_merge_20260627_1336'),
    ]

    operations = [
    ]
