# Generated by Django 5.1.8 on 2026-07-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0088_merge_20260702_1056'),
        ('tracer', '0089_evaltask_continuous_cursor'),
    ]

    operations = [
    ]
