# Generated by Django 5.1.8 on 2026-07-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracer", "0094_canonicalize_dashboard_widget_configs"),
        ("tracer", "0094_normalize_eval_task_filter_casing"),
    ]

    operations = []
