#!/usr/bin/env node
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import os from "node:os";
import path from "node:path";

const E2E_DIR = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const CATALOG = path.join(E2E_DIR, "FLOWS.md");
const REQUIRED = ["id", "area", "userGoal", "steps", "backendChecks"];

export function extractFlows(entries) {
  const flowTests = entries.filter((e) => e.tags.includes("@flow"));
  if (!flowTests.length)
    throw new Error("no @flow tests found — the catalog cannot be empty");
  const flows = flowTests.map((e) => {
    const ann = e.annotations.find((a) => a.type === "flow");
    if (!ann)
      throw new Error(
        `missing flow annotation on "${e.title}" (${e.location})`,
      );
    const meta = JSON.parse(ann.description);
    for (const key of REQUIRED) {
      if (!meta[key] || (Array.isArray(meta[key]) && !meta[key].length)) {
        throw new Error(`flow "${e.title}": annotation missing ${key}`);
      }
    }
    return {
      ...meta,
      title: e.title,
      location: e.location,
      tags: e.tags.filter((t) => t !== "@flow"),
    };
  });
  const seen = new Set();
  for (const f of flows) {
    if (seen.has(f.id)) throw new Error(`duplicate flow id ${f.id}`);
    seen.add(f.id);
  }
  return flows.sort((a, b) => a.id.localeCompare(b.id));
}

export function renderCatalog(flows) {
  const byArea = Map.groupBy(flows, (f) => f.area);
  const lines = [
    "# E2E Flow Catalog",
    "",
    "<!-- GENERATED by `yarn catalog` — do not edit. CI runs `yarn catalog:check`. -->",
    "",
  ];
  for (const [area, group] of [...byArea.entries()].sort()) {
    lines.push(`## ${area}`, "");
    for (const f of group) {
      lines.push(
        `### ${f.id} — ${f.title.replace(`${f.id}: `, "")}`,
        "",
        `**Goal:** ${f.userGoal}  `,
        `**Spec:** \`${f.location}\`  `,
        `**Tags:** ${f.tags.join(" ") || "—"}`,
        "",
        // The blank line before each list keeps the output prettier-clean, so
        // the pre-commit formatter cannot rewrite this file and break --check.
        "**User steps:**",
        "",
        ...f.steps.map((s, i) => `${i + 1}. ${s}`),
        "",
        "**Backend state verified:**",
        "",
        ...f.backendChecks.map((c) => `- ${c}`),
        "",
      );
    }
  }
  return lines.join("\n");
}

function main() {
  const listFile = path.join(os.tmpdir(), `flow-list-${process.pid}.json`);
  try {
    // The catalog documents which flows exist, independent of what a given run
    // executes — quarantining or live-LLM-gating a flow must not delete it from FLOWS.md.
    execFileSync(
      "npx",
      [
        "playwright",
        "test",
        "--list",
        "--reporter=./scripts/flow-list-reporter.mjs",
      ],
      {
        cwd: E2E_DIR,
        encoding: "utf8",
        stdio: ["ignore", "ignore", "pipe"],
        env: {
          ...process.env,
          FLOW_CATALOG_OUT: listFile,
          E2E_INCLUDE_QUARANTINED: "1",
          E2E_LIVE_LLM: "1",
        },
      },
    );
  } catch (err) {
    // The reporter always writes the list once it runs, so a missing file means
    // Playwright failed before collection — a real error, not an empty catalog.
    if (!existsSync(listFile)) {
      console.error(err.stderr || err.message);
      process.exit(1);
    }
  }
  const listed = readFileSync(listFile, "utf8");
  rmSync(listFile, { force: true });
  let rendered;
  try {
    rendered = renderCatalog(extractFlows(JSON.parse(listed)));
  } catch (err) {
    console.error(err.message);
    process.exit(1);
  }
  if (process.argv.includes("--check")) {
    const committed = readFileSync(CATALOG, "utf8");
    if (committed !== rendered) {
      console.error(
        "FLOWS.md is stale — run `yarn catalog` and commit the result.",
      );
      process.exit(1);
    }
    console.log("FLOWS.md is current.");
  } else {
    writeFileSync(CATALOG, rendered);
    console.log(`wrote ${CATALOG}`);
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
