
FROM python:3.11-slim-bookworm

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_DEFAULT_TIMEOUT=300 \
    UV_TIMEOUT=900 \
    NLTK_DATA=/usr/local/share/nltk_data \
    PROJECT_ROOT=/app/backend

RUN groupadd --gid 1000 appuser && \
    useradd --uid 1000 --gid appuser --shell /bin/bash --create-home appuser

RUN apt-get update && apt-get install -y --no-install-recommends \
        supervisor \
        nginx \
        git \
        curl \
        nodejs \
        build-essential \
        libxml2-dev \
        libxmlsec1-dev \
        libxmlsec1-openssl \
        pkg-config \
        xmlsec1 \
        ffmpeg \
        libavformat-dev \
        libavcodec-dev \
        libavdevice-dev \
        libavutil-dev \
        libavfilter-dev \
        libswscale-dev \
        libswresample-dev \
        libcom-err2 \
        libkrb5-3 \
        libgssapi-krb5-2 \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

WORKDIR $PROJECT_ROOT
RUN pip install uv && mkdir -p media logs static && chown -R appuser:appuser /app

COPY futureagi/requirements.txt ./
RUN uv pip install --system -r requirements.txt --compile-bytecode --no-cache --only-binary av

COPY futureagi/ .
RUN python bin/install_nltk_data.py
RUN chmod +x entrypoint.sh

EXPOSE 80 5555 50051

ENTRYPOINT ["bash", "./entrypoint.sh"]
