# Generated by Django 5.1.8 on 2025-07-09 07:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APICallType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(choices=[('dataset_logging', 'Dataset Logging'), ('dataset_evaluation', 'Dataset Evaluation'), ('prompt_bench', 'Prompt Bench'), ('dataset_protect', 'Dataset Protect'), ('dataset_protect_flash', 'Dataset Protect Flash'), ('user_add', 'User Add'), ('observe_add', 'Observe Add'), ('prototype_add', 'Prototype Add'), ('dataset_add', 'Dataset Add'), ('row_add', 'Row Add'), ('knowledge_base', 'Knowledge Base'), ('synthetic_data_generation', 'Synthetic Data Generation'), ('error_localizer', 'Error Localizer'), ('auto_annotation', 'Auto Annotation'), ('experiment_evaluation', 'Experiment Evaluation'), ('optimisation_evaluation', 'Optimisation Evaluation'), ('eval_explanation', 'Eval Explanation'), ('dataset_run_prompt', 'Dataset Run Prompt'), ('dataset_optimization', 'Dataset Optimization'), ('dataset_experiment', 'Dataset Experiment'), ('wallet_refund', 'Wallet Refund'), ('wallet_refill', 'Wallet Refill'), ('wallet_auto_recharge', 'Wallet Auto Recharge'), ('wallet_add_funds', 'Wallet Add Funds')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(choices=[('project', 'Project'), ('dataset', 'Dataset'), ('logs', 'Logs'), ('rows', 'Rows'), ('columns', 'Columns'), ('users', 'Users'), ('traces', 'Traces'), ('observe', 'Observe'), ('prototypes', 'Prototypes'), ('knowledge_base', 'Knowledge Base')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='APICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cost', models.DecimalField(decimal_places=8, max_digits=16)),
                ('deducted_cost', models.DecimalField(decimal_places=8, default=0, max_digits=16)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('not_started', 'Not Started'), ('rate_limited', 'Rate Limited'), ('processing', 'Processing'), ('insufficient_credits', 'Insufficient Credits'), ('resource_limit', 'Resource Limit')], default='not_started', max_length=50)),
                ('refund_parent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('input_token_count', models.PositiveIntegerField(default=0, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('api_call_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usage.apicalltype')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('billing_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_address1', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', unique=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('basic_yearly', 'Basic Yearly'), ('custom', 'Custom')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_price_ids_all', models.JSONField(blank=True, default=list, null=True)),
                ('wallet_refill_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount to refill the wallet every month.', max_digits=10, null=True)),
            ],
            options={
                'unique_together': {('name', 'description')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('next_renewal_date', models.DateField(blank=True, help_text='Next due date for renewal.', null=True)),
                ('subscription_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price of the subscription.', max_digits=10, null=True)),
                ('subscription_future_tier', models.CharField(blank=True, choices=[('free', 'Free'), ('basic', 'Basic'), ('basic_yearly', 'Basic Yearly'), ('custom', 'Custom')], max_length=50, null=True)),
                ('subscription_future_start_date', models.DateField(blank=True, help_text='Next due date for renewal.', null=True)),
                ('subscription_future_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price of the future subscription.', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('wallet_refill_amount', models.DecimalField(decimal_places=2, default=20, help_text='Amount to refill the wallet every month.', max_digits=10)),
                ('wallet_balance', models.DecimalField(decimal_places=8, default=0, max_digits=16)),
                ('stripe_customer_id_test', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('stripe_customer_id_live', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('auto_recharge_enabled', models.BooleanField(default=False)),
                ('auto_recharge_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount to refill the wallet every month.', max_digits=10, null=True)),
                ('auto_recharge_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Threshold to trigger auto recharge.', max_digits=10, null=True)),
                ('payment_method_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_dev_account', models.BooleanField(default=False)),
                ('last_refill_date', models.DateField(blank=True, null=True)),
                ('last_refill_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount of the last refill.', max_digits=10)),
                ('custom_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', unique=True)),
                ('subscription_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usage.subscriptiontier')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('price_per_call', models.DecimalField(decimal_places=8, max_digits=16)),
                ('api_call_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usage.apicalltype')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'unique_together': {('api_call_type', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='ResourceLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('has_access', models.BooleanField(default=False)),
                ('limit', models.PositiveIntegerField(help_text='Limit for the resource')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usage.resourcetype')),
                ('subscription_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usage.subscriptiontier')),
            ],
            options={
                'unique_together': {('resource_type', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('minute_limit', models.PositiveIntegerField(blank=True, help_text='Max calls per minute', null=True)),
                ('hour_limit', models.PositiveIntegerField(blank=True, help_text='Max calls per hour', null=True)),
                ('day_limit', models.PositiveIntegerField(blank=True, help_text='Max calls per day', null=True)),
                ('month_limit', models.PositiveIntegerField(blank=True, help_text='Max calls per month', null=True)),
                ('api_call_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usage.apicalltype')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('subscription_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usage.subscriptiontier')),
            ],
            options={
                'unique_together': {('api_call_type', 'subscription_tier', 'organization')},
            },
        ),
    ]
