# Generated by Django 5.1.8 on 2025-09-05 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20250905_1827'),
        ('usage', '0002_alter_apicalltype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicalllog',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.workspace'),
        ),
    ]
