# Generated by Django 5.1.8 on 2025-09-09 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0003_alter_apicalltype_name'),
        ('usage', '0003_apicalllog_workspace'),
    ]

    operations = [
    ]
