# Generated by Django 5.1.8 on 2025-09-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0004_merge_20250909_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicalltype',
            name='name',
            field=models.CharField(choices=[('prompt_bench', 'Prompt Bench'), ('dataset_protect', 'Dataset Protect'), ('dataset_protect_flash', 'Dataset Protect Flash'), ('turing_large_evaluator', 'Turing Large Evaluator'), ('turing_small_evaluator', 'Turing Small Evaluator'), ('turing_flash_evaluator', 'Turing Flash Evaluator'), ('protect_evaluator', 'Protect Evaluator'), ('protect_flash_evaluator', 'Protect Flash Evaluator'), ('user_add', 'User Add'), ('observe_add', 'Observe Add'), ('prototype_add', 'Prototype Add'), ('dataset_add', 'Dataset Add'), ('row_add', 'Row Add'), ('knowledge_base', 'Knowledge Base'), ('synthetic_data_generation', 'Synthetic Data Generation'), ('error_localizer', 'Error Localizer'), ('auto_annotation', 'Auto Annotation'), ('dataset_evaluation', 'Dataset Evaluation'), ('experiment_evaluation', 'Experiment Evaluation'), ('optimisation_evaluation', 'Optimisation Evaluation'), ('eval_explanation', 'Eval Explanation'), ('dataset_run_prompt', 'Dataset Run Prompt'), ('dataset_optimization', 'Dataset Optimization'), ('dataset_experiment', 'Dataset Experiment'), ('voice_call', 'Voice Call'), ('wallet_refund', 'Wallet Refund'), ('wallet_refill', 'Wallet Refill'), ('wallet_auto_recharge', 'Wallet Auto Recharge'), ('wallet_add_funds', 'Wallet Add Funds'), ('trace_error_analysis', 'Trace Error Analysis')], max_length=50, unique=True),
        ),
    ]
