# Generated by Django 5.1.8 on 2026-02-14 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0006_add_usage_summary_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='apicalllog',
            index=models.Index(fields=['organization', 'source_id', '-created_at'], name='idx_apicalllog_org_source'),
        ),
    ]
