# Generated by Django 5.1.8 on 2026-03-29 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_blockedkeyproxy'),
        ('usage', '0008_alter_apicalllog_options_alter_apicalltype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('credit_type', models.CharField(choices=[('startup', 'Startup Program'), ('referral', 'Referral'), ('goodwill', 'Goodwill'), ('prepaid', 'Prepaid')], help_text='Type of credit.', max_length=30)),
                ('original_amount', models.DecimalField(decimal_places=2, help_text='Total credit amount when issued.', max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, help_text='Remaining credit balance. Decremented when applied to invoices.', max_digits=10)),
                ('currency', models.CharField(default='usd', help_text='ISO 4217 currency code.', max_length=3)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this credit expires. NULL = never expires.', null=True)),
                ('description', models.CharField(help_text="Human-readable description (e.g., 'Startup program — $50K cloud credits').", max_length=200)),
                ('issued_by', models.CharField(blank=True, default='', help_text='Admin or system that issued this credit.', max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='organizationsubscription',
            options={},
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='billing_interval',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', help_text='Billing cycle for add-on subscriptions (monthly or annual).', max_length=10),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='billing_method',
            field=models.CharField(choices=[('card', 'Credit Card'), ('invoice_30', 'Invoice Net-30'), ('invoice_60', 'Invoice Net-60'), ('wire', 'Wire Transfer'), ('aws_marketplace', 'AWS Marketplace'), ('gcp_marketplace', 'GCP Marketplace')], default='card', help_text='How this organization pays (card, invoice, wire, marketplace).', max_length=20),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='billing_period_end',
            field=models.DateField(blank=True, help_text='End of current billing cycle.', null=True),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='billing_period_start',
            field=models.DateField(blank=True, help_text='Start of current billing cycle.', null=True),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('payg', 'Pay-as-you-go'), ('boost', 'Boost'), ('scale', 'Scale'), ('enterprise', 'Enterprise')], db_index=True, default='free', help_text='Current billing plan. Source of truth for entitlements.', max_length=20),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe subscription ID. One per org with multiple line items.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='tracing_billing_mode',
            field=models.CharField(choices=[('storage', 'Storage-based (GB)'), ('events', 'Event-based (traces + spans + scores)')], default='storage', help_text='How tracing data is billed: storage (GB) or events (traces+spans+scores).', max_length=10),
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['plan'], name='idx_orgsub_plan'),
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['status', 'plan'], name='idx_orgsub_status_plan'),
        ),
        migrations.AddField(
            model_name='creditbalance',
            name='organization',
            field=models.ForeignKey(help_text='Organization this credit belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='credit_balances', to='accounts.organization'),
        ),
        migrations.AddIndex(
            model_name='creditbalance',
            index=models.Index(fields=['organization', 'credit_type'], name='idx_credit_org_type'),
        ),
        migrations.AddIndex(
            model_name='creditbalance',
            index=models.Index(fields=['organization', '-expires_at'], name='idx_credit_org_exp'),
        ),
    ]
