# Generated by Django 5.1.8 on 2026-03-29 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_blockedkeyproxy'),
        ('usage', '0009_creditbalance_alter_organizationsubscription_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEventLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(help_text='Idempotency key from UsageEvent.event_id. Consumer deduplicates on this.', unique=True)),
                ('event_type', models.CharField(help_text="API call type key from billing.yaml (e.g., 'turing_large_evaluator').", max_length=50)),
                ('dimension', models.CharField(help_text="Resolved billing dimension (e.g., 'ai_credits', 'storage').", max_length=30)),
                ('amount_raw', models.BigIntegerField(help_text='Units consumed in native units (bytes, credits, requests).')),
                ('amount_display', models.DecimalField(decimal_places=4, help_text='Units consumed in display units (GB, credits).', max_digits=16)),
                ('period', models.CharField(help_text='Billing period in YYYY-MM format.', max_length=7)),
                ('timestamp', models.DateTimeField(help_text='When the usage occurred (from the event, not insert time).')),
                ('properties', models.JSONField(default=dict, help_text='Flat k/v context: source, source_id, model, workspace_id, etc.')),
                ('status', models.CharField(default='success', help_text='success, rate_limited, quota_exceeded.', max_length=20)),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=4, help_text='Estimated cost at time of event. NULL for free-tier events.', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this row was inserted by the consumer.')),
                ('organization', models.ForeignKey(help_text='Organization this event belongs to.', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('workspace', models.ForeignKey(blank=True, help_text='Optional workspace context.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'period', 'dimension'], name='idx_uel_org_period_dim'), models.Index(fields=['organization', 'event_type', '-timestamp'], name='idx_uel_org_type_ts'), models.Index(fields=['organization', '-timestamp'], name='idx_uel_org_ts'), models.Index(fields=['period', 'dimension'], name='idx_uel_period_dim')],
            },
        ),
        migrations.CreateModel(
            name='UsageSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dimension', models.CharField(help_text="Billing dimension key (e.g., 'storage', 'ai_credits').", max_length=30)),
                ('period', models.CharField(help_text='Billing period in YYYY-MM format.', max_length=7)),
                ('total_usage', models.DecimalField(decimal_places=4, help_text='Cumulative usage in display units (GB, credits).', max_digits=16)),
                ('total_usage_raw', models.BigIntegerField(default=0, help_text='Cumulative usage in native units (bytes, tokens) for precision.')),
                ('reported_to_stripe', models.DecimalField(decimal_places=4, default=0, help_text='Last value reported to Stripe. Used for delta reporting.', max_digits=16)),
                ('last_flushed_at', models.DateTimeField(help_text='When this row was last updated from Redis.')),
                ('organization', models.ForeignKey(help_text='Organization this summary belongs to.', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'period'], name='idx_usagesummary_org_period')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'dimension', 'period'), name='uq_usage_summary_org_dim_period')],
            },
        ),
    ]
