# Generated by Django 5.1.8 on 2026-03-29 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_blockedkeyproxy'),
        ('usage', '0010_usageeventlog_usagesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('feature', models.CharField(help_text="Feature key. Convention: 'monitors', 'has_knowledge_base', 'free_storage_gb', 'retention_traces_days', 'api_rate_rpm'", max_length=60)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('payg', 'Pay-as-you-go'), ('boost', 'Boost'), ('scale', 'Scale'), ('enterprise', 'Enterprise')], help_text='Which plan this value applies to.', max_length=20)),
                ('value_int', models.IntegerField(blank=True, help_text='Numeric value: limit count, GB, days, rpm. -1 = unlimited. NULL if boolean.', null=True)),
                ('value_bool', models.BooleanField(blank=True, help_text='Boolean value: feature on/off. NULL if numeric.', null=True)),
                ('organization', models.ForeignKey(blank=True, help_text='NULL = plan default. Non-NULL = per-org override.', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['plan', 'feature'], name='idx_ent_plan_feature'), models.Index(fields=['organization', 'feature'], name='idx_ent_org_feature')],
                'constraints': [models.UniqueConstraint(fields=('feature', 'plan', 'organization'), name='uq_entitlement_feature_plan_org')],
            },
        ),
    ]
