# Generated by Django 5.1.8 on 2026-03-29 09:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_blockedkeyproxy'),
        ('usage', '0011_planentitlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField(help_text='Start of billing period.')),
                ('period_end', models.DateField(help_text='End of billing period.')),
                ('plan', models.CharField(help_text='Plan at time of invoice generation.', max_length=20)),
                ('platform_fee', models.DecimalField(decimal_places=2, help_text='Add-on subscription fee ($0, $250, $750, $2000).', max_digits=10)),
                ('usage_total', models.DecimalField(decimal_places=2, help_text='Sum of all usage line items.', max_digits=10)),
                ('credits_applied', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all credit line items (positive number, subtracted from total).', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='platform_fee + usage_total - credits_applied.', max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, help_text='Tax amount (calculated by Stripe Tax).', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, help_text='subtotal + tax. Final amount to charge.', max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('status', models.CharField(default='draft', help_text='draft, finalized, paid, failed, void.', max_length=20)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_invoice_url', models.URLField(blank=True, null=True)),
                ('stripe_pdf_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(help_text='Organization this invoice belongs to.', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('line_type', models.CharField(help_text='platform_fee, usage, credit, discount, adhoc.', max_length=20)),
                ('dimension', models.CharField(blank=True, help_text='Billing dimension. NULL for non-usage lines.', max_length=30, null=True)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Usage amount in display units.', max_digits=16)),
                ('unit', models.CharField(help_text='GB, credits, requests, etc.', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=4, help_text='Effective price per display unit.', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Line total. Negative for credits.', max_digits=10)),
                ('tier_breakdown', models.JSONField(blank=True, help_text='[{"range": "0-500GB", "rate": "$2.00", "usage": 450, "cost": "$900"}]', null=True)),
                ('credit', models.ForeignKey(blank=True, help_text='Which credit was applied (for credit line items).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usage.creditbalance')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='usage.invoice')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dimension', models.CharField(help_text="Billing dimension key (e.g., 'storage', 'ai_credits').", max_length=30)),
                ('tier_start', models.DecimalField(decimal_places=4, help_text='Start of range in display units (50 for 50 GB, 2000 for 2000 credits).', max_digits=16)),
                ('tier_end', models.DecimalField(blank=True, decimal_places=4, help_text='End of range in display units. NULL = unlimited (last tier).', max_digits=16, null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=4, help_text='Price per display unit ($2.00 per GB, $0.01 per credit).', max_digits=10)),
                ('display_unit', models.CharField(help_text='Display unit label: GB, credits, requests, hits, tokens, minutes, events.', max_length=20)),
                ('organization', models.ForeignKey(blank=True, help_text='NULL = default for everyone. Non-NULL = custom deal for this org.', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='UsageBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='User-facing label.', max_length=100)),
                ('scope', models.CharField(help_text="Dimension key (e.g., 'ai_credits') or 'total_spend'.", max_length=30)),
                ('threshold_value', models.DecimalField(decimal_places=4, help_text='In display units (credits, GB) or cents for total_spend.', max_digits=16)),
                ('action', models.CharField(help_text='notify = email/slack only, warn = notify + banner, pause = block usage.', max_length=20)),
                ('notify_emails', models.JSONField(blank=True, default=list, help_text='Email addresses to notify. Empty = org admins.')),
                ('notify_slack_webhook', models.URLField(blank=True, help_text='Slack webhook URL for notifications.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_period', models.CharField(blank=True, help_text="YYYY-MM of last trigger (dedup: don't re-fire in same period).", max_length=7, null=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, help_text='When the budget was last triggered.', null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_budgets', to='accounts.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', '-period_start'], name='idx_invoice_org_period'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='idx_invoice_status'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('organization', 'period_start'), name='uq_invoice_org_period'),
        ),
        migrations.AddIndex(
            model_name='planpricing',
            index=models.Index(fields=['dimension'], name='idx_pricing_dim'),
        ),
        migrations.AddIndex(
            model_name='planpricing',
            index=models.Index(fields=['organization'], name='idx_pricing_org'),
        ),
        migrations.AddConstraint(
            model_name='planpricing',
            constraint=models.UniqueConstraint(fields=('dimension', 'tier_start', 'organization'), name='uq_pricing_dim_start_org'),
        ),
        migrations.AddIndex(
            model_name='usagebudget',
            index=models.Index(fields=['organization', 'scope', 'is_active'], name='idx_budget_org_scope'),
        ),
    ]
