# Generated by Django 5.1.8 on 2026-03-29 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_blockedkeyproxy'),
        ('usage', '0012_invoice_invoicelineitem_planpricing_usagebudget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EELicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('license_key_hash', models.CharField(help_text='SHA-256 hash of the JWT license key.', max_length=64, unique=True)),
                ('band', models.CharField(help_text='License band: team, business, enterprise, enterprise_plus.', max_length=20)),
                ('features', models.JSONField(help_text='Array of feature strings: ["knowledge_base", "review_workflow", ...]')),
                ('max_traces_monthly', models.BigIntegerField(help_text='Trace limit per month. -1 = unlimited.')),
                ('max_gateway_monthly', models.BigIntegerField(help_text='Gateway request limit per month. -1 = unlimited.')),
                ('max_users', models.IntegerField(help_text='Seat limit. -1 = unlimited.')),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('issued_to', models.CharField(max_length=200)),
                ('is_valid', models.BooleanField(default=True)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(help_text='One license per org (self-hosted typically has one org).', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', unique=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
