# Generated by Django 5.1.8 on 2026-03-29 11:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0013_eelicense'),
    ]

    operations = [
        migrations.CreateModel(
            name='EELicenseGrant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(help_text='Company name.', max_length=200)),
                ('customer_email', models.EmailField(help_text='Primary contact email.', max_length=254)),
                ('band', models.CharField(help_text='team, business, enterprise, enterprise_plus.', max_length=20)),
                ('billing_interval', models.CharField(default='monthly', help_text='monthly or annual.', max_length=10)),
                ('features', models.JSONField(help_text='Feature array encoded in JWT.')),
                ('max_traces_monthly', models.BigIntegerField(help_text='-1 = unlimited.')),
                ('max_gateway_monthly', models.BigIntegerField(help_text='-1 = unlimited.')),
                ('max_users', models.IntegerField(default=-1, help_text='-1 = unlimited.')),
                ('license_key_hash', models.CharField(help_text='SHA-256 of JWT.', max_length=64, unique=True)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(default='active', help_text='active, expired, revoked, suspended.', max_length=20)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, default='', max_length=200)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-expires_at'], name='idx_eegrant_status_exp'), models.Index(fields=['customer_email'], name='idx_eegrant_email')],
            },
        ),
        migrations.CreateModel(
            name='EELicenseInstance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance_id', models.UUIDField(help_text='Self-generated UUID on instance.', unique=True)),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('version', models.CharField(blank=True, default='', max_length=50)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True, help_text='False if no heartbeat for 30 days.')),
                ('license_grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='usage.eelicensegrant')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EEInstanceHeartbeat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(help_text='When heartbeat was received.')),
                ('traces_this_month', models.BigIntegerField(default=0)),
                ('gateway_this_month', models.BigIntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('version', models.CharField(blank=True, default='', max_length=50)),
                ('payload', models.JSONField(blank=True, help_text='Full heartbeat data.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('license_grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='usage.eelicensegrant')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='usage.eelicenseinstance')),
            ],
            options={
                'indexes': [models.Index(fields=['license_grant', '-timestamp'], name='idx_heartbeat_grant_ts'), models.Index(fields=['instance', '-timestamp'], name='idx_heartbeat_inst_ts')],
            },
        ),
    ]
