# Generated by Django 5.1.8 on 2026-03-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0014_eelicensegrant_eelicenseinstance_eeinstanceheartbeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeProductMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(choices=[('boost_monthly', 'Boost Monthly'), ('boost_annual', 'Boost Annual'), ('scale_monthly', 'Scale Monthly'), ('scale_annual', 'Scale Annual'), ('enterprise_monthly', 'Enterprise Monthly'), ('enterprise_annual', 'Enterprise Annual'), ('storage', 'Storage (GB)'), ('ai_credits', 'AI Credits'), ('gateway_requests', 'Gateway Requests'), ('gateway_cache_hits', 'Gateway Cache Hits'), ('text_sim_tokens', 'Text Sim Tokens'), ('voice_sim_minutes', 'Voice Sim Minutes'), ('tracing_events', 'Tracing Events')], db_index=True, help_text='Billing key — maps to a plan add-on or usage dimension.', max_length=50, unique=True)),
                ('stripe_product_id', models.CharField(help_text='Stripe Product ID (prod_xxx).', max_length=100)),
                ('stripe_price_id', models.CharField(help_text='Stripe Price ID (price_xxx).', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive entries are ignored during lookups.')),
            ],
            options={
                'verbose_name': 'Stripe Product Map',
                'verbose_name_plural': 'Stripe Product Maps',
            },
        ),
    ]
