# Generated by Django 5.1.8 on 2026-03-31 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0015_backfill_plan_and_wallet_credits'),
        ('usage', '0015_stripeproductmap'),
    ]

    operations = [
    ]
