# Generated by Django 5.1.8 on 2026-04-06 10:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_blockedkeyproxy'),
        ('usage', '0016_merge_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsubscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('payg', 'Pay-as-you-go'), ('boost', 'Boost'), ('scale', 'Scale'), ('enterprise', 'Enterprise'), ('custom', 'Custom')], db_index=True, default='free', help_text='Current billing plan. Source of truth for entitlements.', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationsubscription',
            name='stripe_customer_id_live',
            field=models.CharField(blank=True, help_text='Stripe customer ID for live mode. NULL values are allowed.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organizationsubscription',
            name='stripe_customer_id_test',
            field=models.CharField(blank=True, help_text='Stripe customer ID for test mode. NULL values are allowed.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organizationsubscription',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='planentitlement',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('payg', 'Pay-as-you-go'), ('boost', 'Boost'), ('scale', 'Scale'), ('enterprise', 'Enterprise'), ('custom', 'Custom')], help_text='Which plan this value applies to.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='organizationsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_customer_id_test__isnull', False)), fields=('stripe_customer_id_test',), name='uq_orgsub_stripe_test_not_null'),
        ),
        migrations.AddConstraint(
            model_name='organizationsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_customer_id_live__isnull', False)), fields=('stripe_customer_id_live',), name='uq_orgsub_stripe_live_not_null'),
        ),
    ]
