# Generated by Django 5.1.8 on 2026-04-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0017_add_custom_plan_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpricing',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=8, help_text='Price per display unit ($2.00 per GB, $0.000015 per request).', max_digits=16),
        ),
    ]
