# Generated by Django 5.1.8 on 2026-04-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0018_increase_price_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsubscription',
            name='contract_end_date',
            field=models.DateField(blank=True, help_text='End date of the custom plan contract. After this date, a final usage-only invoice is generated and plan reverts to free.', null=True),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='platform_fee_billing_cycle',
            field=models.PositiveIntegerField(default=1, help_text='Months between platform fee charges for custom plans. 1=monthly, 3=quarterly, 6=semi-annual, 12=annual. Per-charge amount = subscription_price * billing_cycle / 12.'),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='stripe_fee_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe subscription ID for platform fee (custom plans only).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organizationsubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe subscription ID for metered usage billing.', max_length=100, null=True),
        ),
    ]
