# Generated by Django 5.1.8 on 2026-04-09 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0017_decimal_usage_fields'),
        ('usage', '0019_add_custom_plan_fields'),
    ]

    operations = [
    ]
