# Generated by Django 5.1.8 on 2026-04-15 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0020_merge_20260409_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationsubscription',
            name='is_dev_account',
        ),
    ]
