# Generated by Django 5.1.8 on 2026-04-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0021_add_code_evaluator_choice'),
        ('usage', '0021_remove_is_dev_account'),
    ]

    operations = [
    ]
