# Generated by Django 5.1.8 on 2026-05-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0023_unlock_features_free_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usageeventlog',
            name='amount_display',
            field=models.DecimalField(decimal_places=6, help_text='Units consumed in display units (GB, credits).', max_digits=16),
        ),
        migrations.AlterField(
            model_name='usagesummary',
            name='reported_to_stripe',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Last value reported to Stripe. Used for delta reporting.', max_digits=16),
        ),
        migrations.AlterField(
            model_name='usagesummary',
            name='total_usage',
            field=models.DecimalField(decimal_places=6, help_text='Cumulative usage in display units (GB, credits).', max_digits=16),
        ),
    ]
