# Generated by Django 5.1.8 on 2026-07-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0026_deployment_telemetry'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsubscription',
            name='card_last_4_digits',
            field=models.CharField(blank=True, default='', help_text='Last 4 digits of the default payment method.', max_length=4),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='card_network_logo_url',
            field=models.CharField(blank=True, default='', help_text="Logo URL for the default payment method's card network.", max_length=255),
        ),
        migrations.AlterField(
            model_name='organizationsubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('unpaid', 'Unpaid'), ('canceled', 'Canceled'), ('inactive', 'Inactive')], default='active', max_length=50),
        ),
    ]
