# Generated by Django 5.1.8 on 2026-08-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0027_organizationsubscription_card_last_4_digits_and_more'),
        ('usage', '0028_delete_deploymenttelemetryheartbeat_and_more'),
    ]

    operations = [
    ]
