"""EE-only model additions (private).

Models that exist only in the enterprise catalog: FutureAGI turing_* and
protect_* models, company-specific Bedrock inference-profile ARNs, and a few
regional/dated provider variants. Merged onto the OSS base by
``agentic_eval.core_evals.run_prompt.available_models``.
"""

import os

# FutureAGI's Bedrock inference-profile ARNs are account- and region-specific.
# The account id and region are supplied at deploy time (env) rather than baked
# into source, so this file — imported verbatim into the public OSS cut — does
# not publish an internal AWS account id. When the account id is unset (e.g. a
# public OSS deployment with no FutureAGI Bedrock access), the entry falls back
# to a bare ``bedrock/<profile>`` reference; the managed deployment injects the
# account id via env so the full ARN is used there.
_BEDROCK_ACCOUNT_ID = os.environ.get("FUTUREAGI_BEDROCK_ACCOUNT_ID", "").strip()
_BEDROCK_REGION = os.environ.get("FUTUREAGI_BEDROCK_REGION", "us-east-1").strip()


def _bedrock_arn(profile_id: str) -> str:
    """Build a Bedrock inference-profile model id from the deploy-time account
    id/region. Full ARN when the account id is configured, else a bare
    ``bedrock/<profile>`` reference."""
    if _BEDROCK_ACCOUNT_ID:
        return (
            f"bedrock/arn:aws:bedrock:{_BEDROCK_REGION}:{_BEDROCK_ACCOUNT_ID}"
            f":inference-profile/{profile_id}"
        )
    return f"bedrock/{profile_id}"


EE_ONLY_AVAILABLE_MODELS = [
    {
        "model_name": "gpt-4o-2024-11-20",
        "providers": "openai",
        "api_key_name": "OPENAI_API_KEY",
        "mode": "chat",
        "best_for": ["advanced reasoning", "coding", "multimodal (vision, audio)"],
        "use_case": [
            "solve complex problems",
            "analyze large documents or codebases",
            "understand images and text",
        ],
        "cutoff": "10-2023",
        "rate_limits": {
            "requests_per_minute": 10,
            "free": {"requests_per_minute": 10, "requests_per_day": 1000},
        },
        "latency": 90,
        "pricing": {"input_per_1M_tokens": 5, "output_per_1M_tokens": 15},
    },
    {
        "model_name": "turing_large",
        "providers": "turing",
        "api_key_name": "FUTURE_AGI_API_KEY",
        "mode": "chat",
        "best_for": ["most capable evaluator tasks", "complex reasoning", "research"],
        "use_case": ["LLM-as-judge evaluation", "complex analysis", "agent evaluation"],
        "cutoff": "09-2025",
        "latency": 500,
        "pricing": {"input_per_1M_tokens": 5.5, "output_per_1M_tokens": 27.5},
    },
    {
        "model_name": "turing_large_xl",
        "providers": "turing",
        "api_key_name": "FUTURE_AGI_API_KEY",
        "mode": "chat",
        "best_for": [
            "multimodal evaluator tasks",
            "audio evaluation",
            "PDF evaluation",
        ],
        "use_case": [
            "LLM-as-judge evaluation",
            "multimodal analysis",
            "agent evaluation",
        ],
        "cutoff": "01-2025",
        "latency": 900,
        "pricing": {"input_per_1M_tokens": 1.25, "output_per_1M_tokens": 10},
    },
    {
        "model_name": "turing_small",
        "providers": "turing",
        "api_key_name": "FUTURE_AGI_API_KEY",
        "mode": "chat",
        "best_for": ["advanced evaluator tasks", "agentic tasks", "complex reasoning"],
        "use_case": ["LLM-as-judge evaluation", "software evaluation", "data analysis"],
        "cutoff": "07-2025",
        "latency": 300,
        "pricing": {"input_per_1M_tokens": 3.3, "output_per_1M_tokens": 16.5},
    },
    {
        "model_name": "turing_flash",
        "providers": "turing",
        "api_key_name": "FUTURE_AGI_API_KEY",
        "mode": "chat",
        "best_for": [
            "fast evaluator tasks",
            "cost-effective checks",
            "high-throughput",
        ],
        "use_case": ["classification", "summarization", "quick evaluation"],
        "cutoff": "08-2025",
        "latency": 100,
        "pricing": {"input_per_1M_tokens": 1.1, "output_per_1M_tokens": 5.5},
    },
    {
        "model_name": _bedrock_arn("us.anthropic.claude-3-5-sonnet-20240620-v1:0"),
        "providers": "bedrock",
        "api_key_name": "AWS_ACCESS_KEY_ID",
        "mode": "chat",
        "best_for": ["coding", "reasoning", "long context"],
        "use_case": ["complex problem solving", "code generation", "data analysis"],
        "cutoff": "04-2024",
        "latency": 300,
        "pricing": {"input_per_1M_tokens": 3, "output_per_1M_tokens": 15},
    },
    {
        "model_name": _bedrock_arn("us.anthropic.claude-3-7-sonnet-20250219-v1:0"),
        "providers": "bedrock",
        "api_key_name": "AWS_ACCESS_KEY_ID",
        "mode": "chat",
        "best_for": ["extended thinking", "complex reasoning", "coding"],
        "use_case": ["agentic tasks", "complex problem solving", "code generation"],
        "cutoff": "11-2024",
        "latency": 300,
        "pricing": {"input_per_1M_tokens": 3, "output_per_1M_tokens": 15},
    },
    {
        "model_name": _bedrock_arn("global.anthropic.claude-sonnet-4-20250514-v1:0"),
        "providers": "bedrock",
        "api_key_name": "AWS_ACCESS_KEY_ID",
        "mode": "chat",
        "best_for": ["advanced coding", "agentic tasks", "complex reasoning"],
        "use_case": ["software development", "customer-facing AI", "data analysis"],
        "cutoff": "03-2025",
        "latency": 300,
        "pricing": {"input_per_1M_tokens": 3, "output_per_1M_tokens": 15},
    },
    {
        "model_name": _bedrock_arn("global.anthropic.claude-sonnet-4-5-20250929-v1:0"),
        "providers": "bedrock",
        "api_key_name": "AWS_ACCESS_KEY_ID",
        "mode": "chat",
        "best_for": ["advanced coding", "agentic tasks", "complex reasoning"],
        "use_case": ["software development", "customer-facing AI", "data analysis"],
        "cutoff": "07-2025",
        "latency": 300,
        "pricing": {"input_per_1M_tokens": 3, "output_per_1M_tokens": 15},
    },
    {
        "model_name": _bedrock_arn("us.anthropic.claude-sonnet-4-5-20250929-v1:0"),
        "providers": "bedrock",
        "api_key_name": "AWS_ACCESS_KEY_ID",
        "mode": "chat",
        "best_for": ["advanced coding", "agentic tasks", "complex reasoning"],
        "use_case": ["software development", "customer-facing AI", "data analysis"],
        "cutoff": "07-2025",
        "latency": 300,
        "pricing": {"input_per_1M_tokens": 3.3, "output_per_1M_tokens": 16.5},
    },
    {
        "model_name": _bedrock_arn("us.anthropic.claude-opus-4-5-20251101-v1:0"),
        "providers": "bedrock",
        "api_key_name": "AWS_ACCESS_KEY_ID",
        "mode": "chat",
        "best_for": ["most capable tasks", "complex reasoning", "research"],
        "use_case": [
            "frontier AI tasks",
            "complex analysis",
            "long-horizon agentic work",
        ],
        "cutoff": "09-2025",
        "latency": 500,
        "pricing": {"input_per_1M_tokens": 5.5, "output_per_1M_tokens": 27.5},
    },
    {
        "model_name": _bedrock_arn("us.anthropic.claude-haiku-4-5-20251001-v1:0"),
        "providers": "bedrock",
        "api_key_name": "AWS_ACCESS_KEY_ID",
        "mode": "chat",
        "best_for": ["fast responses", "cost-effective tasks", "high-throughput"],
        "use_case": ["classification", "summarization", "quick reasoning"],
        "cutoff": "08-2025",
        "latency": 100,
        "pricing": {"input_per_1M_tokens": 1.1, "output_per_1M_tokens": 5.5},
    },
    {
        "model_name": "us.anthropic.claude-sonnet-4-6",
        "providers": "bedrock",
        "api_key_name": "AWS_ACCESS_KEY_ID",
        "mode": "chat",
        "best_for": ["advanced coding", "agentic tasks", "complex reasoning"],
        "use_case": ["software development", "customer-facing AI", "data analysis"],
        "cutoff": "04-2026",
        "latency": 300,
        "pricing": {"input_per_1M_tokens": 3, "output_per_1M_tokens": 15},
    },
    {
        "model_name": "global.anthropic.claude-sonnet-4-6",
        "providers": "bedrock",
        "api_key_name": "AWS_ACCESS_KEY_ID",
        "mode": "chat",
        "best_for": ["advanced coding", "agentic tasks", "complex reasoning"],
        "use_case": ["software development", "customer-facing AI", "data analysis"],
        "cutoff": "04-2026",
        "latency": 300,
        "pricing": {"input_per_1M_tokens": 3, "output_per_1M_tokens": 15},
    },
    {
        "model_name": "eu.anthropic.claude-sonnet-4-6",
        "providers": "bedrock",
        "api_key_name": "AWS_ACCESS_KEY_ID",
        "mode": "chat",
        "best_for": ["advanced coding", "agentic tasks", "complex reasoning"],
        "use_case": ["software development", "customer-facing AI", "data analysis"],
        "cutoff": "04-2026",
        "latency": 300,
        "pricing": {"input_per_1M_tokens": 3, "output_per_1M_tokens": 15},
    },
    {
        "model_name": "us.anthropic.claude-opus-4-6",
        "providers": "bedrock",
        "api_key_name": "AWS_ACCESS_KEY_ID",
        "mode": "chat",
        "best_for": ["complex reasoning", "long-context analysis", "frontier tasks"],
        "use_case": ["research", "business intelligence", "long-horizon agentic work"],
        "cutoff": "04-2026",
        "latency": 400,
        "pricing": {"input_per_1M_tokens": 5, "output_per_1M_tokens": 25},
    },
    {
        "model_name": "us.anthropic.claude-sonnet-4-5-20250929",
        "providers": "bedrock",
        "api_key_name": "AWS_ACCESS_KEY_ID",
        "mode": "chat",
        "best_for": ["advanced coding", "agentic tasks", "complex reasoning"],
        "use_case": ["software development", "customer-facing AI", "data analysis"],
        "cutoff": "07-2025",
        "latency": 300,
        "pricing": {"input_per_1M_tokens": 3, "output_per_1M_tokens": 15},
    },
    {
        "model_name": "us.anthropic.claude-opus-4-5-20251101",
        "providers": "bedrock",
        "api_key_name": "AWS_ACCESS_KEY_ID",
        "mode": "chat",
        "best_for": ["frontier reasoning", "long-context analysis", "research"],
        "use_case": ["complex analysis", "long-horizon agentic work", "research"],
        "cutoff": "09-2025",
        "latency": 500,
        "pricing": {"input_per_1M_tokens": 5, "output_per_1M_tokens": 25},
    },
    {
        "model_name": "us.anthropic.claude-haiku-4-5-20251001",
        "providers": "bedrock",
        "api_key_name": "AWS_ACCESS_KEY_ID",
        "mode": "chat",
        "best_for": ["fast responses", "cost-effective tasks", "high-throughput"],
        "use_case": ["classification", "summarization", "quick reasoning"],
        "cutoff": "08-2025",
        "latency": 100,
        "pricing": {"input_per_1M_tokens": 1, "output_per_1M_tokens": 5},
    },
    {
        "model_name": "us.anthropic.claude-sonnet-4-20250514",
        "providers": "bedrock",
        "api_key_name": "AWS_ACCESS_KEY_ID",
        "mode": "chat",
        "best_for": ["advanced coding", "agentic tasks", "complex reasoning"],
        "use_case": ["software development", "customer-facing AI", "data analysis"],
        "cutoff": "03-2025",
        "latency": 300,
        "pricing": {"input_per_1M_tokens": 3, "output_per_1M_tokens": 15},
    },
    {
        "model_name": "vertex_ai/gemini-2.5-pro",
        "providers": "vertex_ai",
        "api_key_name": "VERTEX_AI_API_KEY",
        "mode": "chat",
        "best_for": [
            "Advanced reasoning",
            "Complex coding",
            "Multimodal comprehension",
        ],
        "use_case": [
            "Research assistants",
            "Enterprise chatbots",
            "Complex workflow automation",
        ],
        "cutoff": "01-2025",
        "rate_limits": {
            "requests_per_minute": 1000,
            "free": {"requests_per_minute": None, "requests_per_day": 50000},
        },
        "latency": 900,
        "pricing": {"input_per_1M_tokens": 1.25, "output_per_1M_tokens": 10},
    },
    {
        "model_name": "vertex_ai/gemini-3.6-flash",
        "providers": "vertex_ai",
        "api_key_name": "VERTEX_AI_API_KEY",
        "mode": "chat",
        "best_for": [
            "latest Flash GA on Vertex",
            "multimodal understanding",
            "agentic tasks",
        ],
        "use_case": [
            "enterprise chatbots",
            "fast inference at scale",
            "content processing",
        ],
        "cutoff": "06-2026",
        "latency": 400,
        "pricing": {"input_per_1M_tokens": 1.5, "output_per_1M_tokens": 7.5},
        "notes": "Global tier pricing; Non-global regions are ~10% higher.",
    },
    {
        "model_name": "vertex_ai/gemini-3.5-flash",
        "providers": "vertex_ai",
        "api_key_name": "VERTEX_AI_API_KEY",
        "mode": "chat",
        "best_for": ["agentic and coding tasks on Vertex", "multimodal understanding"],
        "use_case": ["enterprise agents", "code generation", "long-context reasoning"],
        "cutoff": "04-2026",
        "latency": 450,
        "pricing": {"input_per_1M_tokens": 1.5, "output_per_1M_tokens": 9.0},
        "notes": "Global tier pricing; Non-global regions are ~10% higher.",
    },
    {
        "model_name": "vertex_ai/gemini-3.5-flash-lite",
        "providers": "vertex_ai",
        "api_key_name": "VERTEX_AI_API_KEY",
        "mode": "chat",
        "best_for": ["ultra-low latency on Vertex", "cost-optimized workloads"],
        "use_case": ["high volume batch processing", "real-time agents"],
        "cutoff": "04-2026",
        "latency": 250,
        "pricing": {"input_per_1M_tokens": 0.3, "output_per_1M_tokens": 2.5},
        "notes": "Global tier pricing; Non-global regions are ~10% higher.",
    },
    {
        "model_name": "vertex_ai/gemini-3.1-pro-preview",
        "providers": "vertex_ai",
        "api_key_name": "VERTEX_AI_API_KEY",
        "mode": "chat",
        "best_for": [
            "flagship reasoning on Vertex",
            "long-context multimodal analysis",
        ],
        "use_case": [
            "complex reasoning",
            "STEM problem solving",
            "long-document analysis",
        ],
        "cutoff": "04-2026",
        "latency": 1000,
        "pricing": {"input_per_1M_tokens": 2.0, "output_per_1M_tokens": 12.0},
        "notes": "Preview tier. Above 200K input tokens: $4/$18 in/out per 1M tokens.",
    },
    {
        "model_name": "vertex_ai/gemini-3-flash-preview",
        "providers": "vertex_ai",
        "api_key_name": "VERTEX_AI_API_KEY",
        "mode": "chat",
        "best_for": ["Gemini 3 base Flash on Vertex", "fast multimodal"],
        "use_case": ["enterprise chat", "fast inference", "agent orchestration"],
        "cutoff": "04-2026",
        "latency": 400,
        "pricing": {"input_per_1M_tokens": 0.5, "output_per_1M_tokens": 3.0},
        "notes": "Preview tier.",
    },
    {
        "model_name": "vertex_ai/gemini-3.1-flash-lite",
        "providers": "vertex_ai",
        "api_key_name": "VERTEX_AI_API_KEY",
        "mode": "chat",
        "best_for": ["cost-optimized workloads on Vertex", "high throughput"],
        "use_case": ["batch processing", "real-time agents", "classification"],
        "cutoff": "04-2026",
        "latency": 250,
        "pricing": {"input_per_1M_tokens": 0.25, "output_per_1M_tokens": 1.5},
        "notes": "GA Flash-Lite 3.1 on Vertex.",
    },
    {
        "model_name": "vertex_ai/gemini-3.1-flash-image",
        "providers": "vertex_ai",
        "api_key_name": "VERTEX_AI_API_KEY",
        "mode": "image_generation",
        "best_for": ["fast image generation on Vertex", "text-to-image"],
        "use_case": ["marketing assets", "creative iteration"],
        "cutoff": "04-2026",
        "latency": 100,
        "pricing": {"per_image": 0.067},
        "notes": "Gemini 3.1 Flash image generation on Vertex. "
        "per_image is the 1K (~1MP) equivalent.",
    },
    {
        "model_name": "vertex_ai/gemini-2.5-flash-image",
        "providers": "vertex_ai",
        "api_key_name": "VERTEX_AI_API_KEY",
        "mode": "image_generation",
        "best_for": ["cost-effective image generation on Vertex"],
        "use_case": ["batch image generation", "creative iteration"],
        "cutoff": "01-2025",
        "latency": 110,
        "pricing": {"per_image": 0.039},
        "notes": "GA Gemini 2.5 Flash image gen on Vertex. "
        "per_image is the 1K (~1MP) equivalent.",
    },
    {
        "model_name": "protect_toxicity",
        "providers": "futureagi",
        "mode": "moderation",
        "pricing": {"input_per_1M_tokens": 0.02, "output_per_1M_tokens": 0.02},
        "best_for": ["toxicity detection", "content safety"],
        "use_case": ["guardrails", "content moderation"],
        "speed": "fast",
        "notes": "FutureAGI Protect model for toxicity detection. Supports text, image, and audio "
        "inputs.",
    },
    {
        "model_name": "protect_bias",
        "providers": "futureagi",
        "mode": "moderation",
        "pricing": {"input_per_1M_tokens": 0.02, "output_per_1M_tokens": 0.02},
        "best_for": ["bias detection", "fairness evaluation"],
        "use_case": ["guardrails", "bias screening"],
        "speed": "fast",
        "notes": "FutureAGI Protect model for bias and discrimination detection.",
    },
    {
        "model_name": "protect_privacy",
        "providers": "futureagi",
        "mode": "moderation",
        "pricing": {"input_per_1M_tokens": 0.02, "output_per_1M_tokens": 0.02},
        "best_for": ["PII detection", "data privacy compliance"],
        "use_case": ["guardrails", "privacy screening"],
        "speed": "fast",
        "notes": "FutureAGI Protect model for data privacy and PII detection.",
    },
    {
        "model_name": "protect_prompt_injection",
        "providers": "futureagi",
        "mode": "moderation",
        "pricing": {"input_per_1M_tokens": 0.02, "output_per_1M_tokens": 0.02},
        "best_for": ["prompt injection detection", "security"],
        "use_case": ["guardrails", "prompt security"],
        "speed": "fast",
        "notes": "FutureAGI Protect model for prompt injection attack detection.",
    },
    {
        "model_name": "protect_flash",
        "providers": "futureagi",
        "mode": "moderation",
        "pricing": {"input_per_1M_tokens": 0.01, "output_per_1M_tokens": 0.01},
        "best_for": ["all-in-one content safety", "fast moderation"],
        "use_case": ["guardrails", "content moderation"],
        "speed": "very fast",
        "notes": "FutureAGI Protect Flash — single-model all-in-one safety detection for toxicity, "
        "bias, privacy, and prompt injection.",
    },
]
