import litellm
import logging
import time
import json
from pydantic import BaseModel, Field, ValidationError
from typing import List, Dict, Any, Optional, Callable

from ..base.evaluator import Evaluator
from ..base.base_optimizer import BaseOptimizer
from ..base.base_generator import BaseGenerator

from ..datamappers import BasicDataMapper
from ..types import IterationHistory, OptimizationResult
from simulate.utils.agent_prompt_optimiser import update_agent_optimiser_run_step
from .stepper import RandomSearchStepper

# Type for the per-trial callback
OnTrialCallback = Callable[[dict, int, Dict[str, Any], bool], None]

logger = logging.getLogger(__name__)


class PromptVariations(BaseModel):
    """Output model for prompt variations generated by the teacher model."""

    variations: List[str] = Field(
        description="A list of prompt variations.",
    )


class RandomSearchOptimizer(BaseOptimizer):
    """
    A simple optimization strategy that tries a number of random prompt variations
    generated by a powerful "teacher" model.
    """

    def __init__(
        self,
        generator: BaseGenerator,
        teacher_model: str = "gpt-5",
        num_variations: int = 5,
        teacher_model_kwargs: Dict[str, Any] = {},
        eval_template: str = "summary_quality",
        eval_model_name: str = "turing_flash",
    ):
        """
        Initializes the Random Search Optimizer.

        Args:
            generator: The generator to be optimized.
            teacher_model: A powerful LLM to generate prompt variations.
            num_variations: The number of random variations to try.
            teacher_model_kwargs: A dictionary of kwargs to pass to the teacher model.
            eval_template: The evaluation template to use from the ai-evaluation library.
            eval_model_name: The model to use for evaluation.
        """
        self.generator = generator
        self.teacher_model = teacher_model
        self.num_variations = num_variations

        if teacher_model_kwargs is None and "gpt" in teacher_model:
            self.teacher_model_kwargs = {"temperature": 1.0, "max_tokens": 16000}
        else:
            self.teacher_model_kwargs = teacher_model_kwargs or {}

        self.api_key = None
        super().__init__()

    def optimize(
        self,
        evaluator: Evaluator,
        data_mapper: BasicDataMapper,
        dataset: List[Dict[str, Any]],
        resume_state: Optional[Dict[str, Any]] = None,
        max_new_trials: Optional[int] = None,
        on_trial_callback: Optional[OnTrialCallback] = None,
        task_description: str = "",
        **kwargs: Any,
    ) -> OptimizationResult:
        logger.info("--- Starting Random Search Optimization ---")

        if "api_key" in kwargs:
            self.api_key = kwargs["api_key"]

        run_steps = kwargs.get("agent_optimiser_run_steps")
        self._task_description = task_description

        optimization_start_time = time.time()

        initial_prompt = self.generator.get_prompt_template()
        history = []

        # Initial status update: Optimizing (Generating variations)
        update_agent_optimiser_run_step(
            run_steps,
            3,
            description=f"Trial 0 running: Generating {self.num_variations} Variations...",
        )

        stepper_config = {
            "teacher_model": self.teacher_model,
            "teacher_model_kwargs": self.teacher_model_kwargs,
            "num_variations": self.num_variations,
            "api_key": self.api_key,
        }

        if resume_state:
            stepper = RandomSearchStepper.from_state(
                resume_state,
                config=stepper_config,
                variation_generator=_generate_variations,
                task_description=task_description,
            )
        else:
            stepper = RandomSearchStepper.from_config(
                initial_prompt=initial_prompt,
                num_variations=self.num_variations,
                teacher_model=self.teacher_model,
                teacher_model_kwargs=self.teacher_model_kwargs,
                api_key=self.api_key,
                variation_generator=_generate_variations,
                task_description=task_description,
            )

        while True:
            variation = stepper.next_candidate()
            if variation is None:
                break
            if max_new_trials is not None and max_new_trials <= 0:
                break

            iteration_start_time = time.time()
            trial_number = stepper.current_index + 1
            total_variations = len(stepper.variations)

            logger.info(f"--- Testing Variation {trial_number}/{total_variations} ---")
            logger.info(f"Prompt: {variation[:200]}...")

            update_agent_optimiser_run_step(
                run_steps,
                3,
                description=(
                    f"Trial {trial_number} Running: "
                    f"Simulating Variation {trial_number}/{total_variations}..."
                ),
            )

            self.generator.set_prompt_template(variation)

            # For PROMPT OPTIMIZATION: the prompt IS the output
            # We pass it directly to the evaluator (simulations run with this prompt)
            generated_outputs = [variation] * len(dataset)

            eval_inputs = [
                data_mapper.map(gen_output, example)
                for gen_output, example in zip(generated_outputs, dataset)
            ]

            # Time evaluation
            update_agent_optimiser_run_step(
                run_steps,
                3,
                description=(
                    f"Trial {trial_number} Running: "
                    f"Evaluating Variation {trial_number}/{total_variations}..."
                ),
            )
            evaluation_start_time = time.time()
            evaluation_results = evaluator.evaluate(eval_inputs)

            stored_variation = variation
            if eval_inputs and "agent_prompt" in eval_inputs[0]:
                repaired = eval_inputs[0]["agent_prompt"]
                if repaired != variation:
                    stored_variation = repaired

            evaluation_end_time = time.time()
            logger.info(
                f"Evaluation for {len(dataset)} examples took {evaluation_end_time - evaluation_start_time:.2f} seconds."
            )

            if not evaluation_results:
                logger.warning(
                    "No evaluation results were returned for this variation."
                )
                stepper.on_result(prompt=variation, score=float("-inf"))
                if max_new_trials is not None:
                    max_new_trials -= 1
                continue

            # Calculate average score for decision-making
            avg_score = sum(res.score for res in evaluation_results) / len(
                evaluation_results
            )
            logger.info(f"Average Score for Variation {trial_number}: {avg_score:.4f}")

            iteration_history = IterationHistory(
                prompt=stored_variation,
                average_score=avg_score,
                individual_results={
                    dataset[idx].get("call_execution_id", "unknown"): res
                    for idx, res in enumerate(evaluation_results)
                },
            )
            history.append(iteration_history)

            stepper.on_result(prompt=variation, score=avg_score)

            # Call callback to persist trial immediately
            if on_trial_callback:
                on_trial_callback(
                    trial_data=iteration_history.dict(),
                    trial_number=trial_number,
                    stepper_state=stepper.to_state(),
                    is_baseline=False,
                )

            iteration_end_time = time.time()
            logger.info(
                f"--- Variation {trial_number} finished in {iteration_end_time - iteration_start_time:.2f} seconds ---"
            )

            update_agent_optimiser_run_step(
                run_steps,
                3,
                description=(
                    f"Trial {trial_number} Completed. "
                    f"Variation {trial_number}/{total_variations}."
                ),
            )
            if max_new_trials is not None:
                max_new_trials -= 1

        self.generator.set_prompt_template(stepper.best_prompt)

        optimization_end_time = time.time()
        logger.info(
            f"--- Random Search Optimization finished in {optimization_end_time - optimization_start_time:.2f} seconds ---"
        )

        return OptimizationResult(
            best_prompt=stepper.best_prompt,
            history=history,
            final_score=stepper.best_score,
            stepper_state=stepper.to_state(),
        )


def _get_max_output_tokens(model: str) -> int:
    """Get the max output tokens for a model using ParametersValidator + litellm fallback."""
    try:
        from agentic_eval.core_evals.run_prompt.runprompt_handlers.utils.parameter_validator import (
            ParametersValidator,
        )

        validator = ParametersValidator(model)
        if validator._model_info:
            max_tokens = validator._model_info.get(
                "max_tokens"
            ) or validator._model_info.get("max_output_tokens")
            if max_tokens:
                return int(max_tokens)
    except Exception as e:
        logger.warning(f"ParametersValidator lookup failed for {model}: {e}")

    # Fallback: litellm.get_max_tokens
    try:
        max_tokens = litellm.get_max_tokens(model)
        if max_tokens:
            return int(max_tokens)
    except Exception:
        pass

    return 16000  # final fallback


def _generate_variations(
    initial_prompt: str,
    num_variations: int,
    teacher_model: str,
    teacher_model_kwargs: Dict[str, Any],
    api_key: Optional[str],
    task_description: str = "",
) -> List[str]:
    """Generate prompt variations using the teacher model."""
    logger.info(
        f"Generating {num_variations} prompt variations with teacher model: {teacher_model}..."
    )

    task_desc_section = (
        f"\nTask Description/Constraints:\n{task_description}\n"
        if task_description
        else ""
    )

    instruction = f"""You are an expert in prompt engineering. Your task is to generate {num_variations} variations of the following prompt.

CRITICAL RULES:
- Each variation MUST be approximately the SAME LENGTH as the original prompt. Do NOT summarize or condense.
- Preserve the COMPLETE structure: all sections, all instructions, all rules, all formatting.
- Only change wording, phrasing, ordering of sections, or emphasis — NOT the content coverage.
- The variations should be diverse and explore different styles.

Return ONLY a JSON object with a key "variations" containing a list of strings. For example:
{{"variations": ["prompt 1", "prompt 2", ...]}}
{task_desc_section}
Original Prompt ({len(initial_prompt)} characters — each variation must be similar length):
---
{initial_prompt}
---
"""
    messages = [{"role": "user", "content": instruction}]
    response_content = ""

    try:
        teacher_kwargs = teacher_model_kwargs.copy()
        teacher_kwargs["response_format"] = {"type": "json_object"}

        # Set max_tokens to the model's actual limit so large prompts don't get truncated
        model_max_tokens = _get_max_output_tokens(teacher_model)
        teacher_kwargs["max_tokens"] = model_max_tokens
        logger.info(
            f"Using max_tokens={model_max_tokens} for teacher model {teacher_model}"
        )

        response = litellm.completion(
            model=teacher_model,
            messages=messages,
            api_key=api_key,
            **teacher_kwargs,
            drop_params=True,
        )
        response_content = response.choices[0].message.content

        if isinstance(response_content, str):
            if response_content.strip().startswith("```json"):
                response_content = response_content.strip()[7:-3].strip()

        prompt_variations = PromptVariations.model_validate_json(response_content)
        return prompt_variations.variations

    except (ValidationError, json.JSONDecodeError) as e:
        logger.error(f"Failed to parse teacher model response: {e}")
        raise RuntimeError("Teacher model returned invalid JSON") from e
    except Exception as e:
        logger.error(f"An error occurred with the teacher model: {e}")
        raise RuntimeError(f"Teacher model call failed: {e}") from e
