"""
Simple voice mapping system to select voice_id based on persona attributes.
"""

import json
import random
import traceback
from typing import Optional

from agentic_eval.core.llm.llm import LLM
from tracer.models.observability_provider import ProviderChoices

PERSONA_FIELD_CONSTRAINTS = {
    "gender": ["male", "female"],
    "age_group": ["18-25", "25-32", "32-40", "40-50", "50-60", "60+"],
    "location": ["United States", "Canada", "United Kingdom", "Australia", "India"],
    "profession": [
        "Student",
        "Teacher",
        "Engineer",
        "Doctor",
        "Nurse",
        "Business Owner",
        "Manager",
        "Sales Representative",
        "Customer Service",
        "Technician",
        "Consultant",
        "Accountant",
        "Marketing Professional",
        "Retired",
        "Homemaker",
        "Freelancer",
        "Other",
    ],
    "personality": [
        "Friendly and cooperative",
        "Professional and formal",
        "Cautious and skeptical",
        "Impatient and direct",
        "Detail-oriented",
        "Easy-going",
        "Anxious",
        "Confident",
        "Analytical",
        "Emotional",
        "Reserved",
        "Talkative",
    ],
    "communication_style": [
        "Direct and concise",
        "Detailed and elaborate",
        "Casual and friendly",
        "Formal and polite",
        "Technical",
        "Simple and clear",
        "Questioning",
        "Assertive",
        "Passive",
        "Collaborative",
    ],
    "accent": ["American", "Australian", "Indian", "Canadian", "Neutral"],
    # Language options using full names (will be converted to codes during assistant creation)
    "language": ["English", "Hindi"],
    "conversation_speed": ["0.5", "0.75", "1.0", "1.25", "1.5"],
    "background_sound": ["true", "false"],
    "finished_speaking_sensitivity": [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
    ],
    "interrupt_sensitivity": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
}


# Voice mapping based on persona characteristics
VOICE_MAPPING = {
    "gender": {
        "male": [
            "burt",
            "phillip",
            "steve",
            "joseph",
            "ryan",
            "drew",
            "paul",
            "mrb",
            "mark",
        ],
        "female": ["marissa", "andrea", "sarah", "myra", "paula", "matilda"],
        "non-binary": ["andrea", "drew", "sarah", "steve"],  # Neutral/versatile voices
    },
    "age_group": {
        "18-25": ["ryan", "drew", "matilda", "paula"],
        "25-32": ["steve", "sarah", "paula", "andrea", "joseph"],
        "32-40": ["marissa", "andrea", "joseph", "phillip", "mark"],
        "40-50": ["phillip", "marissa", "paul", "myra"],
        "50-60": ["burt", "paul", "myra", "phillip"],
        "60+": ["burt", "paul", "myra", "mrb"],
    },
    "personality": {
        "Friendly and cooperative": ["steve", "drew", "sarah", "andrea"],
        "Professional and formal": ["phillip", "marissa", "joseph", "mark"],
        "Cautious and skeptical": ["paul", "myra", "andrea"],
        "Impatient and direct": ["ryan", "paula", "marissa"],
        "Detail-oriented": ["mark", "andrea", "joseph"],
        "Easy-going": ["steve", "drew", "sarah"],
        "Anxious": ["myra", "drew", "sarah"],
        "Confident": ["phillip", "marissa", "joseph", "burt"],
        "Analytical": ["mark", "joseph", "andrea"],
        "Emotional": ["myra", "paula", "andrea"],
        "Reserved": ["paul", "myra", "mark"],
        "Talkative": ["ryan", "paula", "steve", "matilda"],
    },
    "communication_style": {
        "Direct and concise": ["mark", "joseph", "marissa"],
        "Detailed and elaborate": ["phillip", "andrea", "paul"],
        "Casual and friendly": ["steve", "drew", "sarah", "matilda"],
        "Formal and polite": ["phillip", "marissa", "joseph", "mark"],
        "Technical": ["mark", "joseph", "andrea"],
        "Simple and clear": ["sarah", "steve", "drew"],
        "Questioning": ["drew", "sarah", "ryan"],
        "Assertive": ["burt", "phillip", "marissa", "paula"],
        "Passive": ["myra", "andrea", "paul"],
        "Collaborative": ["steve", "andrea", "sarah"],
    },
    "accent": {
        "American": ["steve", "drew", "ryan", "marissa", "sarah", "paula"],
        "British": ["phillip", "burt", "paul", "andrea"],
        "Australian": ["drew", "sarah", "steve", "matilda"],
        "Indian": ["joseph", "andrea", "mark", "myra"],
        "Canadian": ["drew", "sarah", "andrea", "steve"],
        "Irish": ["drew", "matilda", "steve"],
        "Southern": ["cowboy - hugh man"],
        "Scottish": ["paul", "burt", "mrb"],
        "South African": ["phillip", "sarah", "joseph"],
        "Neutral": ["mark", "joseph", "andrea", "marissa"],
        "Regional": ["steve", "myra", "drew", "sarah"],
    },
}

# Default voice preferences by gender
# Available voices with their characteristics
AVAILABLE_VOICES = [
    {
        "id": "burt",
        "name": "Burt",
        "description": "Deep, resonant male voice with gravitas",
        "gender": "male",
    },
    {
        "id": "marissa",
        "name": "Marissa",
        "description": "Energetic, professional female voice",
        "gender": "female",
    },
    {
        "id": "andrea",
        "name": "Andrea",
        "description": "Warm, articulate female voice",
        "gender": "female",
    },
    {
        "id": "sarah",
        "name": "Sarah",
        "description": "Clear, friendly female voice",
        "gender": "female",
    },
    {
        "id": "phillip",
        "name": "Phillip",
        "description": "Authoritative, refined male voice",
        "gender": "male",
    },
    {
        "id": "steve",
        "name": "Steve",
        "description": "Casual, approachable male voice",
        "gender": "male",
    },
    {
        "id": "joseph",
        "name": "Joseph",
        "description": "Confident, professional male voice",
        "gender": "male",
    },
    {
        "id": "myra",
        "name": "Myra",
        "description": "Gentle, soothing female voice",
        "gender": "female",
    },
    {
        "id": "paula",
        "name": "Paula",
        "description": "Dynamic, engaging female voice",
        "gender": "female",
    },
    {
        "id": "ryan",
        "name": "Ryan",
        "description": "Young, energetic male voice",
        "gender": "male",
    },
    {
        "id": "drew",
        "name": "Drew",
        "description": "Friendly, conversational male voice",
        "gender": "male",
    },
    {
        "id": "paul",
        "name": "Paul",
        "description": "Mature, trustworthy male voice",
        "gender": "male",
    },
    {
        "id": "mrb",
        "name": "MrB",
        "description": "Distinctive, characterful male voice",
        "gender": "male",
    },
    {
        "id": "matilda",
        "name": "Matilda",
        "description": "Sweet, cheerful female voice",
        "gender": "female",
    },
    {
        "id": "mark",
        "name": "Mark",
        "description": "Clear, professional male voice",
        "gender": "male",
    },
    {
        "id": "MF4J4IDTRo0AxOO4dpFR",
        "name": "Indian Female",
        "description": "Professional Indian female voice",
        "gender": "female",
    },
    {
        "id": "Hmz0MdhDqv9vPpSMfDkh",
        "name": "Indian Male",
        "description": "Professional Indian male voice",
        "gender": "male",
    },
]

# Default voice preferences by gender
DEFAULT_VOICES = {"male": "phillip", "female": "marissa"}

# Indian voice preferences by gender
INDIAN_VOICES = {
    "male": "ac7ee4fa-25db-420d-bfff-f590d740aeb2",
    "female": "95d51f79-c397-46f9-b49a-23763d3eaa2d",
}


def get_language_key(
    language: str | None = None,
    accent: str | None = None,
    gender: str | None = None,
    CARTESIA_VOICES: dict | None = None,
) -> str:
    """
    Accent overrides language. If accent not given, use language. Fallback 'en'.
    Accepts codes ('hi') and names/demonyms ('hindi', 'british', 'mexican', etc.).
    """
    supported_langs = [
        "en",
        "es",
        "hi",
        "de",
        "fr",
        "it",
        "pl",
        "ru",
        "pt",
        "ja",
        "ko",
        "zh",
        "tr",
        "sv",
        "nl",
        "no",
        "te",
        "kn",
        "fi",
        "mr",
        "da",
        "bn",
        "sk",
        "uk",
        "el",
        "ta",
        "vi",
        "id",
        "ro",
        "ka",
        "ml",
        "ms",
        "he",
        "bg",
        "th",
        "hu",
        "pa",
        "cs",
        "tl",
        "ar",
        "gu",
        "hr",
    ]
    # ---- accent → language key (accent wins) ----
    accent_map = {
        "spanish": "es",
        "south american": "es",
        "indian": "hi",
        "german": "de",
        "french": "fr",
        "italian": "it",
        "polish": "pl",
        "russian": "ru",
        "portuguese": "pt",
        "brazilian": "pt",
        "japanese": "ja",
        "korean": "ko",
        "chinese": "zh",
        "mandarin": "zh",
        "turkish": "tr",
        "swedish": "sv",
        "dutch": "nl",
        "norwegian": "no",
        "finnish": "fi",
        "danish": "da",
        "slovak": "sk",
        "ukrainian": "uk",
        "greek": "el",
        "romanian": "ro",
        "georgian": "ka",
        "bulgarian": "bg",
        "thai": "th",
        "hungarian": "hu",
        "czech": "cs",
        "croatian": "hr",
        "vietnamese": "vi",
        "indonesian": "id",
        "malay": "ms",
        "malaysian": "ms",
        "tagalog": "tl",
        "filipino": "tl",
        "arabic": "ar",
        "hebrew": "he",
        "israeli": "he",
        "telugu": "te",
        "kannada": "kn",
        "marathi": "mr",
        "bengali": "bn",
        "tamil": "ta",
        "malayalam": "ml",
        "punjabi": "pa",
        "gujarati": "gu",
    }

    # ---- language → language key (used if accent not provided) ----
    language_map = {
        "es": "es",
        "hi": "hi",
        "de": "de",
        "fr": "fr",
        "it": "it",
        "pl": "pl",
        "ru": "ru",
        "pt": "pt",
        "ja": "ja",
        "ko": "ko",
        "zh": "zh",
        "tr": "tr",
        "sv": "sv",
        "nl": "nl",
        "no": "no",
        "te": "te",
        "kn": "kn",
        "fi": "fi",
        "mr": "mr",
        "da": "da",
        "bn": "bn",
        "sk": "sk",
        "uk": "uk",
        "el": "el",
        "ta": "ta",
        "vi": "vi",
        "id": "id",
        "ro": "ro",
        "ka": "ka",
        "ml": "ml",
        "ms": "ms",
        "he": "he",
        "bg": "bg",
        "th": "th",
        "hu": "hu",
        "pa": "pa",
        "cs": "cs",
        "tl": "tl",
        "ar": "ar",
        "gu": "gu",
        "hr": "hr",
        "spanish": "es",
        "hindi": "hi",
        "german": "de",
        "french": "fr",
        "italian": "it",
        "polish": "pl",
        "russian": "ru",
        "portuguese": "pt",
        "japanese": "ja",
        "korean": "ko",
        "chinese": "zh",
        "mandarin": "zh",
        "turkish": "tr",
        "swedish": "sv",
        "dutch": "nl",
        "norwegian": "no",
        "telugu": "te",
        "kannada": "kn",
        "finnish": "fi",
        "marathi": "mr",
        "danish": "da",
        "bengali": "bn",
        "slovak": "sk",
        "ukrainian": "uk",
        "greek": "el",
        "tamil": "ta",
        "vietnamese": "vi",
        "indonesian": "id",
        "romanian": "ro",
        "georgian": "ka",
        "malayalam": "ml",
        "malay": "ms",
        "hebrew": "he",
        "bulgarian": "bg",
        "thai": "th",
        "hungarian": "hu",
        "punjabi": "pa",
        "czech": "cs",
        "tagalog": "tl",
        "filipino": "tl",
        "arabic": "ar",
        "gujarati": "gu",
        "croatian": "hr",
    }

    def norm(x: str | None) -> str | None:
        if not x:
            return None
        return x.strip().lower().replace("-", " ")

    voice_id = None
    a = norm(accent)
    l = norm(language)
    if a and a in accent_map and accent_map[a] in supported_langs:
        accent = accent_map.get(a, "")
        voice_list = CARTESIA_VOICES.get(accent, {}).get(gender, [])
        voice_id = random.choice(voice_list) if voice_list else None

    elif l and l in language_map and language_map[l] in supported_langs:
        language = language_map.get(l, "")
        voice_list = CARTESIA_VOICES.get(language, {}).get(gender, [])
        voice_id = random.choice(voice_list) if voice_list else None
    # print("voice id here", voice_id)
    return voice_id


def select_voice_id(persona_data, provider=ProviderChoices.LIVEKIT):
    """
    Select appropriate voice_id based on persona attributes using a scoring system.

    Uses these persona fields (all optional except gender):
    - gender (required): male, female, non-binary
    - location: India (uses Indian voices)
    - language: Hindi (uses Indian voices)
    - age_group: 18-25, 25-32, 32-40, 40-50, 50-60, 60+ (+3 points if matched)
    - personality: Friendly, Professional, Confident, etc. (+2 points if matched)
    - communication_style: Direct, Casual, Formal, etc. (+2 points if matched)
    - accent: American, British, Indian, etc. (+2 points if matched)

    Args:
        persona_data (dict or str): Persona data dict or JSON string
        provider (ProviderChoices): Voice infrastructure provider —
            LIVEKIT returns Cartesia UUIDs,
            VAPI returns 11Labs-compatible voice names.

    Returns:
        str: Selected voice_id (e.g., 'phillip', 'marissa', 'steve', etc.)
    """

    try:
        if not persona_data or not isinstance(persona_data, dict):
            return DEFAULT_VOICES.get("male", "phillip")

        # Get gender first as primary filter
        gender = persona_data.get("gender", "").lower()
        if gender not in ["male", "female"]:
            gender = "male"  # Default to male if gender is unclear

        # Check if location is India or language is Hindi - use Indian voices only
        location = persona_data.get("location", "").lower()
        language = persona_data.get("language", "").lower()
        accent = persona_data.get("accent", "").lower()

        # Cartesia UUIDs are only valid for LiveKit infrastructure.
        # VAPI uses 11Labs-style voice names (e.g. "marissa", "phillip").
        if provider != ProviderChoices.VAPI:
            with open(
                "/app/backend/simulate/data/voices_by_language_and_gender.json",
                "r",
                encoding="utf-8",
            ) as f:
                CARTESIA_VOICES = json.load(f)

            try:
                cartestia_language_key = get_language_key(
                    language, accent, gender, CARTESIA_VOICES
                )
            except Exception as e:
                traceback.print_exc()

            if cartestia_language_key:
                return cartestia_language_key

        # Start with voices matching the gender
        available_voices = VOICE_MAPPING["gender"].get(
            gender, VOICE_MAPPING["gender"]["male"]
        )

        # Filter by age group if specified
        age_group = persona_data.get("age_group", "").lower()
        if age_group in VOICE_MAPPING["age_group"]:
            age_voices = VOICE_MAPPING["age_group"][age_group]
            available_voices = [v for v in available_voices if v in age_voices]

        # Filter by personality if specified
        personality = persona_data.get("personality", "").lower()
        if personality in VOICE_MAPPING["personality"]:
            personality_voices = VOICE_MAPPING["personality"][personality]
            available_voices = [v for v in available_voices if v in personality_voices]

        # Filter by communication style if specified
        communication_style = persona_data.get("communication_style", "").lower()
        if communication_style in VOICE_MAPPING["communication_style"]:
            style_voices = VOICE_MAPPING["communication_style"][communication_style]
            available_voices = [v for v in available_voices if v in style_voices]

        # If no voices match all criteria, fall back to gender-based selection
        if not available_voices:
            available_voices = VOICE_MAPPING["gender"].get(
                gender, VOICE_MAPPING["gender"]["male"]
            )

        # Return a random matching voice (or default)
        return (
            random.choice(available_voices)
            if available_voices
            else DEFAULT_VOICES.get(gender, "phillip")
        )
    except Exception:
        # print("I am inside exception of select_voice_id")
        return DEFAULT_VOICES.get(gender, "phillip")


def select_voice_with_llm(persona_data):
    """
    Use LLM to select the most appropriate voice based on persona.
    Works with new persona field structure.

    Args:
        persona_data (dict or str): Persona data dict or JSON string

    Returns:
        str: Selected voice_id
    """
    if persona_data.get("gender", "").lower() == "male":
        return "phillip"
    else:
        return "marissa"
    if not persona_data or not isinstance(persona_data, dict):
        return DEFAULT_VOICES.get("male", "phillip")

    try:
        # Prepare the prompt for LLM
        persona_summary = f"""
        Persona Details:
        - Gender: {persona_data.get("gender", "unknown")}
        - Age Group: {persona_data.get("age_group", "unknown")}
        - Personality: {persona_data.get("personality", "unknown")}
        - Communication Style: {persona_data.get("communication_style", "unknown")}
        - Profession: {persona_data.get("profession", "unknown")}
        - Location: {persona_data.get("location", "unknown")}
        """

        voices_info = "\n".join(
            [
                f"- {voice['id']}: {voice['description']} ({voice['gender']})"
                for voice in AVAILABLE_VOICES
            ]
        )

        prompt = f"""
        Based on the following persona details, select the most appropriate voice from the available options.

        {persona_summary}

        Available Voices:
        {voices_info}

        Please select the voice_id that best matches this persona. Consider:
        1. Gender preference
        2. Age appropriateness
        3. Personality match
        4. Communication style alignment
        5. Professional context

        Respond with only the voice_id (e.g., "phillip" or "marissa").
        """
        llm = LLM(
            model_name="gpt-4o-mini",
            temperature=0.1,  # Lower temperature for more consistent, structured output
            provider="openai",
            api_key=None,
        )
        messages = [
            {
                "role": "system",
                "content": "You are a voice selection expert. Choose the most appropriate voice based on persona characteristics.",
            },
            {"role": "user", "content": prompt},
        ]
        response = llm.call_llm(messages, "openai")
        selected_voice = response.strip().strip('"').strip("'")

        # Validate the selected voice exists
        voice_ids = [voice["id"] for voice in AVAILABLE_VOICES]
        if selected_voice in voice_ids:
            return selected_voice
        else:
            # Fallback to rule-based selection if LLM returns invalid voice
            fallback_voice = select_voice_id(persona_data)
            # Double-check fallback is valid
            if fallback_voice in voice_ids:
                return fallback_voice
            else:
                # Ultimate fallback to gender-based default
                gender = persona_data.get("gender", "male").lower()
                return DEFAULT_VOICES.get(gender, "phillip")

    except Exception as e:
        # Fallback to rule-based selection if LLM call fails
        print(f"LLM voice selection failed: {e}")
        fallback_voice = select_voice_id(persona_data)
        # Double-check fallback is valid
        voice_ids = [voice["id"] for voice in AVAILABLE_VOICES]
        if fallback_voice in voice_ids:
            return fallback_voice
        else:
            # Ultimate fallback to gender-based default
            gender = (
                persona_data.get("gender", "male").lower() if persona_data else "male"
            )
            return DEFAULT_VOICES.get(gender, "phillip")


def validate_and_return_voice(voice_id, persona_data=None):
    """
    Validate that voice_id exists in available voices, return safe fallback if not.

    Args:
        voice_id (str): Voice ID to validate
        persona_data (dict): Optional persona data for fallback selection

    Returns:
        str: Valid voice_id
    """
    voice_ids = [voice["id"] for voice in AVAILABLE_VOICES]

    if voice_id in voice_ids:
        return voice_id

    # If invalid voice_id, use fallback
    if persona_data:
        fallback_voice = select_voice_id(persona_data)
        if fallback_voice in voice_ids:
            return fallback_voice

    # Ultimate fallback
    gender = persona_data.get("gender", "male").lower() if persona_data else "male"
    return DEFAULT_VOICES.get(gender, "phillip")


def get_voice_by_gender_only(gender):
    """
    Simple function to get a voice based only on gender.

    Args:
        gender (str): 'male' or 'female'

    Returns:
        str: voice_id
    """
    return DEFAULT_VOICES.get(gender.lower(), DEFAULT_VOICES["male"])


ENGLISH_PERSONAS = [
    {
        "gender": "Female",
        "name": "Emily Parker",
        "age_group": "18-25",
        "location": "United States",
        "profession": "Student",
        "personality": "Friendly and cooperative",
        "communication_style": "Casual and friendly",
        "accent": "American",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "1.0",
        "background_sound": "false",
        "finished_speaking_sensitivity": "7",
        "interrupt_sensitivity": "3",
    },
    {
        "gender": "Male",
        "name": "James Wilson",
        "age_group": "25-32",
        "location": "United Kingdom",
        "profession": "Engineer",
        "personality": "Analytical",
        "communication_style": "Technical",
        "accent": "Neutral",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "0.75",
        "background_sound": "false",
        "finished_speaking_sensitivity": "8",
        "interrupt_sensitivity": "2",
    },
    {
        "gender": "Female",
        "name": "Olivia Johnson",
        "age_group": "32-40",
        "location": "Australia",
        "profession": "Manager",
        "personality": "Confident",
        "communication_style": "Direct and concise",
        "accent": "Australian",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "1.25",
        "background_sound": "false",
        "finished_speaking_sensitivity": "5",
        "interrupt_sensitivity": "7",
    },
    {
        "gender": "Male",
        "name": "William Taylor",
        "age_group": "40-50",
        "location": "Canada",
        "profession": "Business Owner",
        "personality": "Professional and formal",
        "communication_style": "Assertive",
        "accent": "Canadian",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "1.0",
        "background_sound": "true",
        "finished_speaking_sensitivity": "6",
        "interrupt_sensitivity": "8",
    },
    {
        "gender": "Female",
        "name": "Sophia Miller",
        "age_group": "50-60",
        "location": "United States",
        "profession": "Doctor",
        "personality": "Detail-oriented",
        "communication_style": "Formal and polite",
        "accent": "American",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "0.75",
        "background_sound": "false",
        "finished_speaking_sensitivity": "9",
        "interrupt_sensitivity": "2",
    },
    {
        "gender": "Male",
        "name": "Benjamin Harris",
        "age_group": "60+",
        "location": "United Kingdom",
        "profession": "Retired",
        "personality": "Easy-going",
        "communication_style": "Detailed and elaborate",
        "accent": "Neutral",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "0.5",
        "background_sound": "false",
        "finished_speaking_sensitivity": "10",
        "interrupt_sensitivity": "1",
    },
    {
        "gender": "Female",
        "name": "Ava Thomas",
        "age_group": "18-25",
        "location": "Australia",
        "profession": "Sales Representative",
        "personality": "Talkative",
        "communication_style": "Casual and friendly",
        "accent": "Australian",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "1.5",
        "background_sound": "true",
        "finished_speaking_sensitivity": "3",
        "interrupt_sensitivity": "9",
    },
    {
        "gender": "Male",
        "name": "Daniel Martinez",
        "age_group": "25-32",
        "location": "United States",
        "profession": "Technician",
        "personality": "Cautious and skeptical",
        "communication_style": "Simple and clear",
        "accent": "American",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "1.0",
        "background_sound": "true",
        "finished_speaking_sensitivity": "5",
        "interrupt_sensitivity": "5",
    },
    {
        "gender": "Female",
        "name": "Charlotte Brown",
        "age_group": "32-40",
        "location": "Canada",
        "profession": "Teacher",
        "personality": "Friendly and cooperative",
        "communication_style": "Collaborative",
        "accent": "Canadian",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "1.0",
        "background_sound": "false",
        "finished_speaking_sensitivity": "7",
        "interrupt_sensitivity": "4",
    },
    {
        "gender": "Male",
        "name": "Matthew Lewis",
        "age_group": "40-50",
        "location": "United Kingdom",
        "profession": "Consultant",
        "personality": "Impatient and direct",
        "communication_style": "Direct and concise",
        "accent": "Neutral",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "1.25",
        "background_sound": "false",
        "finished_speaking_sensitivity": "4",
        "interrupt_sensitivity": "8",
    },
    {
        "gender": "Female",
        "name": "Abigail Davis",
        "age_group": "50-60",
        "location": "Australia",
        "profession": "Nurse",
        "personality": "Emotional",
        "communication_style": "Detailed and elaborate",
        "accent": "Australian",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "0.75",
        "background_sound": "false",
        "finished_speaking_sensitivity": "8",
        "interrupt_sensitivity": "3",
    },
    {
        "gender": "Male",
        "name": "Henry Wilson",
        "age_group": "60+",
        "location": "Canada",
        "profession": "Retired",
        "personality": "Reserved",
        "communication_style": "Formal and polite",
        "accent": "Canadian",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "0.5",
        "background_sound": "false",
        "finished_speaking_sensitivity": "9",
        "interrupt_sensitivity": "1",
    },
    {
        "gender": "Female",
        "name": "Zoe Anderson",
        "age_group": "18-25",
        "location": "United States",
        "profession": "Marketing Professional",
        "personality": "Confident",
        "communication_style": "Assertive",
        "accent": "American",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "1.25",
        "background_sound": "true",
        "finished_speaking_sensitivity": "4",
        "interrupt_sensitivity": "7",
    },
    {
        "gender": "Male",
        "name": "Alexander Thompson",
        "age_group": "25-32",
        "location": "United Kingdom",
        "profession": "Accountant",
        "personality": "Detail-oriented",
        "communication_style": "Technical",
        "accent": "Neutral",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "1.0",
        "background_sound": "false",
        "finished_speaking_sensitivity": "6",
        "interrupt_sensitivity": "5",
    },
    {
        "gender": "Female",
        "name": "Lily Jackson",
        "age_group": "32-40",
        "location": "Australia",
        "profession": "Freelancer",
        "personality": "Easy-going",
        "communication_style": "Casual and friendly",
        "accent": "Australian",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "1.0",
        "background_sound": "true",
        "finished_speaking_sensitivity": "5",
        "interrupt_sensitivity": "6",
    },
    {
        "gender": "Male",
        "name": "Christopher White",
        "age_group": "40-50",
        "location": "United States",
        "profession": "Manager",
        "personality": "Professional and formal",
        "communication_style": "Direct and concise",
        "accent": "American",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "1.25",
        "background_sound": "false",
        "finished_speaking_sensitivity": "7",
        "interrupt_sensitivity": "4",
    },
    {
        "gender": "Female",
        "name": "Grace Moore",
        "age_group": "50-60",
        "location": "Canada",
        "profession": "Customer Service",
        "personality": "Friendly and cooperative",
        "communication_style": "Simple and clear",
        "accent": "Canadian",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "0.75",
        "background_sound": "false",
        "finished_speaking_sensitivity": "8",
        "interrupt_sensitivity": "3",
    },
    {
        "gender": "Male",
        "name": "Joseph Clark",
        "age_group": "60+",
        "location": "Australia",
        "profession": "Retired",
        "personality": "Analytical",
        "communication_style": "Questioning",
        "accent": "Australian",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "0.75",
        "background_sound": "false",
        "finished_speaking_sensitivity": "10",
        "interrupt_sensitivity": "2",
    },
    {
        "gender": "Female",
        "name": "Emma Robinson",
        "age_group": "25-32",
        "location": "United Kingdom",
        "profession": "Doctor",
        "personality": "Confident",
        "communication_style": "Formal and polite",
        "accent": "Neutral",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "1.0",
        "background_sound": "false",
        "finished_speaking_sensitivity": "6",
        "interrupt_sensitivity": "5",
    },
    {
        "gender": "Male",
        "name": "Ryan Garcia",
        "age_group": "32-40",
        "location": "United States",
        "profession": "Engineer",
        "personality": "Cautious and skeptical",
        "communication_style": "Technical",
        "accent": "American",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "1.0",
        "background_sound": "true",
        "finished_speaking_sensitivity": "7",
        "interrupt_sensitivity": "4",
    },
    {
        "gender": "Male",
        "name": "Nathan Cooper",
        "age_group": "18-25",
        "location": "United States",
        "profession": "Student",
        "personality": "Analytical",
        "communication_style": "Questioning",
        "accent": "American",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "1.25",
        "background_sound": "false",
        "finished_speaking_sensitivity": "5",
        "interrupt_sensitivity": "6",
    },
    {
        "gender": "Female",
        "name": "Isabella Morgan",
        "age_group": "25-32",
        "location": "Australia",
        "profession": "Marketing Professional",
        "personality": "Confident",
        "communication_style": "Assertive",
        "accent": "Australian",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "1.25",
        "background_sound": "true",
        "finished_speaking_sensitivity": "4",
        "interrupt_sensitivity": "8",
    },
    {
        "gender": "Male",
        "name": "Ethan Phillips",
        "age_group": "32-40",
        "location": "Canada",
        "profession": "Doctor",
        "personality": "Reserved",
        "communication_style": "Formal and polite",
        "accent": "Canadian",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "0.75",
        "background_sound": "false",
        "finished_speaking_sensitivity": "8",
        "interrupt_sensitivity": "2",
    },
    {
        "gender": "Female",
        "name": "Victoria Bennett",
        "age_group": "40-50",
        "location": "United Kingdom",
        "profession": "Teacher",
        "personality": "Friendly and cooperative",
        "communication_style": "Detailed and elaborate",
        "accent": "Neutral",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "1.0",
        "background_sound": "false",
        "finished_speaking_sensitivity": "7",
        "interrupt_sensitivity": "3",
    },
    {
        "gender": "Male",
        "name": "Jack Richardson",
        "age_group": "50-60",
        "location": "United States",
        "profession": "Business Owner",
        "personality": "Impatient and direct",
        "communication_style": "Direct and concise",
        "accent": "American",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "1.5",
        "background_sound": "true",
        "finished_speaking_sensitivity": "3",
        "interrupt_sensitivity": "9",
    },
    {
        "gender": "Female",
        "name": "Audrey Sullivan",
        "age_group": "60+",
        "location": "Australia",
        "profession": "Retired",
        "personality": "Detail-oriented",
        "communication_style": "Simple and clear",
        "accent": "Australian",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "0.5",
        "background_sound": "false",
        "finished_speaking_sensitivity": "10",
        "interrupt_sensitivity": "1",
    },
    {
        "gender": "Male",
        "name": "Lucas Edwards",
        "age_group": "18-25",
        "location": "Canada",
        "profession": "Technician",
        "personality": "Easy-going",
        "communication_style": "Casual and friendly",
        "accent": "Canadian",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "1.0",
        "background_sound": "true",
        "finished_speaking_sensitivity": "5",
        "interrupt_sensitivity": "5",
    },
    {
        "gender": "Female",
        "name": "Mia Dawson",
        "age_group": "25-32",
        "location": "United Kingdom",
        "profession": "Consultant",
        "personality": "Talkative",
        "communication_style": "Collaborative",
        "accent": "Neutral",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "1.25",
        "background_sound": "false",
        "finished_speaking_sensitivity": "6",
        "interrupt_sensitivity": "7",
    },
    {
        "gender": "Male",
        "name": "Owen Kennedy",
        "age_group": "32-40",
        "location": "United States",
        "profession": "Freelancer",
        "personality": "Anxious",
        "communication_style": "Detailed and elaborate",
        "accent": "American",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "1.0",
        "background_sound": "false",
        "finished_speaking_sensitivity": "8",
        "interrupt_sensitivity": "4",
    },
    {
        "gender": "Female",
        "name": "Chloe Harrison",
        "age_group": "40-50",
        "location": "Australia",
        "profession": "Accountant",
        "personality": "Professional and formal",
        "communication_style": "Technical",
        "accent": "Australian",
        "language": "English",
        "simulation_type": "voice",
        "conversation_speed": "0.75",
        "background_sound": "false",
        "finished_speaking_sensitivity": "7",
        "interrupt_sensitivity": "3",
    },
]


HINDI_PERSONAS = [
    {
        "gender": "Female",
        "name": "Arti Sharma",
        "age_group": "18-25",
        "location": "India",
        "profession": "Student",
        "personality": "Anxious",
        "communication_style": "Questioning",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "1.0",
        "background_sound": "false",
        "finished_speaking_sensitivity": "8",
        "interrupt_sensitivity": "2",
    },
    {
        "gender": "Male",
        "name": "Karan Gupta",
        "age_group": "25-32",
        "location": "India",
        "profession": "Consultant",
        "personality": "Confident",
        "communication_style": "Direct and concise",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "1.25",
        "background_sound": "true",
        "finished_speaking_sensitivity": "4",
        "interrupt_sensitivity": "7",
    },
    {
        "gender": "Female",
        "name": "Jyoti Malhotra",
        "age_group": "32-40",
        "location": "India",
        "profession": "Teacher",
        "personality": "Detail-oriented",
        "communication_style": "Detailed and elaborate",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "0.75",
        "background_sound": "false",
        "finished_speaking_sensitivity": "9",
        "interrupt_sensitivity": "2",
    },
    {
        "gender": "Male",
        "name": "Ajay Tiwari",
        "age_group": "40-50",
        "location": "India",
        "profession": "Doctor",
        "personality": "Professional and formal",
        "communication_style": "Formal and polite",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "1.0",
        "background_sound": "false",
        "finished_speaking_sensitivity": "7",
        "interrupt_sensitivity": "4",
    },
    {
        "gender": "Female",
        "name": "Rekha Mehra",
        "age_group": "50-60",
        "location": "India",
        "profession": "Homemaker",
        "personality": "Friendly and cooperative",
        "communication_style": "Casual and friendly",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "0.75",
        "background_sound": "false",
        "finished_speaking_sensitivity": "8",
        "interrupt_sensitivity": "3",
    },
    {
        "gender": "Male",
        "name": "Sanjay Patel",
        "age_group": "60+",
        "location": "India",
        "profession": "Retired",
        "personality": "Cautious and skeptical",
        "communication_style": "Questioning",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "0.5",
        "background_sound": "false",
        "finished_speaking_sensitivity": "10",
        "interrupt_sensitivity": "1",
    },
    {
        "gender": "Female",
        "name": "Anjali Arora",
        "age_group": "18-25",
        "location": "India",
        "profession": "Student",
        "personality": "Talkative",
        "communication_style": "Collaborative",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "1.5",
        "background_sound": "true",
        "finished_speaking_sensitivity": "3",
        "interrupt_sensitivity": "9",
    },
    {
        "gender": "Male",
        "name": "Rahul Bhatia",
        "age_group": "25-32",
        "location": "India",
        "profession": "Engineer",
        "personality": "Impatient and direct",
        "communication_style": "Technical",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "1.25",
        "background_sound": "true",
        "finished_speaking_sensitivity": "5",
        "interrupt_sensitivity": "6",
    },
    {
        "gender": "Female",
        "name": "Sheetal Chopra",
        "age_group": "32-40",
        "location": "India",
        "profession": "Sales Representative",
        "personality": "Emotional",
        "communication_style": "Passive",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "1.0",
        "background_sound": "false",
        "finished_speaking_sensitivity": "7",
        "interrupt_sensitivity": "4",
    },
    {
        "gender": "Male",
        "name": "Vivek Yadav",
        "age_group": "40-50",
        "location": "India",
        "profession": "Customer Service",
        "personality": "Easy-going",
        "communication_style": "Simple and clear",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "0.75",
        "background_sound": "true",
        "finished_speaking_sensitivity": "6",
        "interrupt_sensitivity": "5",
    },
    {
        "gender": "Male",
        "name": "Arjun Sharma",
        "age_group": "25-32",
        "location": "India",
        "profession": "Engineer",
        "personality": "Analytical",
        "communication_style": "Technical",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "1.0",
        "background_sound": "false",
        "finished_speaking_sensitivity": "6",
        "interrupt_sensitivity": "5",
    },
    {
        "gender": "Female",
        "name": "Priya Patel",
        "age_group": "18-25",
        "location": "India",
        "profession": "Student",
        "personality": "Friendly and cooperative",
        "communication_style": "Casual and friendly",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "1.25",
        "background_sound": "false",
        "finished_speaking_sensitivity": "5",
        "interrupt_sensitivity": "4",
    },
    {
        "gender": "Male",
        "name": "Vikram Singh",
        "age_group": "32-40",
        "location": "India",
        "profession": "Business Owner",
        "personality": "Confident",
        "communication_style": "Assertive",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "1.25",
        "background_sound": "true",
        "finished_speaking_sensitivity": "4",
        "interrupt_sensitivity": "7",
    },
    {
        "gender": "Female",
        "name": "Ananya Gupta",
        "age_group": "25-32",
        "location": "India",
        "profession": "Doctor",
        "personality": "Professional and formal",
        "communication_style": "Formal and polite",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "1.0",
        "background_sound": "false",
        "finished_speaking_sensitivity": "7",
        "interrupt_sensitivity": "3",
    },
    {
        "gender": "Male",
        "name": "Rohit Verma",
        "age_group": "40-50",
        "location": "India",
        "profession": "Manager",
        "personality": "Detail-oriented",
        "communication_style": "Direct and concise",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "1.0",
        "background_sound": "true",
        "finished_speaking_sensitivity": "6",
        "interrupt_sensitivity": "6",
    },
    {
        "gender": "Female",
        "name": "Neha Sharma",
        "age_group": "32-40",
        "location": "India",
        "profession": "Teacher",
        "personality": "Friendly and cooperative",
        "communication_style": "Detailed and elaborate",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "0.75",
        "background_sound": "false",
        "finished_speaking_sensitivity": "8",
        "interrupt_sensitivity": "2",
    },
    {
        "gender": "Male",
        "name": "Amit Kumar",
        "age_group": "50-60",
        "location": "India",
        "profession": "Consultant",
        "personality": "Analytical",
        "communication_style": "Technical",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "0.75",
        "background_sound": "false",
        "finished_speaking_sensitivity": "9",
        "interrupt_sensitivity": "3",
    },
    {
        "gender": "Female",
        "name": "Divya Mishra",
        "age_group": "18-25",
        "location": "India",
        "profession": "Student",
        "personality": "Talkative",
        "communication_style": "Casual and friendly",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "1.5",
        "background_sound": "true",
        "finished_speaking_sensitivity": "3",
        "interrupt_sensitivity": "8",
    },
    {
        "gender": "Male",
        "name": "Rajesh Khanna",
        "age_group": "60+",
        "location": "India",
        "profession": "Retired",
        "personality": "Easy-going",
        "communication_style": "Simple and clear",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "0.5",
        "background_sound": "false",
        "finished_speaking_sensitivity": "10",
        "interrupt_sensitivity": "1",
    },
    {
        "gender": "Female",
        "name": "Meera Iyer",
        "age_group": "40-50",
        "location": "India",
        "profession": "Accountant",
        "personality": "Detail-oriented",
        "communication_style": "Formal and polite",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "0.75",
        "background_sound": "false",
        "finished_speaking_sensitivity": "8",
        "interrupt_sensitivity": "2",
    },
    {
        "gender": "Male",
        "name": "Sunil Mehta",
        "age_group": "25-32",
        "location": "India",
        "profession": "Sales Representative",
        "personality": "Confident",
        "communication_style": "Assertive",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "1.25",
        "background_sound": "true",
        "finished_speaking_sensitivity": "4",
        "interrupt_sensitivity": "7",
    },
    {
        "gender": "Female",
        "name": "Kavita Reddy",
        "age_group": "32-40",
        "location": "India",
        "profession": "Marketing Professional",
        "personality": "Friendly and cooperative",
        "communication_style": "Collaborative",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "1.0",
        "background_sound": "true",
        "finished_speaking_sensitivity": "5",
        "interrupt_sensitivity": "5",
    },
    {
        "gender": "Male",
        "name": "Prakash Joshi",
        "age_group": "50-60",
        "location": "India",
        "profession": "Manager",
        "personality": "Professional and formal",
        "communication_style": "Direct and concise",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "1.0",
        "background_sound": "false",
        "finished_speaking_sensitivity": "7",
        "interrupt_sensitivity": "4",
    },
    {
        "gender": "Female",
        "name": "Sunita Agarwal",
        "age_group": "40-50",
        "location": "India",
        "profession": "Nurse",
        "personality": "Emotional",
        "communication_style": "Detailed and elaborate",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "0.75",
        "background_sound": "false",
        "finished_speaking_sensitivity": "8",
        "interrupt_sensitivity": "3",
    },
    {
        "gender": "Male",
        "name": "Vijay Malhotra",
        "age_group": "32-40",
        "location": "India",
        "profession": "Engineer",
        "personality": "Cautious and skeptical",
        "communication_style": "Technical",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "1.0",
        "background_sound": "false",
        "finished_speaking_sensitivity": "6",
        "interrupt_sensitivity": "5",
    },
    {
        "gender": "Female",
        "name": "Pooja Desai",
        "age_group": "25-32",
        "location": "India",
        "profession": "Customer Service",
        "personality": "Friendly and cooperative",
        "communication_style": "Simple and clear",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "1.0",
        "background_sound": "true",
        "finished_speaking_sensitivity": "5",
        "interrupt_sensitivity": "4",
    },
    {
        "gender": "Male",
        "name": "Deepak Choudhary",
        "age_group": "18-25",
        "location": "India",
        "profession": "Student",
        "personality": "Reserved",
        "communication_style": "Questioning",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "0.75",
        "background_sound": "false",
        "finished_speaking_sensitivity": "9",
        "interrupt_sensitivity": "2",
    },
    {
        "gender": "Female",
        "name": "Rani Kapoor",
        "age_group": "60+",
        "location": "India",
        "profession": "Retired",
        "personality": "Easy-going",
        "communication_style": "Casual and friendly",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "0.5",
        "background_sound": "false",
        "finished_speaking_sensitivity": "10",
        "interrupt_sensitivity": "1",
    },
    {
        "gender": "Male",
        "name": "Nitin Bajaj",
        "age_group": "40-50",
        "location": "India",
        "profession": "Business Owner",
        "personality": "Impatient and direct",
        "communication_style": "Direct and concise",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "1.5",
        "background_sound": "true",
        "finished_speaking_sensitivity": "3",
        "interrupt_sensitivity": "8",
    },
    {
        "gender": "Female",
        "name": "Ritu Saxena",
        "age_group": "32-40",
        "location": "India",
        "profession": "Freelancer",
        "personality": "Creative",
        "communication_style": "Detailed and elaborate",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "voice",
        "conversation_speed": "1.0",
        "background_sound": "false",
        "finished_speaking_sensitivity": "7",
        "interrupt_sensitivity": "4",
    },
]


ENGLISH_PERSONAS_TEXT = [
    {
        "gender": "Female",
        "name": "Emily Parker",
        "age_group": "18-25",
        "location": "United States",
        "profession": "Student",
        "personality": "Friendly and cooperative",
        "communication_style": "Casual and friendly",
        "accent": "American",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "expressive",
        "slang_usage": "moderate",
        "typos_frequency": "occasional",
        "regional_mix": "low",
        "emoji_usage": "regular",
        "tone": "casual",
        "verbosity": "balanced",
    },
    {
        "gender": "Male",
        "name": "James Wilson",
        "age_group": "25-32",
        "location": "United Kingdom",
        "profession": "Engineer",
        "personality": "Analytical",
        "communication_style": "Technical",
        "accent": "Neutral",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "clean",
        "slang_usage": "low",
        "typos_frequency": "rare",
        "regional_mix": "none",
        "emoji_usage": "never",
        "tone": "formal",
        "verbosity": "detailed",
    },
    {
        "gender": "Female",
        "name": "Olivia Johnson",
        "age_group": "32-40",
        "location": "Australia",
        "profession": "Manager",
        "personality": "Confident",
        "communication_style": "Direct and concise",
        "accent": "Australian",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "minimal",
        "slang_usage": "moderate",
        "typos_frequency": "none",
        "regional_mix": "moderate",
        "emoji_usage": "light",
        "tone": "neutral",
        "verbosity": "brief",
    },
    {
        "gender": "Male",
        "name": "William Taylor",
        "age_group": "40-50",
        "location": "Canada",
        "profession": "Business Owner",
        "personality": "Professional and formal",
        "communication_style": "Assertive",
        "accent": "Canadian",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "clean",
        "slang_usage": "none",
        "typos_frequency": "none",
        "regional_mix": "none",
        "emoji_usage": "never",
        "tone": "formal",
        "verbosity": "balanced",
    },
    {
        "gender": "Female",
        "name": "Sophia Miller",
        "age_group": "50-60",
        "location": "United States",
        "profession": "Doctor",
        "personality": "Detail-oriented",
        "communication_style": "Formal and polite",
        "accent": "American",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "clean",
        "slang_usage": "none",
        "typos_frequency": "none",
        "regional_mix": "none",
        "emoji_usage": "never",
        "tone": "formal",
        "verbosity": "detailed",
    },
    {
        "gender": "Male",
        "name": "Benjamin Harris",
        "age_group": "60+",
        "location": "United Kingdom",
        "profession": "Retired",
        "personality": "Easy-going",
        "communication_style": "Detailed and elaborate",
        "accent": "Neutral",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "expressive",
        "slang_usage": "low",
        "typos_frequency": "occasional",
        "regional_mix": "low",
        "emoji_usage": "light",
        "tone": "casual",
        "verbosity": "detailed",
    },
    {
        "gender": "Female",
        "name": "Ava Thomas",
        "age_group": "18-25",
        "location": "Australia",
        "profession": "Sales Representative",
        "personality": "Talkative",
        "communication_style": "Casual and friendly",
        "accent": "Australian",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "expressive",
        "slang_usage": "heavy",
        "typos_frequency": "frequent",
        "regional_mix": "moderate",
        "emoji_usage": "heavy",
        "tone": "casual",
        "verbosity": "balanced",
    },
    {
        "gender": "Male",
        "name": "Daniel Martinez",
        "age_group": "25-32",
        "location": "United States",
        "profession": "Technician",
        "personality": "Cautious and skeptical",
        "communication_style": "Simple and clear",
        "accent": "American",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "minimal",
        "slang_usage": "low",
        "typos_frequency": "rare",
        "regional_mix": "low",
        "emoji_usage": "never",
        "tone": "neutral",
        "verbosity": "brief",
    },
    {
        "gender": "Female",
        "name": "Charlotte Brown",
        "age_group": "32-40",
        "location": "Canada",
        "profession": "Teacher",
        "personality": "Friendly and cooperative",
        "communication_style": "Collaborative",
        "accent": "Canadian",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "clean",
        "slang_usage": "moderate",
        "typos_frequency": "rare",
        "regional_mix": "moderate",
        "emoji_usage": "light",
        "tone": "casual",
        "verbosity": "balanced",
    },
    {
        "gender": "Male",
        "name": "Matthew Lewis",
        "age_group": "40-50",
        "location": "United Kingdom",
        "profession": "Consultant",
        "personality": "Impatient and direct",
        "communication_style": "Direct and concise",
        "accent": "Neutral",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "minimal",
        "slang_usage": "low",
        "typos_frequency": "none",
        "regional_mix": "none",
        "emoji_usage": "never",
        "tone": "neutral",
        "verbosity": "brief",
    },
    {
        "gender": "Female",
        "name": "Abigail Davis",
        "age_group": "50-60",
        "location": "Australia",
        "profession": "Nurse",
        "personality": "Emotional",
        "communication_style": "Detailed and elaborate",
        "accent": "Australian",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "expressive",
        "slang_usage": "moderate",
        "typos_frequency": "occasional",
        "regional_mix": "moderate",
        "emoji_usage": "regular",
        "tone": "casual",
        "verbosity": "detailed",
    },
    {
        "gender": "Male",
        "name": "Henry Wilson",
        "age_group": "60+",
        "location": "Canada",
        "profession": "Retired",
        "personality": "Reserved",
        "communication_style": "Formal and polite",
        "accent": "Canadian",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "clean",
        "slang_usage": "none",
        "typos_frequency": "occasional",
        "regional_mix": "low",
        "emoji_usage": "never",
        "tone": "formal",
        "verbosity": "balanced",
    },
    {
        "gender": "Female",
        "name": "Zoe Anderson",
        "age_group": "18-25",
        "location": "United States",
        "profession": "Marketing Professional",
        "personality": "Confident",
        "communication_style": "Assertive",
        "accent": "American",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "expressive",
        "slang_usage": "moderate",
        "typos_frequency": "rare",
        "regional_mix": "low",
        "emoji_usage": "regular",
        "tone": "casual",
        "verbosity": "balanced",
    },
    {
        "gender": "Male",
        "name": "Alexander Thompson",
        "age_group": "25-32",
        "location": "United Kingdom",
        "profession": "Accountant",
        "personality": "Detail-oriented",
        "communication_style": "Technical",
        "accent": "Neutral",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "clean",
        "slang_usage": "none",
        "typos_frequency": "none",
        "regional_mix": "none",
        "emoji_usage": "never",
        "tone": "formal",
        "verbosity": "detailed",
    },
    {
        "gender": "Female",
        "name": "Lily Jackson",
        "age_group": "32-40",
        "location": "Australia",
        "profession": "Freelancer",
        "personality": "Easy-going",
        "communication_style": "Casual and friendly",
        "accent": "Australian",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "erratic",
        "slang_usage": "heavy",
        "typos_frequency": "frequent",
        "regional_mix": "heavy",
        "emoji_usage": "heavy",
        "tone": "casual",
        "verbosity": "balanced",
    },
    {
        "gender": "Male",
        "name": "Christopher White",
        "age_group": "40-50",
        "location": "United States",
        "profession": "Manager",
        "personality": "Professional and formal",
        "communication_style": "Direct and concise",
        "accent": "American",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "clean",
        "slang_usage": "low",
        "typos_frequency": "none",
        "regional_mix": "low",
        "emoji_usage": "light",
        "tone": "neutral",
        "verbosity": "brief",
    },
    {
        "gender": "Female",
        "name": "Grace Moore",
        "age_group": "50-60",
        "location": "Canada",
        "profession": "Customer Service",
        "personality": "Friendly and cooperative",
        "communication_style": "Simple and clear",
        "accent": "Canadian",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "clean",
        "slang_usage": "moderate",
        "typos_frequency": "rare",
        "regional_mix": "moderate",
        "emoji_usage": "light",
        "tone": "casual",
        "verbosity": "balanced",
    },
    {
        "gender": "Male",
        "name": "Joseph Clark",
        "age_group": "60+",
        "location": "Australia",
        "profession": "Retired",
        "personality": "Analytical",
        "communication_style": "Questioning",
        "accent": "Australian",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "expressive",
        "slang_usage": "low",
        "typos_frequency": "occasional",
        "regional_mix": "moderate",
        "emoji_usage": "never",
        "tone": "neutral",
        "verbosity": "detailed",
    },
    {
        "gender": "Female",
        "name": "Emma Robinson",
        "age_group": "25-32",
        "location": "United Kingdom",
        "profession": "Doctor",
        "personality": "Confident",
        "communication_style": "Formal and polite",
        "accent": "Neutral",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "clean",
        "slang_usage": "none",
        "typos_frequency": "none",
        "regional_mix": "none",
        "emoji_usage": "never",
        "tone": "formal",
        "verbosity": "detailed",
    },
    {
        "gender": "Male",
        "name": "Ryan Garcia",
        "age_group": "32-40",
        "location": "United States",
        "profession": "Engineer",
        "personality": "Cautious and skeptical",
        "communication_style": "Technical",
        "accent": "American",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "minimal",
        "slang_usage": "low",
        "typos_frequency": "rare",
        "regional_mix": "low",
        "emoji_usage": "never",
        "tone": "neutral",
        "verbosity": "detailed",
    },
    {
        "gender": "Male",
        "name": "Nathan Cooper",
        "age_group": "18-25",
        "location": "United States",
        "profession": "Student",
        "personality": "Analytical",
        "communication_style": "Questioning",
        "accent": "American",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "erratic",
        "slang_usage": "heavy",
        "typos_frequency": "frequent",
        "regional_mix": "moderate",
        "emoji_usage": "regular",
        "tone": "casual",
        "verbosity": "balanced",
    },
    {
        "gender": "Female",
        "name": "Isabella Morgan",
        "age_group": "25-32",
        "location": "Australia",
        "profession": "Marketing Professional",
        "personality": "Confident",
        "communication_style": "Assertive",
        "accent": "Australian",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "expressive",
        "slang_usage": "moderate",
        "typos_frequency": "occasional",
        "regional_mix": "moderate",
        "emoji_usage": "regular",
        "tone": "casual",
        "verbosity": "balanced",
    },
    {
        "gender": "Male",
        "name": "Ethan Phillips",
        "age_group": "32-40",
        "location": "Canada",
        "profession": "Doctor",
        "personality": "Reserved",
        "communication_style": "Formal and polite",
        "accent": "Canadian",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "clean",
        "slang_usage": "none",
        "typos_frequency": "none",
        "regional_mix": "none",
        "emoji_usage": "never",
        "tone": "formal",
        "verbosity": "detailed",
    },
    {
        "gender": "Female",
        "name": "Victoria Bennett",
        "age_group": "40-50",
        "location": "United Kingdom",
        "profession": "Teacher",
        "personality": "Friendly and cooperative",
        "communication_style": "Detailed and elaborate",
        "accent": "Neutral",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "clean",
        "slang_usage": "moderate",
        "typos_frequency": "rare",
        "regional_mix": "low",
        "emoji_usage": "light",
        "tone": "casual",
        "verbosity": "detailed",
    },
    {
        "gender": "Male",
        "name": "Jack Richardson",
        "age_group": "50-60",
        "location": "United States",
        "profession": "Business Owner",
        "personality": "Impatient and direct",
        "communication_style": "Direct and concise",
        "accent": "American",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "minimal",
        "slang_usage": "low",
        "typos_frequency": "none",
        "regional_mix": "low",
        "emoji_usage": "never",
        "tone": "neutral",
        "verbosity": "brief",
    },
    {
        "gender": "Female",
        "name": "Audrey Sullivan",
        "age_group": "60+",
        "location": "Australia",
        "profession": "Retired",
        "personality": "Detail-oriented",
        "communication_style": "Simple and clear",
        "accent": "Australian",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "expressive",
        "slang_usage": "low",
        "typos_frequency": "occasional",
        "regional_mix": "moderate",
        "emoji_usage": "light",
        "tone": "casual",
        "verbosity": "detailed",
    },
    {
        "gender": "Male",
        "name": "Lucas Edwards",
        "age_group": "18-25",
        "location": "Canada",
        "profession": "Technician",
        "personality": "Easy-going",
        "communication_style": "Casual and friendly",
        "accent": "Canadian",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "erratic",
        "slang_usage": "heavy",
        "typos_frequency": "frequent",
        "regional_mix": "heavy",
        "emoji_usage": "heavy",
        "tone": "casual",
        "verbosity": "balanced",
    },
    {
        "gender": "Female",
        "name": "Mia Dawson",
        "age_group": "25-32",
        "location": "United Kingdom",
        "profession": "Consultant",
        "personality": "Talkative",
        "communication_style": "Collaborative",
        "accent": "Neutral",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "expressive",
        "slang_usage": "moderate",
        "typos_frequency": "occasional",
        "regional_mix": "low",
        "emoji_usage": "regular",
        "tone": "casual",
        "verbosity": "balanced",
    },
    {
        "gender": "Male",
        "name": "Owen Kennedy",
        "age_group": "32-40",
        "location": "United States",
        "profession": "Freelancer",
        "personality": "Anxious",
        "communication_style": "Detailed and elaborate",
        "accent": "American",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "erratic",
        "slang_usage": "moderate",
        "typos_frequency": "frequent",
        "regional_mix": "moderate",
        "emoji_usage": "regular",
        "tone": "casual",
        "verbosity": "detailed",
    },
    {
        "gender": "Female",
        "name": "Chloe Harrison",
        "age_group": "40-50",
        "location": "Australia",
        "profession": "Accountant",
        "personality": "Professional and formal",
        "communication_style": "Technical",
        "accent": "Australian",
        "language": "English",
        "simulation_type": "text",
        "punctuation": "clean",
        "slang_usage": "none",
        "typos_frequency": "none",
        "regional_mix": "none",
        "emoji_usage": "never",
        "tone": "formal",
        "verbosity": "detailed",
    },
]


HINDI_PERSONAS_TEXT = [
    {
        "gender": "Female",
        "name": "Arti Sharma",
        "age_group": "18-25",
        "location": "India",
        "profession": "Student",
        "personality": "Anxious",
        "communication_style": "Questioning",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "erratic",
        "slang_usage": "moderate",
        "typos_frequency": "frequent",
        "regional_mix": "heavy",
        "emoji_usage": "regular",
        "tone": "casual",
        "verbosity": "balanced",
    },
    {
        "gender": "Male",
        "name": "Karan Gupta",
        "age_group": "25-32",
        "location": "India",
        "profession": "Consultant",
        "personality": "Confident",
        "communication_style": "Direct and concise",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "minimal",
        "slang_usage": "moderate",
        "typos_frequency": "occasional",
        "regional_mix": "moderate",
        "emoji_usage": "light",
        "tone": "neutral",
        "verbosity": "brief",
    },
    {
        "gender": "Female",
        "name": "Jyoti Malhotra",
        "age_group": "32-40",
        "location": "India",
        "profession": "Teacher",
        "personality": "Detail-oriented",
        "communication_style": "Detailed and elaborate",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "clean",
        "slang_usage": "low",
        "typos_frequency": "rare",
        "regional_mix": "moderate",
        "emoji_usage": "light",
        "tone": "formal",
        "verbosity": "detailed",
    },
    {
        "gender": "Male",
        "name": "Ajay Tiwari",
        "age_group": "40-50",
        "location": "India",
        "profession": "Doctor",
        "personality": "Professional and formal",
        "communication_style": "Formal and polite",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "clean",
        "slang_usage": "none",
        "typos_frequency": "none",
        "regional_mix": "low",
        "emoji_usage": "never",
        "tone": "formal",
        "verbosity": "detailed",
    },
    {
        "gender": "Female",
        "name": "Rekha Mehra",
        "age_group": "50-60",
        "location": "India",
        "profession": "Homemaker",
        "personality": "Friendly and cooperative",
        "communication_style": "Casual and friendly",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "expressive",
        "slang_usage": "moderate",
        "typos_frequency": "occasional",
        "regional_mix": "heavy",
        "emoji_usage": "regular",
        "tone": "casual",
        "verbosity": "balanced",
    },
    {
        "gender": "Male",
        "name": "Sanjay Patel",
        "age_group": "60+",
        "location": "India",
        "profession": "Retired",
        "personality": "Cautious and skeptical",
        "communication_style": "Questioning",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "expressive",
        "slang_usage": "low",
        "typos_frequency": "occasional",
        "regional_mix": "moderate",
        "emoji_usage": "light",
        "tone": "neutral",
        "verbosity": "detailed",
    },
    {
        "gender": "Female",
        "name": "Anjali Arora",
        "age_group": "18-25",
        "location": "India",
        "profession": "Student",
        "personality": "Talkative",
        "communication_style": "Collaborative",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "erratic",
        "slang_usage": "heavy",
        "typos_frequency": "frequent",
        "regional_mix": "heavy",
        "emoji_usage": "heavy",
        "tone": "casual",
        "verbosity": "balanced",
    },
    {
        "gender": "Male",
        "name": "Rahul Bhatia",
        "age_group": "25-32",
        "location": "India",
        "profession": "Engineer",
        "personality": "Impatient and direct",
        "communication_style": "Technical",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "minimal",
        "slang_usage": "moderate",
        "typos_frequency": "occasional",
        "regional_mix": "moderate",
        "emoji_usage": "light",
        "tone": "neutral",
        "verbosity": "brief",
    },
    {
        "gender": "Female",
        "name": "Sheetal Chopra",
        "age_group": "32-40",
        "location": "India",
        "profession": "Sales Representative",
        "personality": "Emotional",
        "communication_style": "Passive",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "expressive",
        "slang_usage": "moderate",
        "typos_frequency": "occasional",
        "regional_mix": "heavy",
        "emoji_usage": "regular",
        "tone": "casual",
        "verbosity": "detailed",
    },
    {
        "gender": "Male",
        "name": "Vivek Yadav",
        "age_group": "40-50",
        "location": "India",
        "profession": "Customer Service",
        "personality": "Easy-going",
        "communication_style": "Simple and clear",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "clean",
        "slang_usage": "moderate",
        "typos_frequency": "rare",
        "regional_mix": "moderate",
        "emoji_usage": "light",
        "tone": "casual",
        "verbosity": "balanced",
    },
    {
        "gender": "Male",
        "name": "Arjun Sharma",
        "age_group": "25-32",
        "location": "India",
        "profession": "Engineer",
        "personality": "Analytical",
        "communication_style": "Technical",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "clean",
        "slang_usage": "low",
        "typos_frequency": "rare",
        "regional_mix": "moderate",
        "emoji_usage": "never",
        "tone": "formal",
        "verbosity": "detailed",
    },
    {
        "gender": "Female",
        "name": "Priya Patel",
        "age_group": "18-25",
        "location": "India",
        "profession": "Student",
        "personality": "Friendly and cooperative",
        "communication_style": "Casual and friendly",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "erratic",
        "slang_usage": "heavy",
        "typos_frequency": "frequent",
        "regional_mix": "heavy",
        "emoji_usage": "heavy",
        "tone": "casual",
        "verbosity": "balanced",
    },
    {
        "gender": "Male",
        "name": "Vikram Singh",
        "age_group": "32-40",
        "location": "India",
        "profession": "Business Owner",
        "personality": "Confident",
        "communication_style": "Assertive",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "minimal",
        "slang_usage": "moderate",
        "typos_frequency": "occasional",
        "regional_mix": "moderate",
        "emoji_usage": "light",
        "tone": "neutral",
        "verbosity": "brief",
    },
    {
        "gender": "Female",
        "name": "Ananya Gupta",
        "age_group": "25-32",
        "location": "India",
        "profession": "Doctor",
        "personality": "Professional and formal",
        "communication_style": "Formal and polite",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "clean",
        "slang_usage": "none",
        "typos_frequency": "none",
        "regional_mix": "low",
        "emoji_usage": "never",
        "tone": "formal",
        "verbosity": "detailed",
    },
    {
        "gender": "Male",
        "name": "Rohit Verma",
        "age_group": "40-50",
        "location": "India",
        "profession": "Manager",
        "personality": "Detail-oriented",
        "communication_style": "Direct and concise",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "clean",
        "slang_usage": "low",
        "typos_frequency": "rare",
        "regional_mix": "moderate",
        "emoji_usage": "never",
        "tone": "neutral",
        "verbosity": "balanced",
    },
    {
        "gender": "Female",
        "name": "Neha Sharma",
        "age_group": "32-40",
        "location": "India",
        "profession": "Teacher",
        "personality": "Friendly and cooperative",
        "communication_style": "Detailed and elaborate",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "clean",
        "slang_usage": "moderate",
        "typos_frequency": "rare",
        "regional_mix": "moderate",
        "emoji_usage": "light",
        "tone": "casual",
        "verbosity": "detailed",
    },
    {
        "gender": "Male",
        "name": "Amit Kumar",
        "age_group": "50-60",
        "location": "India",
        "profession": "Consultant",
        "personality": "Analytical",
        "communication_style": "Technical",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "clean",
        "slang_usage": "low",
        "typos_frequency": "rare",
        "regional_mix": "moderate",
        "emoji_usage": "never",
        "tone": "formal",
        "verbosity": "detailed",
    },
    {
        "gender": "Female",
        "name": "Divya Mishra",
        "age_group": "18-25",
        "location": "India",
        "profession": "Student",
        "personality": "Talkative",
        "communication_style": "Casual and friendly",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "erratic",
        "slang_usage": "heavy",
        "typos_frequency": "frequent",
        "regional_mix": "heavy",
        "emoji_usage": "heavy",
        "tone": "casual",
        "verbosity": "balanced",
    },
    {
        "gender": "Male",
        "name": "Rajesh Khanna",
        "age_group": "60+",
        "location": "India",
        "profession": "Retired",
        "personality": "Easy-going",
        "communication_style": "Simple and clear",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "expressive",
        "slang_usage": "low",
        "typos_frequency": "occasional",
        "regional_mix": "moderate",
        "emoji_usage": "light",
        "tone": "casual",
        "verbosity": "detailed",
    },
    {
        "gender": "Female",
        "name": "Meera Iyer",
        "age_group": "40-50",
        "location": "India",
        "profession": "Accountant",
        "personality": "Detail-oriented",
        "communication_style": "Formal and polite",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "clean",
        "slang_usage": "none",
        "typos_frequency": "none",
        "regional_mix": "low",
        "emoji_usage": "never",
        "tone": "formal",
        "verbosity": "detailed",
    },
    {
        "gender": "Male",
        "name": "Sunil Mehta",
        "age_group": "25-32",
        "location": "India",
        "profession": "Sales Representative",
        "personality": "Confident",
        "communication_style": "Assertive",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "minimal",
        "slang_usage": "moderate",
        "typos_frequency": "occasional",
        "regional_mix": "moderate",
        "emoji_usage": "light",
        "tone": "neutral",
        "verbosity": "brief",
    },
    {
        "gender": "Female",
        "name": "Kavita Reddy",
        "age_group": "32-40",
        "location": "India",
        "profession": "Marketing Professional",
        "personality": "Friendly and cooperative",
        "communication_style": "Collaborative",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "expressive",
        "slang_usage": "moderate",
        "typos_frequency": "occasional",
        "regional_mix": "moderate",
        "emoji_usage": "regular",
        "tone": "casual",
        "verbosity": "balanced",
    },
    {
        "gender": "Male",
        "name": "Prakash Joshi",
        "age_group": "50-60",
        "location": "India",
        "profession": "Manager",
        "personality": "Professional and formal",
        "communication_style": "Direct and concise",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "clean",
        "slang_usage": "low",
        "typos_frequency": "rare",
        "regional_mix": "moderate",
        "emoji_usage": "never",
        "tone": "neutral",
        "verbosity": "balanced",
    },
    {
        "gender": "Female",
        "name": "Sunita Agarwal",
        "age_group": "40-50",
        "location": "India",
        "profession": "Nurse",
        "personality": "Emotional",
        "communication_style": "Detailed and elaborate",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "expressive",
        "slang_usage": "moderate",
        "typos_frequency": "occasional",
        "regional_mix": "heavy",
        "emoji_usage": "regular",
        "tone": "casual",
        "verbosity": "detailed",
    },
    {
        "gender": "Male",
        "name": "Vijay Malhotra",
        "age_group": "32-40",
        "location": "India",
        "profession": "Engineer",
        "personality": "Cautious and skeptical",
        "communication_style": "Technical",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "clean",
        "slang_usage": "low",
        "typos_frequency": "rare",
        "regional_mix": "moderate",
        "emoji_usage": "never",
        "tone": "formal",
        "verbosity": "detailed",
    },
    {
        "gender": "Female",
        "name": "Pooja Desai",
        "age_group": "25-32",
        "location": "India",
        "profession": "Customer Service",
        "personality": "Friendly and cooperative",
        "communication_style": "Simple and clear",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "clean",
        "slang_usage": "moderate",
        "typos_frequency": "rare",
        "regional_mix": "moderate",
        "emoji_usage": "light",
        "tone": "casual",
        "verbosity": "balanced",
    },
    {
        "gender": "Male",
        "name": "Deepak Choudhary",
        "age_group": "18-25",
        "location": "India",
        "profession": "Student",
        "personality": "Reserved",
        "communication_style": "Questioning",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "erratic",
        "slang_usage": "moderate",
        "typos_frequency": "frequent",
        "regional_mix": "heavy",
        "emoji_usage": "regular",
        "tone": "casual",
        "verbosity": "balanced",
    },
    {
        "gender": "Female",
        "name": "Rani Kapoor",
        "age_group": "60+",
        "location": "India",
        "profession": "Retired",
        "personality": "Easy-going",
        "communication_style": "Casual and friendly",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "expressive",
        "slang_usage": "low",
        "typos_frequency": "occasional",
        "regional_mix": "moderate",
        "emoji_usage": "light",
        "tone": "casual",
        "verbosity": "detailed",
    },
    {
        "gender": "Male",
        "name": "Nitin Bajaj",
        "age_group": "40-50",
        "location": "India",
        "profession": "Business Owner",
        "personality": "Impatient and direct",
        "communication_style": "Direct and concise",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "minimal",
        "slang_usage": "moderate",
        "typos_frequency": "occasional",
        "regional_mix": "moderate",
        "emoji_usage": "never",
        "tone": "neutral",
        "verbosity": "brief",
    },
    {
        "gender": "Female",
        "name": "Ritu Saxena",
        "age_group": "32-40",
        "location": "India",
        "profession": "Freelancer",
        "personality": "Creative",
        "communication_style": "Detailed and elaborate",
        "accent": "Indian",
        "language": "Hindi",
        "simulation_type": "text",
        "punctuation": "expressive",
        "slang_usage": "moderate",
        "typos_frequency": "occasional",
        "regional_mix": "moderate",
        "emoji_usage": "regular",
        "tone": "casual",
        "verbosity": "detailed",
    },
]


def get_personas_by_language(agent_language, agent_type: Optional[str] = None):
    """
    Get the appropriate persona list based on agent definition language.

    Args:
        agent_language (str): Language code from agent definition (e.g., 'hi' for Hindi, 'en' for English)

    Returns:
        list: List of personas matching the language (defaults to ENGLISH_PERSONAS)
    """
    # Check if language is Hindi (case insensitive check for both code 'hi' and full name 'hindi')

    if agent_language and (
        agent_language.lower() == "hi" or agent_language.lower() == "hindi"
    ):
        if agent_type and agent_type == "text":
            return HINDI_PERSONAS_TEXT

        else:
            return HINDI_PERSONAS

    # Default to English personas for all other languages
    if agent_type and agent_type == "text":
        return ENGLISH_PERSONAS_TEXT

    return ENGLISH_PERSONAS


# Example usage and testing
if __name__ == "__main__":
    # Test with sample persona data
    sample_persona = {
        "gender": "female",
        "age_group": "middle_aged",
        "personality": "professional",
        "communication_style": "formal",
        "profession": "lawyer",
        "location": "New York",
    }

    print("Sample persona:", sample_persona)
    print("Selected voice (LLM):", select_voice_with_llm(sample_persona))
    print("Selected voice (Rule-based):", select_voice_id(sample_persona))

    # Test safety validation
    print("\n--- Safety Tests ---")
    print(
        "Valid voice validation:", validate_and_return_voice("phillip", sample_persona)
    )
    print(
        "Invalid voice validation:",
        validate_and_return_voice("invalid_voice", sample_persona),
    )
    print("Empty persona validation:", validate_and_return_voice("invalid_voice", {}))
    print("None persona validation:", validate_and_return_voice("invalid_voice", None))
