# Generated by Django 5.1.8 on 2026-03-17 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_ai', '0003_falconfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='files',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='falconfile',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to='falcon_ai.conversation'),
        ),
        migrations.AlterField(
            model_name='falconfile',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to='falcon_ai.message'),
        ),
    ]
