# Generated by Django 5.1.8 on 2026-03-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_ai', '0004_message_files_alter_falconfile_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpconnector',
            name='oauth_access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mcpconnector',
            name='oauth_client_id',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='mcpconnector',
            name='oauth_client_secret',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mcpconnector',
            name='oauth_code_verifier',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mcpconnector',
            name='oauth_refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mcpconnector',
            name='oauth_server_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mcpconnector',
            name='oauth_state',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mcpconnector',
            name='oauth_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcpconnector',
            name='auth_type',
            field=models.CharField(choices=[('none', 'No Authentication'), ('api_key', 'API Key'), ('bearer', 'Bearer Token'), ('oauth', 'OAuth 2.1')], default='none', max_length=20),
        ),
    ]
