# Generated by Django 5.1.8 on 2026-03-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_ai', '0005_mcpconnector_oauth_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='context_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='conversation',
            name='total_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
