import { format } from "date-fns";
import { SCENARIO_STATUS } from "src/pages/dashboard/scenarios/common";
import { z } from "zod";
export const replaySessionsFormSchema = z
  .object({
    agentDefinition: z.object({
      id: z.string().nullable().optional(),
      name: z.string().min(1, "Agent name is required"),
      version: z.string().min(1, "Agent version is required"),
      versionId: z.string().nullable().optional(),
      prompt: z.string().min(1, "Agent prompt is required"),
    }),
    scenarioName: z.string().min(1, "Scenario name is required"),
    numOfScenarios: z.coerce
      .number({
        invalid_type_error: "Number of scenarios is required",
      })
      .min(10, { message: "Number of scenarios must be at least 10" })
      .max(20000, { message: "Maximum 20000 scenarios are allowed" }),
    // numOfSessions: z.coerce
    //   .number({
    //     invalid_type_error: "Number of sessions is required",
    //   })
    //   .min(1, { message: "Number of sessions must be at least 1" }),
    addPersonaAutomatically: z.boolean().default(true),
    // columns: z.array(
    //   z.object({
    //     name: z
    //       .string()
    //       .min(1, "Column name is required")
    //       .max(50, "Column name must be less than 50 characters"),

    //     type: z.enum(
    //       ["text", "boolean", "integer", "float", "json", "array", "datetime"],
    //       { message: "Data type is required" },
    //     ),

    //     description: z
    //       .string()
    //       .min(1, "Description is required")
    //       .max(200, "Description must be less than 200 characters"),
    //   }),
    // ),
    personas: z
      .array(z.object({ id: z.string() }))
      .transform((arr) => arr.map((item) => item.id)),
    hasAgentPrompt: z.boolean().default(false),
    agentDefExists: z.boolean().default(false),
    agentType: z.enum(["text", "voice"]).default("text"),
    replaySessionId: z.string().min(1, "Replay session ID is required"),
  })
  .refine((data) => {
    if (!data.addPersonaAutomatically && data.personas.length === 0) {
      return {
        message: "At least one persona is required",
        path: ["personas"],
      };
    }
    return true;
  })
  .transform((data) => {
    const transformedData = {
      ...data,
      agent_name: data?.agentDefinition?.name,
      agent_description: data?.agentDefinition?.prompt,
      agent_type: data?.agentType,
      scenario_name: data?.scenarioName,
      no_of_rows: data?.numOfScenarios,
      add_persona_automatically: data?.addPersonaAutomatically,
      replay_session_id: data?.replaySessionId,
      version_id: data?.versionId,
      // customColumns: data?.columns,
    };
    delete transformedData.agentDefinition;
    delete transformedData.agentType;
    delete transformedData.scenarioName;
    delete transformedData.numOfScenarios;
    delete transformedData.columns;
    delete transformedData.addPersonaAutomatically;
    delete transformedData.replaySessionId;

    if (data?.addPersonaAutomatically) {
      transformedData.personas = [];
    }
    delete transformedData.hasAgentPrompt;
    delete transformedData.agentDefExists;
    delete transformedData.versionId;
    return transformedData;
  });

export const getReplaySessionsFormDefaultValues = (createdReplay) => {
  const agentDefinitionExists = createdReplay?.exists;

  return {
    agentDefinition: {
      id: createdReplay?.agent_definition_id,
      name: createdReplay?.suggestions?.agent_name ?? "",
      version: createdReplay?.suggestions?.version_name ?? "v1",
      versionId: "",
      prompt: createdReplay?.suggestions?.agent_description ?? "",
    },
    scenarioName: createdReplay?.suggestions?.scenario_name ?? "",
    numOfScenarios: createdReplay?.numOfScenarios ?? 10,
    // numOfSessions: editData?.numOfSessions ?? 0,
    // columns: [],
    personas: [],
    addPersonaAutomatically: createdReplay?.addPersonaAutomatically ?? true,
    hasAgentPrompt: Boolean(createdReplay?.suggestions?.agent_description),
    agentDefExists: Boolean(agentDefinitionExists),
    agentType: createdReplay?.suggestions?.agent_type ?? "text",
    replaySessionId: createdReplay?.id,
  };
};

const generateSimulationNameAndDescription = (projectDetail) => {
  return {
    name: `${projectDetail?.name}_replay_${format(new Date(), "dd-MMM-yyyy_HH-mm")}`,
    description: `Generated by Replay Sessions for project ${projectDetail?.name}`,
  };
};

const transformMapping = (mapping, requiredKeys, optionalKeys) => {
  const requiredKeysMappingObject = requiredKeys?.reduce((acc, curr) => {
    return {
      ...acc,
      [curr.replace(/\./g, "_")]: curr,
    };
  }, {});
  const optionalKeysMappingObject = optionalKeys?.reduce((acc, curr) => {
    return {
      ...acc,
      [curr.replace(/\./g, "_")]: curr,
    };
  }, {});
  const newMapping = {};

  // Process all keys in the mapping object
  // Check if they match required keys or optional keys
  Object.entries(mapping).forEach(([transformedKey, value]) => {
    // Check if it's a required key
    if (requiredKeysMappingObject[transformedKey]) {
      newMapping[requiredKeysMappingObject[transformedKey]] = value;
    }
    // Check if it's an optional key
    else if (optionalKeysMappingObject[transformedKey]) {
      newMapping[optionalKeysMappingObject[transformedKey]] = value;
    }
  });

  // Remove empty values
  const keysToBeRemoved = [];
  Object.entries(newMapping).forEach(([key, val]) => {
    if (val === "" || val === null || val === undefined) {
      keysToBeRemoved.push(key);
    }
  });
  for (let i = 0; i < keysToBeRemoved.length; ++i) {
    delete newMapping[keysToBeRemoved[i]];
  }
  return newMapping;
};

const getEvaluationMappingPayload = (
  data,
  requiredKeys,
  optionalKeys,
  projectEvals,
) => {
  const globalMapping = transformMapping(
    data.config.mapping,
    requiredKeys,
    optionalKeys,
  );
  const globalModel = data.model || "";
  const globalKbId = data.kbId || "";
  const globalErrorLocalizer = data.errorLocalizer || false;

  // Create individual eval payloads
  const individualEvalPayloads = projectEvals.map((evalItem) => {
    // Filter mapping to only include keys relevant to this eval
    const evalMapping = {};
    const evalRequiredKeys = evalItem.requiredKeys || [];
    const evalOptionalKeys = evalItem.optionalKeys || [];

    // Add required keys mapping
    evalRequiredKeys.forEach((key) => {
      if (globalMapping[key]) {
        evalMapping[key] = globalMapping[key];
      }
    });

    // Add optional keys mapping
    evalOptionalKeys.forEach((key) => {
      if (globalMapping[key]) {
        evalMapping[key] = globalMapping[key];
      }
    });

    // Determine model for this eval
    let evalModel = globalModel;
    const allowedEvalModels = evalItem.models || [];
    if (
      allowedEvalModels.length > 0 &&
      !allowedEvalModels.includes(globalModel)
    ) {
      evalModel = allowedEvalModels[0];
    }

    return {
      name: evalItem.name,
      template_id: evalItem.evalTemplateId,
      mapping: evalMapping,
      model: evalModel || undefined,
      error_localizer: globalErrorLocalizer,
      kb_id: globalKbId || undefined,
      config: {
        mapping: evalMapping,
        config: {},
        reasonColumn: data.config.reasonColumn,
      },
    };
  });
  return individualEvalPayloads;
};

export const getRunSimulationPayload = (
  data,
  projectDetail,
  requiredKeys,
  optionalKeys,
  projectEvals,
) => {
  const { name, description } =
    generateSimulationNameAndDescription(projectDetail);
  const evaluationsConfig =
    projectEvals?.length > 0
      ? getEvaluationMappingPayload(
          data,
          requiredKeys,
          optionalKeys,
          projectEvals,
        )
      : [];
  return {
    agent_definition_id: data?.createdScenario?.agent_definition_id,
    agent_version: data?.createdScenario?.agent_definition_latest_version_id,
    name: name,
    description: description,
    enable_tool_evaluation: false,
    scenario_ids: [data?.createdScenario?.scenario_id],
    eval_config_ids: [],
    evaluations_config: evaluationsConfig,
    replay_session_id: data?.replaySessionId,
  };
};
export const getConfirmationMessages = (status) => {
  if (status === SCENARIO_STATUS.PROCESSING) {
    return {
      title: "Are you sure you want to close?",
      message:
        "Your scenario is currently being processed. Are you sure you want to leave?",
      content:
        "The scenarios will continue generating in the background. You can run the simulation later.",
    };
  }

  // Default messages for other statuses (Completed, Failed, etc.) or when status is unknown
  return {
    title: "Unsaved Changes",
    message: "Are you sure you want to proceed?",
    content:
      "You have unsaved changes. If you leave now, they will be permanently lost.",
  };
};

export const buildEvaluationMappingFormSchema = (requiredKeys) => {
  return z.object({
    model: z.string(),
    config: z.object({
      mapping: z
        .record(z.string().optional())
        .refine(
          (val) =>
            requiredKeys.every((key) => val[key] && val[key].trim() !== ""),
          {
            message: "Required input mappings must be filled",
          },
        ),
      reasonColumn: z.boolean(),
    }),
    errorLocalizer: z.boolean(),
    kbId: z.string().optional(),
    projectEvals: z.array(z.unknown()).default([]),
  });
};

export const formatProjectEvals = (evalConfigs) => {
  if (!evalConfigs) return [];
  return evalConfigs?.map((evalItem) => ({
    evalTemplateId: evalItem.eval_template?.id,
    eval_template_id: evalItem.eval_template?.id,
    name: evalItem.name,
    description: evalItem.eval_template?.description,
    requiredKeys: evalItem.eval_template?.required_keys,
    optionalKeys: evalItem.eval_template?.optional_keys,
    models: evalItem?.available_models ?? [],
    tags: evalItem.eval_template?.tags ?? [],
    fromProject: true,
  }));
};
