"""
Django settings for tfc project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import re
from datetime import datetime, timedelta
from pathlib import Path

# Structured logging configuration
from tfc.logging import configure_structlog, get_logging_config, init_sentry
from tfc.settings.runtime_setting_specs import (
    RUNTIME_NUMERIC_SETTING_SPECS as _runtime_numeric_setting_specs,
)
from tfc.settings.runtime_setting_specs import (
    NumericSettingSpec as _NumericSettingSpec,
)
from tfc.settings.runtime_setting_specs import (
    load_numeric_settings as _load_numeric_settings,
)
from tfc.settings.runtime_setting_specs import (
    validate_runtime_numeric_settings as _validate_runtime_numeric_settings,
)

configure_structlog()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY is set below from env var (search for "SECRET_KEY =")

# Environment classification — used below for security-sensitive defaults.
# Must be one of: local, test, dev, staging, prod. Defaults to "local".
ENV_TYPE = os.getenv("ENV_TYPE", "local").lower()
_IS_LOCAL = ENV_TYPE in ("local", "test")

# Exact analytics continue to use the existing XL queue unless a deployment
# explicitly provisions the dedicated single-slot worker.  This keeps local,
# development, EU, and self-hosted installs compatible while allowing the US
# ClickHouse cluster to opt into strict refresh admission.
EXACT_AGGREGATION_TASK_QUEUE = os.getenv(
    "EXACT_AGGREGATION_TASK_QUEUE",
    "tasks_xl",
)

# Eval-usage API reads use ClickHouse in deployed environments. Keep the
# source selection explicit so contract tests and standalone installs can use
# the existing PostgreSQL fallback without changing global ClickHouse routing.
EVAL_USAGE_CLICKHOUSE_ENABLED = os.getenv(
    "EVAL_USAGE_CLICKHOUSE_ENABLED",
    "true",
).lower() in ("true", "1", "t", "yes", "y")


def _split_env(name: str, default: str = "") -> list[str]:
    """Parse a comma-separated env var into a list."""
    raw = os.getenv(name, default)
    return [x.strip() for x in raw.split(",") if x.strip()]


def _bounded_env_int(
    name: str,
    default: int,
    *,
    minimum: int,
    maximum: int,
) -> int:
    """Parse one setting whose default or bound depends on another setting."""

    spec = _NumericSettingSpec(int, default, minimum, maximum)
    return int(spec.parse(name, os.getenv(name)))


# Numeric runtime knobs are declared once in runtime_setting_specs.py. Parse
# and cross-validate them before database/cache configuration consumes them.
_runtime_numeric_settings = _load_numeric_settings(
    _runtime_numeric_setting_specs,
    source=os.environ,
)
del _runtime_numeric_setting_specs
_validate_runtime_numeric_settings(_runtime_numeric_settings)
globals().update(_runtime_numeric_settings)

# Optional ClickHouse cluster whose entries intentionally expose each physical
# replica as one read shard. Dashboard heavy reads use it only after validating
# the identifier in the query builder; an empty value keeps the local-table
# fallback for OSS and single-node installations.
DASHBOARD_TRACE_REPLICA_SHARD_CLUSTER = os.getenv(
    "DASHBOARD_TRACE_REPLICA_SHARD_CLUSTER", ""
).strip()

SIMULATOR_PHONE_NUMBERS = tuple(
    _split_env(
        "SIMULATOR_PHONE_NUMBERS",
        ",".join(
            (
                "+18568806998",
                "+17755715840",
                "+13463424590",
                "+12175683677",
                "+12175696753",
                "+12175683493",
                "+12175681887",
                "+12176018447",
                "+12176018280",
                "+12175696862",
                "+19168660414",
                "+19163473349",
                "+18563161617",
                "+13463619738",
                "+19847339395",
            )
        ),
    )
)

# These three values are consumed in this module before application code
# imports the remaining dynamically published Django settings. Explicit aliases
# keep static analysis honest without duplicating their parsing or defaults.
PG_CONNECT_TIMEOUT_SECONDS = int(
    _runtime_numeric_settings["PG_CONNECT_TIMEOUT_SECONDS"]
)
REDIS_CACHE_SOCKET_CONNECT_TIMEOUT_SECONDS = float(
    _runtime_numeric_settings["REDIS_CACHE_SOCKET_CONNECT_TIMEOUT_SECONDS"]
)
REDIS_CACHE_SOCKET_TIMEOUT_SECONDS = float(
    _runtime_numeric_settings["REDIS_CACHE_SOCKET_TIMEOUT_SECONDS"]
)


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True" if _IS_LOCAL else "False").lower() in (
    "true",
    "1",
    "t",
    "yes",
    "y",
)

# ── ALLOWED_HOSTS ─────────────────────────────────────────────────────────
# Open by default for self-host-friendly OSS conventions —
# production deployments should tighten this via the ALLOWED_HOSTS env var
# or enforce via a reverse proxy (nginx / Caddy / load balancer).
ALLOWED_HOSTS = _split_env("ALLOWED_HOSTS", "*")

# ── CORS (django-cors-headers) ────────────────────────────────────────────
# Default: permissive — any browser origin can hit the API. Production
# self-hosters should set CORS_ALLOWED_ORIGINS (comma-separated) to flip
# CORS_ALLOW_ALL_ORIGINS off when explicit origins are configured.
_cors_origins = _split_env("CORS_ALLOWED_ORIGINS")
if _cors_origins:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = _cors_origins
else:
    CORS_ALLOW_ALL_ORIGINS = True
# Legacy alias (django-cors-headers pre-4.0)
CORS_ORIGIN_ALLOW_ALL = CORS_ALLOW_ALL_ORIGINS

CORS_ALLOWED_ORIGIN_REGEXES = _split_env("CORS_ALLOWED_ORIGIN_REGEXES")
CORS_ORIGIN_REGEX_WHITELIST = CORS_ALLOWED_ORIGIN_REGEXES  # legacy alias

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]

# Scope the CORS middleware to API / ingest paths only. Admin pages, static
# files, and Django admin don't need CORS headers.
# CORS_URLS_REGEX = r"^/(api/|tracer/|v1/|oauth/|static/).*$"
CORS_URLS_REGEX = r"^/(?!admin/|docs/|swagger|__debug__/).*$"

# Extend django-cors-headers' defaults with tracing + workspace headers we
# actually read. Using `default_headers` means we automatically pick up any
# new safe headers added upstream without maintaining a hand-rolled list.
from corsheaders.defaults import default_headers  # noqa: E402

CORS_ALLOW_HEADERS = (
    *default_headers,
    *(
        "x-api-key",
        "x-secret-key",
        "x-workspace-id",
        "x-workspace-slug",
        "x-project-id",
        "x-organization-id",
        "sentry-trace",
        "baggage",
        "traceparent",
        "tracestate",
    ),
)

# CSRF_TRUSTED_ORIGINS is built dynamically after BASE_URL is resolved — see below.

# Application definition

INSTALLED_APPS = [
    "channels",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Required for database cache
    "rest_framework",
    "django_filters",
    "rest_framework_simplejwt",
    "anymail",
    "drf_yasg",
    "corsheaders",
    "django_celery_beat",
    "django_celery_results",
    # custom apps
    "tfc.apps.TfcConfig",
    "sockets",
    "accounts",
    "model_hub",
    "tracer",
    "simulate",
    "agent_playground.apps.AgentPlaygroundConfig",
    "integrations",
    # AI tools shared layer (MCP + AI Assistant)
    "ai_tools",
    # MCP Server (protocol layer for external AI clients)
    "mcp_server",
    "agentcc",
    "tfc.deployment_telemetry",
    "tfc.licensing",
    "tfc.capabilities",
    # gRPC framework
    "django_socio_grpc",
    # "djstripe"
    "saml2_auth",
    # Structured logging
    "django_structlog",
]

# EE apps.
#   - ee.usage: gated on presence only — it implements DeploymentMode.
#   - ee feature modules: gated on presence AND deployment mode (EE/Cloud).
from tfc.ee_loader import ee_feature_enabled, has_ee  # noqa: E402

if ee_feature_enabled("ee.falcon_ai"):
    INSTALLED_APPS.append("ee.falcon_ai.apps.FalconAIConfig")
if has_ee("ee.usage"):
    INSTALLED_APPS.append("ee.usage")
if has_ee("ee.licensing"):
    INSTALLED_APPS.append("ee.licensing")
if has_ee("ee.cloud.control_plane") and os.environ.get("CLOUD_DEPLOYMENT", "") in (
    "US",
    "EU",
    "DEV",
):
    INSTALLED_APPS.append("ee.cloud.control_plane.apps.CloudControlPlaneConfig")

# Site ID for django.contrib.sites
SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",  #
    "tfc.middleware.cors_origin.OriginCheckMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "tfc.telemetry.middleware.OTelContextMiddleware",  # OpenTelemetry context enrichment (after auth)
    "django_structlog.middlewares.RequestMiddleware",  # Structured logging - adds request_id, ip, etc.
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 'tfc.middleware.debug_middleware.DebugMiddleware',
    "tfc.middleware.auth_monitoring.AuthMonitoringMiddleware",
    "tfc.utils.audit.AuditMiddleware",  # Stores request.user in thread-local for audit logging
    # 'tfc.middleware.query_timeout.QueryTimeoutMiddleware',
    "accounts.authentication.AuthMonitoringMiddleware",
    # Workspace context and permissions are now handled in APIKeyAuthentication class
    "tfc.middleware.workspace_context.WorkspaceContextMiddleware",
]
if has_ee("ee.usage"):
    MIDDLEWARE.append("ee.usage.middleware.rate_limit.RateLimitMiddleware")
    MIDDLEWARE.append("ee.usage.middleware.ee.EEFeatureMiddleware")
MIDDLEWARE += [
    # "tfc.middleware.workspace_permissions.WorkspacePermissionMiddleware",
    # "tfc.middleware.workspace_permissions.WorkspaceCRUDMiddleware",
    "accounts.middleware.require_2fa.Require2FAMiddleware",
    "tfc.middleware.posthog_middleware.PostHogMiddleware",  # API analytics (after auth)
]

# To check all the APIs
SWAGGER_SETTINGS = {
    "DEFAULT_INFO": "tfc.urls.info_api",
    "DEFAULT_AUTO_SCHEMA_CLASS": "tfc.utils.api_contracts.ManagementAPIAutoSchema",
    "SECURITY_DEFINITIONS": {
        "X-Api-Key": {"type": "apiKey", "in": "header", "name": "X-Api-Key"},
        "X-Secret-Key": {
            "type": "apiKey",
            "in": "header",
            "name": "X-Secret-Key",
        },
    },
    "USE_SESSION_AUTH": False,
}

ROOT_URLCONF = "tfc.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tfc.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


def _pg_config(host, port=None, *, name=None, disable_cursors=True, options=None):
    """
    Build a Postgres config dict for a Django DATABASES alias.

    Mirrors PostHog's `postgres_config()` helper. The `default`, `replica`,
    and `default_direct` aliases differ only by host/port and (for
    default_direct) cursor + lock-timeout options, so we factor the shared
    config here.

    Behaviour note: an empty-string `port` or `name` falls back to the
    PG_DB / PGBOUNCER_PORT defaults via `or` semantics. The previous
    DATABASES block preserved empty strings verbatim — this is a small,
    intentional behaviour change because an empty PORT / NAME would have
    failed anyway at connection time.
    """
    connection_options = {
        "connect_timeout": PG_CONNECT_TIMEOUT_SECONDS,
        **(options or {}),
    }
    cfg = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": name or os.getenv("PG_DB", "tfc"),
        "USER": os.getenv("PG_USER", "user"),
        "PASSWORD": os.getenv("PG_PASSWORD", "password"),
        "HOST": host,
        "PORT": port or os.getenv("PGBOUNCER_PORT", 6432),
        "CONN_MAX_AGE": 0,
        # Verify connection is alive before use (prevents stale PgBouncer connections)
        "CONN_HEALTH_CHECKS": True,
        # Required for PgBouncer transaction pooling (server-side cursors need session persistence)
        "DISABLE_SERVER_SIDE_CURSORS": disable_cursors,
        # CONN_MAX_AGE=0 opens a socket on every request. Keep that transport
        # step inside the same sub-ten-second interactive budget as the
        # endpoint's request-owned statement deadlines.
        "OPTIONS": connection_options,
    }
    return cfg


DATABASES = {
    "default": _pg_config(os.getenv("PGBOUNCER_HOST", "pgbouncer")),
}

# Read replica — only enabled when PGBOUNCER_READ_HOST is set.
# Falls back to default when not configured, so safe to deploy without a replica.
_read_host = os.getenv("PGBOUNCER_READ_HOST")
if _read_host:
    DATABASES["replica"] = _pg_config(
        _read_host,
        port=os.getenv("PGBOUNCER_READ_PORT", os.getenv("PGBOUNCER_PORT", 6432)),
        name=os.getenv("PG_READ_DB", os.getenv("PG_DB", "tfc")),
    )
    DATABASES["replica"]["TEST"] = {
        "MIRROR": "default"
    }  # Tests use default DB, not a real replica

# Direct connection (bypasses PgBouncer) — used for migrations that need
# `lock_timeout` set at connection time. PgBouncer transaction-pool mode
# does not persist session-level SET statements between transactions, so a
# `SET lock_timeout` issued by the migration runner would not survive.
# This connection has server-side cursors ENABLED (no PgBouncer to break
# them) — useful for data-migration scripts that iterate over large tables.
_direct_host = os.getenv("PG_DIRECT_HOST")
if _direct_host:
    # Defensive: malformed env var should not crash Django at import time.
    try:
        _lock_timeout_ms = int(os.getenv("PG_MIGRATION_LOCK_TIMEOUT_MS", "20000"))
    except (TypeError, ValueError):
        _lock_timeout_ms = 20000
    DATABASES["default_direct"] = _pg_config(
        _direct_host,
        port=os.getenv("PG_DIRECT_PORT", "5432"),
        disable_cursors=False,
        options={"options": f"-c lock_timeout={_lock_timeout_ms}"},
    )
    DATABASES["default_direct"]["TEST"] = {"MIRROR": "default"}

# Opt-in list for read-replica routing. Comma-separated.
# Accepts TWO kinds of strings, NAMESPACED to avoid collision:
#   - Bare model class names (e.g. "Dashboard", "SavedView") — ReadReplicaRouter
#     routes those models to the replica.
#   - Feature/path keys prefixed with "feature:" (e.g. "feature:dashboard_render")
#     — hot-path code checks these and switches its `db_manager()` target
#     manually. The router ignores prefixed keys.
# Special value 'ALL_MODELS_USE_READ_REPLICA' routes every model — DO NOT use
# outside a controlled load-shed experiment (we have ~245 atomic/locking
# sites; routing everything is a consistency incident waiting to happen).
#
# IMPORTANT: env-var changes only take effect after worker restart. The
# router re-reads settings per call, but feature-key constants in hot paths
# are computed at import time.
_opt_in_raw = os.getenv("READ_REPLICA_OPT_IN", "")
READ_REPLICA_OPT_IN: list[str] = [
    s.strip() for s in _opt_in_raw.split(",") if s.strip()
]

DATABASE_ROUTERS = ["tfc.routers.ReadReplicaRouter"]

CLICKHOUSE = {
    "CH_HOST": os.getenv("CH_HOST"),
    "CH_PORT": os.getenv("CH_PORT", "8123"),
    "CH_USERNAME": os.getenv("CH_USERNAME", "default"),
    "CH_PASSWORD": os.getenv("CH_PASSWORD", ""),
    "CH_DATABASE": os.getenv("CH_DATABASE", "futureagi"),
    # Phase 6: ClickHouse Analytics Backend
    "CH_ENABLED": os.getenv("CH_ENABLED", "false").lower() in ("true", "1", "yes"),
    "CH_DUAL_WRITE": os.getenv("CH_DUAL_WRITE", "false").lower()
    in ("true", "1", "yes"),
    "CH_BATCH_SIZE": int(os.getenv("CH_BATCH_SIZE", "1000")),
    "CH_FLUSH_INTERVAL_SECONDS": int(os.getenv("CH_FLUSH_INTERVAL_SECONDS", "5")),
    "CH_MAX_RETRIES": int(os.getenv("CH_MAX_RETRIES", "3")),
    "CH_RETRY_DELAY_SECONDS": int(os.getenv("CH_RETRY_DELAY_SECONDS", "1")),
    # Connection pool settings
    "CH_POOL_SIZE": int(os.getenv("CH_POOL_SIZE", "10")),
    "CH_CONNECT_TIMEOUT": int(os.getenv("CH_CONNECT_TIMEOUT", "10")),
    "CH_SEND_TIMEOUT": int(os.getenv("CH_SEND_TIMEOUT", "300")),
    "CH_RECEIVE_TIMEOUT": int(os.getenv("CH_RECEIVE_TIMEOUT", "300")),
    # Dedicated SOS/read-replica profiles may lock readonly=1 and every
    # resource ceiling server-side. Such profiles reject per-query setting
    # overrides, so the client must transmit none.
    "CH_SERVER_ENFORCED_READONLY": os.getenv(
        "CH_SERVER_ENFORCED_READONLY", "false"
    ).lower()
    in ("true", "1", "yes"),
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
# Add static files directory for development
STATICFILES_DIRS = ["/app/backend/staticfiles"]
STATIC_ROOT = "/app/backend/static"

# Configure WhiteNoise for static file serving
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Enable static file serving in staging/production
if os.getenv("ENV_TYPE") in ["staging", "prod"]:
    # Use WhiteNoise for production static file serving
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# This ensures Django serves static files in development
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ("accounts.authentication.APIKeyAuthentication",),
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "DEFAULT_PARSER_CLASSES": (
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
    ),
    "DEFAULT_PAGINATION_CLASS": "tfc.utils.pagination.ExtendedPageNumberPagination",
    "PAGE_SIZE": 10,  # Number of objects per page.
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    "EXCEPTION_HANDLER": "accounts.authentication.custom_exception_handler",
}

# SECRET_KEY — sentinel default so the app starts for first-run self-host;
# non-local environments using the default bail out loudly.
_DEFAULT_SECRET_KEY = "django-insecure-<default-SECRET_KEY-replace-in-production>"
SECRET_KEY = os.getenv("SECRET_KEY") or _DEFAULT_SECRET_KEY

if not _IS_LOCAL and SECRET_KEY == _DEFAULT_SECRET_KEY:
    import sys as _sys

    _sys.stderr.write(
        "[FATAL] SECRET_KEY is set to the default value in a non-local "
        "environment. Generate a key and set SECRET_KEY env var. "
        "See: https://docs.djangoproject.com/en/stable/ref/settings/#secret-key\n"
    )
    _sys.exit(1)

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        days=14
    ),  # or the time frame you want your token to be active
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1 * 30),  # or the time frame you prefer
    "ROTATE_REFRESH_TOKENS": False,  # If True, the refresh token will be rotated each time
    "BLACKLIST_AFTER_ROTATION": False,  # If True, the refresh token will be blacklisted after being rotated
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
}

AUTH_USER_MODEL = "accounts.User"

ANYMAIL = {
    # (exact settings here depend on your ESP...)
    "MAILGUN_API_KEY": os.getenv("MAILGUN_API_KEY"),
    "MAILGUN_SENDER_DOMAIN": os.getenv(
        "MAILGUN_SENDER_DOMAIN"
    ),  # your Mailgun domain, if needed
}
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "anymail.backends.mailgun.EmailBackend"
    if os.getenv("MAILGUN_API_KEY")
    else "django.core.mail.backends.console.EmailBackend",
)
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL"
)  # if you don't already have this in settings
SERVER_EMAIL = os.getenv("SERVER_EMAIL")  # ditto (default from-email for Django errors)

APP_URL = os.getenv("APP_URL")

# ── Billing ───────────────────────────────────────────────────
# Ships only with the cloud overlay, which is the future-agi/ee repo checked
# out at futureagi/ee/cloud/. Absent on OSS/EE — BillingConfig falls open to
# empty defaults there (and fails closed on cloud).
BILLING_CONFIG_PATH = os.environ.get(
    "BILLING_CONFIG_PATH",
    os.path.join(BASE_DIR, "..", "ee", "cloud", "billing.yaml"),
)

# EE license key (self-hosted only, JWT RS256)
EE_LICENSE_KEY = os.environ.get("EE_LICENSE_KEY", "")
EE_LICENSE_PUBLIC_KEY = os.environ.get("EE_LICENSE_PUBLIC_KEY", "").replace("\\n", "\n")
EE_LICENSE_PUBLIC_KEYS = os.environ.get("EE_LICENSE_PUBLIC_KEYS", "")
EE_LICENSE_CLOCK_SKEW_SECONDS = os.environ.get("EE_LICENSE_CLOCK_SKEW_SECONDS", "300")
EE_LICENSE_KEY_ID = os.environ.get("EE_LICENSE_KEY_ID", "default")
EE_LICENSE_PRIVATE_KEY = os.environ.get("EE_LICENSE_PRIVATE_KEY", "").replace(
    "\\n", "\n"
)

# Cloud API key for managed AI features (self-hosted → cloud Agentcc gateway)
FUTUREAGI_CLOUD_API_KEY = os.environ.get("FUTUREAGI_CLOUD_API_KEY", "")

# Activation signing key (cloud control plane uses this to mint service tokens)
ACTIVATION_PRIVATE_KEY = os.environ.get("ACTIVATION_PRIVATE_KEY", "").replace(
    "\\n", "\n"
)
ACTIVATION_KEY_ID = os.environ.get("ACTIVATION_KEY_ID", "default")
ACTIVATION_SIGNING_SERVICE_URL = os.environ.get("ACTIVATION_SIGNING_SERVICE_URL", "")
ACTIVATION_TOKEN_ISSUER = os.environ.get(
    "ACTIVATION_TOKEN_ISSUER", "https://licenses.futureagi.com"
)
ACTIVATION_TOKEN_AUDIENCE = os.environ.get(
    "ACTIVATION_TOKEN_AUDIENCE", "futureagi-agentcc-gateway"
)
ACTIVATION_TOKEN_TYPE = os.environ.get(
    "ACTIVATION_TOKEN_TYPE", "futureagi-managed-service-token"
)
ACTIVATION_TOKEN_TTL_SECONDS = os.environ.get("ACTIVATION_TOKEN_TTL_SECONDS", "3600")
ACTIVATION_RUNTIME_STATE_REQUIRED = os.environ.get(
    "ACTIVATION_RUNTIME_STATE_REQUIRED", "true"
).lower() in ("1", "true", "yes")
FUTUREAGI_CLOUD_GATEWAY_URL = os.environ.get(
    "FUTUREAGI_CLOUD_GATEWAY_URL", "https://gateway.futureagi.com"
)

# Internal Agentcc gateway (cloud deployment only)
INTERNAL_GATEWAY_URL = os.environ.get(
    "INTERNAL_GATEWAY_URL", "http://agentcc-internal:8090"
)
INTERNAL_GATEWAY_KEY = os.environ.get("INTERNAL_GATEWAY_KEY", "")

# ── Multi-Region ──────────────────────────────────────────────
REGION = os.environ.get("REGION", "us")
CLOUD_DEPLOYMENT = os.environ.get("CLOUD_DEPLOYMENT", "")
CLOUD_DEPLOYMENT_SECRET = os.environ.get("CLOUD_DEPLOYMENT_SECRET", "")
AVAILABLE_REGIONS = os.environ.get("AVAILABLE_REGIONS", "")

# Celery Configuration Options

CELERY_BROKER_URL = os.getenv(
    "CELERY_BROKER_URL", "amqp://user:password@rabbitmq:5672//"
)
CELERY_RESULT_BACKEND = "django-db"  # If you want to use Django's ORM
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_DEFAULT_RETRY_DELAY = 300  # Retry in 5 minutes.
CELERY_TASK_MAX_RETRIES = 0  # Maximum retry attempts.
CELERY_TASK_PUBLISH_RETRY = False
CELERY_TASK_ACKS_LATE = True  # Acknowledge tasks only after successful execution
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_DISABLE_RATE_LIMITS = True
CELERY_WORKER_MAX_TASKS_PER_CHILD = None  # No limit

CELERY_IMPORTS = [
    "model_hub.tasks",
    "agentcc.tasks",
]

# Temporal Test Execution Configuration
# When enabled, test executions use Temporal workflows instead of Celery tasks
TEMPORAL_TEST_EXECUTION_ENABLED = os.getenv(
    "TEMPORAL_TEST_EXECUTION_ENABLED", "false"
).lower() in ("true", "1", "yes")

# Hosted simulation runner (plan §9): when enabled, eligible runs are dispatched
# to the simulation-runner worker which executes the released SDK, instead of the
# native in-backend simulation path. Default off — no regression.
HOSTED_RUNNER_ENABLED = os.getenv("HOSTED_RUNNER_ENABLED", "false").lower() in (
    "true",
    "1",
    "yes",
)

# Route VOICE runs to the hosted simulation runner too (default off: voice stays
# on the native path). Requires HOSTED_RUNNER_ENABLED.
HOSTED_RUNNER_VOICE_ENABLED = os.getenv(
    "HOSTED_RUNNER_VOICE_ENABLED", "false"
).lower() in ("true", "1", "yes")

# Structured logging configuration with django-structlog
# This provides:
# - JSON output in production, colored console in development
# - Automatic request_id (correlation ID) on every log
# - user_id, user_email, organization_id, workspace_id after authentication
# - OpenTelemetry trace_id/span_id for distributed tracing
# - Process ID and thread ID for debugging
LOGGING = get_logging_config(str(BASE_DIR))

# Airbyte configurations
AIRBYTE_HOST = os.getenv("AIRBYTE_HOST")
AIRBYTE_PORT = os.getenv("AIRBYTE_PORT")
AIRBYTE_API_URL = f"http://{AIRBYTE_HOST}:{AIRBYTE_PORT}/api/v1"
SLACK_WEBHOOK_CHANNEL = os.getenv("SLACK_WEBHOOK_CHANNEL", "")
DEPLOYMENT_TELEMETRY_SLACK_WEBHOOK = os.getenv(
    "DEPLOYMENT_TELEMETRY_SLACK_WEBHOOK",
    SLACK_WEBHOOK_CHANNEL,
)
ERROR_LOGS_WEBHOOK = os.getenv("ERROR_LOGS_WEBHOOK", "")

AIRBYTE_HEADERS = {
    "Content-Type": "application/json",
    "Authorization": "Basic YWlyYnl0ZTpwYXNzd29yZA==",
}


LLM_KEYS = {
    "OPENAI": os.getenv("OPENAI_API_KEY"),
    "ANTHROPIC": os.getenv("ANTHROPIC_API_KEY"),
    "OPENROUTER": os.getenv("OPENROUTER_API_KEY"),
}

DEEPGRAM_API_KEY = os.getenv("DEEPGRAM_API_KEY", "")
CARTESIA_API_KEY = os.getenv("CARTESIA_API_KEY", "")

AWS = {
    "AWS_ACCESS_KEY_ID": os.getenv("AWS_ACCESS_KEY_ID"),
    "AWS_SECRET_ACCESS_KEY": os.getenv("AWS_SECRET_ACCESS_KEY"),
    "AWS_DEFAULT_REGION": os.getenv("AWS_DEFAULT_REGION"),
    "S3_FOR_DATA": os.getenv("S3_FOR_DATA"),
    "AWS_BUCKET_NAME": os.getenv("AWS_BUCKET_NAME"),
    "BEDROCK_REGION": os.getenv("BEDROCK_REGION"),
}

HUGGINGFACE_API_TOKEN = os.getenv("HUGGINGFACE_API_TOKEN", "")
HUGGINGFACE_API_TOKEN_1 = os.getenv("HUGGINGFACE_API_TOKEN_1", "")
HUGGINGFACE_API_TOKEN_2 = os.getenv("HUGGINGFACE_API_TOKEN_2", "")
HUBSPOT_URL = "https://api.hubapi.com/crm/v3/objects/contacts"
HUBSPOT_UPDATE_URL = (
    "https://api.hubapi.com/crm/v3/objects/contacts/{}?idProperty=email"
)
HUBSPOT_API_TOKEN = os.getenv("HUBSPOT_API_TOKEN", "")

VAPI_INDIAN_PHONE_NUMBER_ID = os.getenv(
    "VAPI_INDIAN_PHONE_NUMBER_ID", "6fe53c53-99cc-4090-bf65-6ea4d8267a95"
)

# VAPI Webhook Configuration
# Single system phone number for all outbound calls (webhook-based architecture)
VAPI_PHONE_NUMBER_ID = os.getenv("VAPI_PHONE_NUMBER_ID", "")
# HMAC secret for webhook signature verification (configure in VAPI dashboard)
VAPI_WEBHOOK_SECRET = os.getenv("VAPI_WEBHOOK_SECRET", "")

# Internal API authentication (shared secret for service-to-service calls)
INTERNAL_API_SECRET = os.getenv("INTERNAL_API_SECRET", "")

# LiveKit credentials (used for webhook verification and API calls)
LIVEKIT_URL = os.getenv("LIVEKIT_URL", "")
LIVEKIT_API_KEY = os.getenv("LIVEKIT_API_KEY", "")
LIVEKIT_API_SECRET = os.getenv("LIVEKIT_API_SECRET", "")

# Fallback concurrency when a LiveKit agent's credentials don't specify one.
# Kept low by default to protect LiveKit quota; override per-agent via the
# agent-definition API or globally via this env var.
DEFAULT_LIVEKIT_MAX_CONCURRENCY = int(os.getenv("DEFAULT_LIVEKIT_MAX_CONCURRENCY", "2"))

# Third-party provider URLs for WebRTC bridge connectors
VAPI_API_URL = os.getenv("VAPI_API_URL", "https://api.vapi.ai/call")
RETELL_API_URL = os.getenv(
    "RETELL_API_URL", "https://api.retellai.com/v2/create-web-call"
)
RETELL_LIVEKIT_URL = os.getenv(
    "RETELL_LIVEKIT_URL", "wss://retell-ai-4ihahnq7.livekit.cloud"
)

# Stripe
STRIPE_REDIRECT_DOMAIN = os.getenv("STRIPE_REDIRECT_DOMAIN")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
BUSINESS_MONTHLY_STRIPE_PRICE_ID = os.getenv("BUSINESS_MONTHLY_STRIPE_PRICE_ID")
BUSINESS_YEARLY_STRIPE_PRICE_ID = os.getenv("BUSINESS_YEARLY_STRIPE_PRICE_ID")

STRIPE_LIVE = bool(STRIPE_SECRET_KEY and STRIPE_SECRET_KEY.startswith("sk_live"))

# Signing secret for the billing webhook endpoint. Keyed off the same
# live/test signal StripeService._is_live() uses, so the secret can never
# disagree with the API key the events were generated against.
STRIPE_WEBHOOK_SECRET = os.getenv(
    "WEBHOOK_SECRET_LIVE" if STRIPE_LIVE else "WEBHOOK_SECRET_TEST", ""
)

BUSINESS_MONTHLY_STRIPE_PRICE_IDS_ALL = [
    x
    for x in (os.getenv("BUSINESS_MONTHLY_STRIPE_PRICE_IDS_ALL") or "").split(",")
    if x
]
if (
    BUSINESS_MONTHLY_STRIPE_PRICE_ID
    and BUSINESS_MONTHLY_STRIPE_PRICE_ID not in BUSINESS_MONTHLY_STRIPE_PRICE_IDS_ALL
):
    BUSINESS_MONTHLY_STRIPE_PRICE_IDS_ALL.append(BUSINESS_MONTHLY_STRIPE_PRICE_ID)

BUSINESS_YEARLY_STRIPE_PRICE_IDS_ALL = [
    x for x in (os.getenv("BUSINESS_YEARLY_STRIPE_PRICE_IDS_ALL") or "").split(",") if x
]
if (
    BUSINESS_YEARLY_STRIPE_PRICE_ID
    and BUSINESS_YEARLY_STRIPE_PRICE_ID not in BUSINESS_YEARLY_STRIPE_PRICE_IDS_ALL
):
    BUSINESS_YEARLY_STRIPE_PRICE_IDS_ALL.append(BUSINESS_YEARLY_STRIPE_PRICE_ID)

# ── URL & OAuth — all from env vars, no ENV_TYPE branching ───
# ENV_TYPE / _IS_LOCAL are computed once at the top of the file; aliased here
# for existing callers that read the lowercase names.
env_type = ENV_TYPE
_is_local = _IS_LOCAL
_ssl = "http://" if _is_local else "https://"
ssl = _ssl  # exported — used by accounts.utils, accounts.views.workspace_management

BASE_URL = os.getenv(
    "BASE_URL", "http://localhost:8000" if _is_local else "https://api.futureagi.com"
)
WEBSOCKET_ENDPOINT = os.getenv("WEBSOCKET_ENDPOINT", f"{BASE_URL}/call-websocket/")
MINIO_URL = os.getenv(
    "MINIO_URL", f"{_ssl}localhost:9005" if _is_local else f"{_ssl}{APP_URL}:9005"
)
UPLOAD_BUCKET_NAME = os.getenv(
    "UPLOAD_BUCKET_NAME", "fi-content-dev" if _is_local else "fi-content"
)

# Storage backend: "s3" (default/US), "gcs" (EU via S3-interop HMAC keys),
# or "minio" (self-hosted OSS local stack)
STORAGE_BACKEND = os.getenv("STORAGE_BACKEND", "s3")
GCS_HMAC_ACCESS_KEY = os.getenv("GCS_HMAC_ACCESS_KEY", "")
GCS_HMAC_SECRET_KEY = os.getenv("GCS_HMAC_SECRET_KEY", "")

AUTH0_CLIENT_ID = os.getenv("AUTH0_CLIENT_ID", "")
AUTH0_CLIENT_SECRET = os.getenv("AUTH0_CLIENT_SECRET", "")
GITHUB_CLIENT_ID = os.getenv("GITHUB_CLIENT_ID", "")
GITHUB_CLIENT_SECRET = os.getenv("GITHUB_CLIENT_SECRET", "")
MICROSOFT_CLIENT_ID = os.getenv("MICROSOFT_CLIENT_ID", "")
MICROSOFT_CLIENT_SECRET = os.getenv("MICROSOFT_CLIENT_SECRET", "")

sentry_sdk_enabled = (
    os.getenv("SENTRY_ENABLED", "" if _is_local else "true").lower() == "true"
)

# ── CSRF trusted origins (built dynamically from BASE_URL / APP_URL) ──
CSRF_TRUSTED_ORIGINS = ["http://localhost:5173", "http://localhost:3031"]
if APP_URL:
    CSRF_TRUSTED_ORIGINS += [f"https://{APP_URL}", f"http://{APP_URL}"]
if BASE_URL:
    CSRF_TRUSTED_ORIGINS += [BASE_URL, BASE_URL.replace("https://", "http://")]
# Extra origins (comma-separated) for additional subdomains or custom deployments
_extra_csrf = os.getenv("EXTRA_CSRF_ORIGINS", "")
if _extra_csrf:
    CSRF_TRUSTED_ORIGINS += [o.strip() for o in _extra_csrf.split(",") if o.strip()]

AUTH0_CALLBACK_URL = f"{BASE_URL}/saml2_auth/auth/callback/"
GITHUB_CALLBACK_URL = f"{BASE_URL}/saml2_auth/github/callback/"
MICROSOFT_CALLBACK_URL = f"{BASE_URL}/saml2_auth/microsoft/callback/"
get_assertion_url = f"{BASE_URL}/saml2_auth/acs/"
default_next_url = f"{_ssl}{APP_URL}/dashboard/develop"
get_started_url = f"{_ssl}{APP_URL}/dashboard/get-started"
default_error_next_url = f"{_ssl}{APP_URL}/auth/jwt/login?denied=true"
get_entity_id = f"{_ssl}{APP_URL}"

# APP_URL is a bare host; each region is its own deployment with its own value.
APP_BASE_URL = f"{_ssl}{APP_URL}" if APP_URL else ""

get_name_id_format = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
AUTH0_DOMAIN = "accounts.google.com/o/oauth2"
AUTH0_ALGORITHM = "RS256"
GITHUB_API_ENDPOINT = "https://api.github.com"
GITHUB_OAUTH_URL = "https://github.com/login/oauth"
GOOGLE_USERINFO_API = "https://www.googleapis.com/oauth2/v1/userinfo"
MICROSOFT_OAUTH_URL = "https://login.microsoftonline.com/common/oauth2/v2.0"
MICROSOFT_GRAPH_API = "https://graph.microsoft.com/v1.0"

RECAPTCHA_SECRET_KEY = os.getenv("RECAPTCHA_SECRET_KEY", "")
RECAPTCHA_ENABLED = os.getenv(
    "RECAPTCHA_ENABLED",
    "false" if env_type in {"local", "development"} else "true",
).lower() in ("true", "1", "yes")

# Integration encryption key (Fernet) for storing external platform credentials
INTEGRATION_ENCRYPTION_KEY = os.getenv("INTEGRATION_ENCRYPTION_KEY", "")
if not INTEGRATION_ENCRYPTION_KEY and env_type == "local":
    # Generate a throwaway key for local dev so the app starts without config.
    # Data encrypted with this key is lost on restart — production MUST set
    # INTEGRATION_ENCRYPTION_KEY as an env var.
    import base64
    import secrets as _secrets

    INTEGRATION_ENCRYPTION_KEY = base64.urlsafe_b64encode(
        _secrets.token_bytes(32)
    ).decode()
ENABLE_INTEGRATIONS = os.getenv("ENABLE_INTEGRATIONS", "false").lower() == "true"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_rabbitmq.core.RabbitmqChannelLayer",
        "CONFIG": {
            "host": CELERY_BROKER_URL,
            "ssl_context": None,
            "expiry": 300,
            "local_capacity": 500,
            "local_expiry": 300,
            "remote_capacity": 500,
        },
    },
}
REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")


if os.getenv("DJANGO_CACHE_BACKEND") == "locmem":
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "futureagi-local-cache",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": os.getenv("REDIS_CACHE_URL", f"{REDIS_URL}"),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "SOCKET_CONNECT_TIMEOUT": REDIS_CACHE_SOCKET_CONNECT_TIMEOUT_SECONDS,
                "SOCKET_TIMEOUT": REDIS_CACHE_SOCKET_TIMEOUT_SECONDS,
            },
            "KEY_PREFIX": "futureagi",
            "TIMEOUT": 600,  # Default timeout in seconds (10 minutes)
        }
    }

# Authentication Security Settings
MAX_LOGIN_ATTEMPTS = 10  # Maximum failed login attempts before account lockout
ACCOUNT_LOCKOUT_DURATION = 1800  # 30 minutes in seconds
FAILED_ATTEMPTS_TIMEOUT = 3600  # 1 hour in seconds
MAX_LOGIN_ATTEMPTS_PER_HOUR = 10  # Rate limiting per IP
IP_BLOCK_DURATION = 3600  # 1 hour in seconds

DATA_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 1024  # 1GB in bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 1024  # 1GB in bytes
DATA_UPLOAD_MAX_NUMBER_FILES = 1000


init_sentry(component="django")

# gRPC-framework settings
GRPC_FRAMEWORK = {
    "ROOT_HANDLERS_HOOK": "tracer.handlers.grpc_handlers",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "accounts.authentication.APIKeyAuthentication",
    ],
    "SERVER_OPTIONS": [
        ("grpc.max_receive_message_length", 100 * 1024 * 1024),  # 100MB
        ("grpc.max_send_message_length", 100 * 1024 * 1024),  # 100MB
    ],
}

# WebAuthn / Passkeys
WEBAUTHN_RP_ID = os.getenv("WEBAUTHN_RP_ID", "localhost")
WEBAUTHN_RP_NAME = os.getenv("WEBAUTHN_RP_NAME", "FutureAGI")
WEBAUTHN_ORIGIN = os.getenv("WEBAUTHN_ORIGIN", "http://localhost:3031")

# 2FA challenge token TTLs (seconds)
TWO_FACTOR_CHALLENGE_TTL = 300  # 5 minutes
WEBAUTHN_CHALLENGE_TTL = 120  # 2 minutes

# ─── ClickHouse 25.3 (v2) span store ────────────────────────────────────────
# The new spans cluster (typed Maps + typed JSON; PLAN_V2_NO_CDC). Falls back
# to the legacy CLICKHOUSE dict above for connection details if not set
# explicitly — see tracer/services/clickhouse/v2/__init__.py:get_v2_config().
CLICKHOUSE_V2 = {
    "CH25_HOST": os.getenv("CH25_HOST"),
    "CH25_HTTP_PORT": os.getenv("CH25_HTTP_PORT"),
    "CH25_TCP_PORT": os.getenv("CH25_TCP_PORT"),
    "CH25_USER": os.getenv("CH25_USER"),
    "CH25_PASSWORD": os.getenv("CH25_PASSWORD"),
    "CH25_DATABASE": os.getenv("CH25_DATABASE"),
    # ``None`` means the v2-specific flag was not configured and lets
    # ``get_v2_config`` inherit the legacy single-cluster setting.  A concrete
    # False must be reserved for an explicit CH25 override; defaulting to False
    # here silently disabled inheritance for server-locked read profiles.
    "CH25_SERVER_ENFORCED_READONLY": (
        None
        if os.getenv("CH25_SERVER_ENFORCED_READONLY") is None
        else os.getenv("CH25_SERVER_ENFORCED_READONLY", "").lower()
        in ("true", "1", "yes")
    ),
    # ─── Per-query-type routing for the shadow-mode rollout ──────────────────
    # Comma-separated query type names. See tracer/services/clickhouse/v2/shadow.py
    # for RoutingMode definitions. Anything not listed defaults to V1_ONLY.
    "QUERY_TYPES_V2_PRIMARY": os.getenv("CH25_QUERY_TYPES_V2_PRIMARY", ""),
    "QUERY_TYPES_V2_ONLY": os.getenv("CH25_QUERY_TYPES_V2_ONLY", ""),
    "QUERY_TYPES_SHADOW": os.getenv("CH25_QUERY_TYPES_SHADOW", ""),
    "QUERY_TYPES_DISABLED": os.getenv("CH25_QUERY_TYPES_DISABLED", ""),
}

# ``off`` is the production-safe default. ``shadow`` is fail-open observation;
# ``read`` can affect public results only in an explicitly acknowledged DEV
# deployment. The runtime helper repeats this guard so an override cannot turn
# a production process into a catalog reader after settings import.
SPAN_ATTRIBUTE_CATALOG_READ_MODE = (
    os.getenv("SPAN_ATTRIBUTE_CATALOG_READ_MODE", "off").strip().lower()
)
SPAN_ATTRIBUTE_CATALOG_DATABASE = os.getenv(
    "SPAN_ATTRIBUTE_CATALOG_DATABASE", ""
).strip()
SPAN_ATTRIBUTE_CATALOG_DEV_READ_ACK = os.getenv(
    "SPAN_ATTRIBUTE_CATALOG_DEV_READ_ACK", ""
).strip()
_span_attribute_catalog_dev_snapshot_raw = (
    os.getenv("SPAN_ATTRIBUTE_CATALOG_DEV_SNAPSHOT_ENABLED", "false").strip().lower()
)
if _span_attribute_catalog_dev_snapshot_raw not in {"true", "false"}:
    raise ValueError(
        "SPAN_ATTRIBUTE_CATALOG_DEV_SNAPSHOT_ENABLED must be true or false"
    )
SPAN_ATTRIBUTE_CATALOG_DEV_SNAPSHOT_ENABLED = (
    _span_attribute_catalog_dev_snapshot_raw == "true"
)
_span_attribute_catalog_is_dev_deployment = ENV_TYPE in {
    "dev",
    "development",
} or (ENV_TYPE == "staging" and CLOUD_DEPLOYMENT == "DEV")
_span_attribute_catalog_handoff_start_raw = os.getenv(
    "SPAN_ATTRIBUTE_CATALOG_HANDOFF_START", ""
).strip()
_span_attribute_catalog_handoff_end_raw = os.getenv(
    "SPAN_ATTRIBUTE_CATALOG_HANDOFF_END", ""
).strip()


def _span_attribute_catalog_bound(raw_value):
    if not raw_value:
        return None
    try:
        return datetime.fromisoformat(raw_value.replace("Z", "+00:00"))
    except ValueError:
        return None


SPAN_ATTRIBUTE_CATALOG_HANDOFF_START = _span_attribute_catalog_bound(
    _span_attribute_catalog_handoff_start_raw
)
SPAN_ATTRIBUTE_CATALOG_HANDOFF_END = _span_attribute_catalog_bound(
    _span_attribute_catalog_handoff_end_raw
)
SPAN_ATTRIBUTE_CATALOG_CH_HOST = os.getenv("SPAN_ATTRIBUTE_CATALOG_CH_HOST", "").strip()
_span_attribute_catalog_ch_port_raw = os.getenv(
    "SPAN_ATTRIBUTE_CATALOG_CH_PORT", ""
).strip()
SPAN_ATTRIBUTE_CATALOG_CH_DATABASE = os.getenv(
    "SPAN_ATTRIBUTE_CATALOG_CH_DATABASE", ""
).strip()
SPAN_ATTRIBUTE_CATALOG_CH_USER = os.getenv("SPAN_ATTRIBUTE_CATALOG_CH_USER", "").strip()
# Do not strip or interpolate secrets. Runtime connection construction consumes
# this value directly and its redacted config object excludes it from repr().
SPAN_ATTRIBUTE_CATALOG_CH_PASSWORD = os.getenv("SPAN_ATTRIBUTE_CATALOG_CH_PASSWORD", "")
try:
    SPAN_ATTRIBUTE_CATALOG_CH_PORT = (
        int(_span_attribute_catalog_ch_port_raw)
        if _span_attribute_catalog_ch_port_raw
        else 0
    )
except ValueError:
    SPAN_ATTRIBUTE_CATALOG_CH_PORT = 0
if SPAN_ATTRIBUTE_CATALOG_READ_MODE not in {"off", "shadow", "read"}:
    raise ValueError("SPAN_ATTRIBUTE_CATALOG_READ_MODE must be off, shadow, or read")
try:
    SPAN_ATTRIBUTE_CATALOG_EPOCH = int(os.getenv("SPAN_ATTRIBUTE_CATALOG_EPOCH", "0"))
except ValueError as exc:
    raise ValueError("SPAN_ATTRIBUTE_CATALOG_EPOCH must be a UInt16") from exc
if not 0 <= SPAN_ATTRIBUTE_CATALOG_EPOCH <= 65_535:
    raise ValueError("SPAN_ATTRIBUTE_CATALOG_EPOCH must be a UInt16")
if SPAN_ATTRIBUTE_CATALOG_DEV_SNAPSHOT_ENABLED and (
    SPAN_ATTRIBUTE_CATALOG_READ_MODE != "read"
    or not _span_attribute_catalog_is_dev_deployment
    or SPAN_ATTRIBUTE_CATALOG_DEV_READ_ACK
    != "I_ACKNOWLEDGE_DEV_ONLY_ATTRIBUTE_CATALOG_READS"
):
    raise ValueError(
        "span attribute catalog DEV snapshot requires acknowledged DEV read mode"
    )
if SPAN_ATTRIBUTE_CATALOG_READ_MODE == "read":
    if (
        not _span_attribute_catalog_is_dev_deployment
        or SPAN_ATTRIBUTE_CATALOG_DEV_READ_ACK
        != "I_ACKNOWLEDGE_DEV_ONLY_ATTRIBUTE_CATALOG_READS"
    ):
        raise ValueError(
            "span attribute catalog public reads require DEV and explicit "
            "acknowledgement"
        )
    if not 1 <= SPAN_ATTRIBUTE_CATALOG_EPOCH <= 65_535:
        raise ValueError(
            "span attribute catalog public reads require an epoch from 1 to 65535"
        )
    if not SPAN_ATTRIBUTE_CATALOG_DEV_SNAPSHOT_ENABLED:
        raise ValueError(
            "span attribute catalog public reads require the pinned DEV snapshot"
        )
    if (
        SPAN_ATTRIBUTE_CATALOG_HANDOFF_START is None
        or SPAN_ATTRIBUTE_CATALOG_HANDOFF_END is None
        or SPAN_ATTRIBUTE_CATALOG_HANDOFF_START.tzinfo is None
        or SPAN_ATTRIBUTE_CATALOG_HANDOFF_END.tzinfo is None
        or SPAN_ATTRIBUTE_CATALOG_HANDOFF_START.utcoffset() != timedelta(0)
        or SPAN_ATTRIBUTE_CATALOG_HANDOFF_END.utcoffset() != timedelta(0)
        or any(
            (
                bound.minute,
                bound.second,
                bound.microsecond,
            )
            != (0, 0, 0)
            for bound in (
                SPAN_ATTRIBUTE_CATALOG_HANDOFF_START,
                SPAN_ATTRIBUTE_CATALOG_HANDOFF_END,
            )
        )
        or SPAN_ATTRIBUTE_CATALOG_HANDOFF_START >= SPAN_ATTRIBUTE_CATALOG_HANDOFF_END
    ):
        raise ValueError(
            "span attribute catalog public reads require aligned increasing UTC "
            "handoff bounds"
        )
    if (
        not SPAN_ATTRIBUTE_CATALOG_CH_DATABASE
        or len(SPAN_ATTRIBUTE_CATALOG_CH_DATABASE.encode("utf-8")) > 128
        or re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", SPAN_ATTRIBUTE_CATALOG_CH_DATABASE)
        is None
    ):
        raise ValueError(
            "span attribute catalog public reads require a safe dedicated "
            "catalog database"
        )
    if (
        SPAN_ATTRIBUTE_CATALOG_DATABASE != SPAN_ATTRIBUTE_CATALOG_CH_DATABASE
        or "dev" not in SPAN_ATTRIBUTE_CATALOG_CH_DATABASE.lower()
        or SPAN_ATTRIBUTE_CATALOG_CH_DATABASE.lower()
        in {"default", "system", "information_schema", "futureagi"}
    ):
        raise ValueError(
            "span attribute catalog public reads require the same isolated "
            "development catalog database for qualification and connection"
        )
    if (
        not SPAN_ATTRIBUTE_CATALOG_CH_HOST
        or not 1 <= SPAN_ATTRIBUTE_CATALOG_CH_PORT <= 65_535
        or not SPAN_ATTRIBUTE_CATALOG_CH_USER
        or not SPAN_ATTRIBUTE_CATALOG_CH_PASSWORD
    ):
        raise ValueError(
            "span attribute catalog public reads require complete dedicated "
            "ClickHouse connection settings"
        )
    _span_attribute_catalog_source_users = {
        str(CLICKHOUSE_V2.get("CH25_USER") or "").strip(),
        str(CLICKHOUSE.get("CH_USERNAME") or "").strip(),
    } - {""}
    if SPAN_ATTRIBUTE_CATALOG_CH_USER in _span_attribute_catalog_source_users:
        raise ValueError(
            "span attribute catalog public reads require a dedicated ClickHouse "
            "read identity distinct from source application users"
        )

# Unified property-definition catalog. This is a separate read-only path from
# the frozen span-attribute snapshot above. It resolves its immutable
# epoch/revision from the activation ledger and therefore has no process-wide
# epoch/window setting. Production reads remain off by default and require a
# separate, exact acknowledgement; this admission policy does not enable any
# writer, backfill, schema, or reconciliation path.
PROPERTY_CATALOG_DEV_READ_ACKNOWLEDGEMENT = (
    "I_ACKNOWLEDGE_DEV_ONLY_UNIFIED_PROPERTY_CATALOG"
)
PROPERTY_CATALOG_PROD_READ_ACKNOWLEDGEMENT = (
    "I_ACKNOWLEDGE_PROD_READ_ONLY_UNIFIED_PROPERTY_CATALOG"
)
PROPERTY_CATALOG_MAX_READ_WORKSPACES = 256
PROPERTY_CATALOG_PROD_WORKSPACE_SCOPE_MODES = frozenset({"allowlist", "all"})
PROPERTY_CATALOG_PRODUCTION_DATABASE_ENV = "PROPERTY_CATALOG_PRODUCTION_DATABASE"
PROPERTY_CATALOG_DEFAULT_PRODUCTION_DATABASE = "property_catalog"
_PROPERTY_CATALOG_DATABASE_IDENTIFIER = re.compile(r"\A[a-z][a-z0-9_]*\Z")
_PROPERTY_CATALOG_RESERVED_DATABASES = {
    "default",
    "futureagi",
    "information_schema",
    "system",
}


def property_catalog_read_deployment(
    environment_type: object,
    cloud_deployment: object,
) -> str:
    """Classify one explicitly supported catalog read deployment."""

    normalized_environment = (
        environment_type.strip().lower() if isinstance(environment_type, str) else ""
    )
    normalized_cloud = (
        cloud_deployment.strip().upper() if isinstance(cloud_deployment, str) else ""
    )
    if normalized_environment in {"dev", "development"} or (
        normalized_environment == "staging" and normalized_cloud == "DEV"
    ):
        return "dev"
    # ``ENV_TYPE`` is documented and deployed as ``prod``. Keep the longer
    # spelling as a backwards-compatible alias, but never classify either as
    # production when the cloud deployment is explicitly DEV.
    if normalized_environment in {"prod", "production"} and normalized_cloud != "DEV":
        return "prod"
    raise ValueError(
        "unified property catalog reads require an explicitly supported DEV "
        "or production deployment"
    )


def validate_property_catalog_database(
    database: object,
    *,
    deployment: str | None = None,
) -> str:
    """Validate a safe catalog identifier and configurable deployment binding."""

    if (
        not isinstance(database, str)
        or not database
        or len(database.encode("utf-8")) > 128
        or _PROPERTY_CATALOG_DATABASE_IDENTIFIER.fullmatch(database) is None
    ):
        raise ValueError(
            "property catalog database must be a safe ClickHouse identifier"
        )
    if database in _PROPERTY_CATALOG_RESERVED_DATABASES:
        raise ValueError(
            "property catalog database must be isolated from source databases"
        )
    if deployment not in {None, "dev", "prod"}:
        raise ValueError("unsupported property catalog deployment")
    production_database = os.getenv(
        PROPERTY_CATALOG_PRODUCTION_DATABASE_ENV,
        PROPERTY_CATALOG_DEFAULT_PRODUCTION_DATABASE,
    ).strip()
    if (
        not production_database
        or len(production_database.encode("utf-8")) > 128
        or _PROPERTY_CATALOG_DATABASE_IDENTIFIER.fullmatch(production_database) is None
        or production_database in _PROPERTY_CATALOG_RESERVED_DATABASES
    ):
        raise ValueError(
            "configured production property catalog database must be a safe "
            "isolated ClickHouse identifier"
        )
    if (deployment == "prod" and database != production_database) or (
        deployment == "dev" and database == production_database
    ):
        raise ValueError(
            "property catalog database namespace does not match the deployment"
        )
    return database


def validate_property_catalog_read_connection(
    *,
    host: object,
    port: object,
    database: object,
    api_read_user: object,
    password: object,
    source_users: object,
    deployment: str,
) -> None:
    """Validate the bounded, dedicated API connection for one deployment."""

    validate_property_catalog_database(database, deployment=deployment)
    if (
        not isinstance(host, str)
        or not host.strip()
        or type(port) is not int
        or not 1 <= port <= 65_535
        or not isinstance(api_read_user, str)
        or not api_read_user.strip()
        or not isinstance(password, str)
        or not password
    ):
        raise ValueError(
            "complete dedicated property catalog ClickHouse settings are required"
        )
    try:
        normalized_source_users = {
            str(user).strip() for user in source_users if str(user).strip()
        }
    except TypeError as exc:
        raise ValueError("property catalog source users must be iterable") from exc
    if api_read_user.strip() in normalized_source_users:
        raise ValueError(
            "property catalog reads require a dedicated API identity distinct "
            "from source application users"
        )


def validate_property_catalog_read_admission(
    *,
    read_mode: object,
    environment_type: object,
    cloud_deployment: object,
    dev_acknowledgement: object,
    prod_acknowledgement: object,
    database: object,
    host: object,
    port: object,
    api_read_user: object,
    password: object,
    source_users: object,
    dev_workspace_allowlist: object,
    prod_workspace_allowlist: object,
    prod_workspace_scope_mode: object = "allowlist",
) -> str | None:
    """Fail closed unless one bounded DEV or production read is admitted."""

    if read_mode not in {"off", "shadow", "read"}:
        raise ValueError("PROPERTY_CATALOG_READ_MODE must be off, shadow, or read")
    if read_mode == "off":
        return None

    deployment = property_catalog_read_deployment(
        environment_type,
        cloud_deployment,
    )
    if deployment == "dev":
        acknowledgement = dev_acknowledgement
        expected_acknowledgement = PROPERTY_CATALOG_DEV_READ_ACKNOWLEDGEMENT
        cross_wired_acknowledgement = prod_acknowledgement
        workspace_allowlist = dev_workspace_allowlist
        cross_wired_workspace_allowlist = prod_workspace_allowlist
        workspace_scope_mode = "allowlist"
        if prod_workspace_scope_mode != "allowlist":
            raise ValueError(
                "global property catalog workspace scope is production-only"
            )
    else:
        acknowledgement = prod_acknowledgement
        expected_acknowledgement = PROPERTY_CATALOG_PROD_READ_ACKNOWLEDGEMENT
        cross_wired_acknowledgement = dev_acknowledgement
        workspace_allowlist = prod_workspace_allowlist
        cross_wired_workspace_allowlist = dev_workspace_allowlist
        workspace_scope_mode = prod_workspace_scope_mode
        if workspace_scope_mode not in PROPERTY_CATALOG_PROD_WORKSPACE_SCOPE_MODES:
            raise ValueError(
                "PROPERTY_CATALOG_PROD_WORKSPACE_SCOPE_MODE must be allowlist or all"
            )
    if (
        acknowledgement != expected_acknowledgement
        or cross_wired_acknowledgement not in {None, ""}
    ):
        raise ValueError(
            "unified property catalog reads require the exact deployment-specific "
            "acknowledgement"
        )
    try:
        cross_wired_workspaces = tuple(cross_wired_workspace_allowlist)
    except TypeError as exc:
        raise ValueError(
            "property catalog workspace allowlists must be deployment-specific"
        ) from exc
    if cross_wired_workspaces:
        raise ValueError(
            "property catalog workspace allowlists must be deployment-specific"
        )

    validate_property_catalog_read_connection(
        host=host,
        port=port,
        database=database,
        api_read_user=api_read_user,
        password=password,
        source_users=source_users,
        deployment=deployment,
    )
    if isinstance(workspace_allowlist, (str, bytes)):
        raise ValueError(
            "property catalog workspace allowlist must contain 1 to 256 entries"
        )
    try:
        workspaces = tuple(workspace_allowlist)
    except TypeError as exc:
        raise ValueError(
            "property catalog workspace allowlist must contain 1 to 256 entries"
        ) from exc
    if workspace_scope_mode == "all":
        if workspaces:
            raise ValueError(
                "global property catalog workspace scope requires an empty allowlist"
            )
        return deployment
    if not 1 <= len(workspaces) <= PROPERTY_CATALOG_MAX_READ_WORKSPACES or any(
        not isinstance(workspace, str) or not workspace.strip()
        for workspace in workspaces
    ):
        raise ValueError(
            "property catalog workspace allowlist must contain 1 to 256 entries"
        )
    return deployment


def property_catalog_read_workspace_allowlist(source: object) -> tuple[object, ...]:
    """Return only the allowlist bound to the admitted read deployment."""

    deployment = getattr(source, "PROPERTY_CATALOG_READ_DEPLOYMENT", None)
    if deployment == "dev":
        configured = getattr(source, "PROPERTY_CATALOG_DEV_WORKSPACE_ALLOWLIST", ())
    elif deployment == "prod":
        configured = getattr(source, "PROPERTY_CATALOG_PROD_WORKSPACE_ALLOWLIST", ())
    else:
        return ()
    try:
        return tuple(configured)
    except TypeError:
        return ()


def property_catalog_reads_all_production_workspaces(source: object) -> bool:
    """Return whether admitted production reads use authenticated workspace scope."""

    return (
        getattr(source, "PROPERTY_CATALOG_READ_DEPLOYMENT", None) == "prod"
        and getattr(
            source,
            "PROPERTY_CATALOG_PROD_WORKSPACE_SCOPE_MODE",
            "allowlist",
        )
        == "all"
    )


PROPERTY_CATALOG_READ_MODE = (
    os.getenv("PROPERTY_CATALOG_READ_MODE", "off").strip().lower()
)
PROPERTY_CATALOG_PRODUCTION_DATABASE = os.getenv(
    PROPERTY_CATALOG_PRODUCTION_DATABASE_ENV,
    PROPERTY_CATALOG_DEFAULT_PRODUCTION_DATABASE,
).strip()
PROPERTY_CATALOG_DATABASE = os.getenv("PROPERTY_CATALOG_DATABASE", "").strip()
PROPERTY_CATALOG_DEV_READ_ACK = os.getenv("PROPERTY_CATALOG_DEV_READ_ACK", "").strip()
PROPERTY_CATALOG_PROD_READ_ACK = os.getenv("PROPERTY_CATALOG_PROD_READ_ACK", "").strip()
PROPERTY_CATALOG_CH_HOST = os.getenv("PROPERTY_CATALOG_CH_HOST", "").strip()
_property_catalog_ch_port_raw = os.getenv("PROPERTY_CATALOG_CH_PORT", "").strip()
PROPERTY_CATALOG_CH_USER = os.getenv("PROPERTY_CATALOG_CH_USER", "").strip()
PROPERTY_CATALOG_CH_PASSWORD = os.getenv("PROPERTY_CATALOG_CH_PASSWORD", "")

# Periodic unified reconciliation is a separate, write-capable DEV control
# plane. It is disabled unless the exact boolean is enabled and its activity
# revalidates the runtime deployment, isolated target, acknowledgement, and
# workspace allowlist before importing the reviewed runtime factory.
_property_catalog_dev_reconcile_enabled = (
    os.getenv("PROPERTY_CATALOG_DEV_RECONCILE_ENABLED", "false").strip().lower()
)
if _property_catalog_dev_reconcile_enabled not in {"true", "false"}:
    raise ValueError(
        "PROPERTY_CATALOG_DEV_RECONCILE_ENABLED must be exactly true or false"
    )
PROPERTY_CATALOG_DEV_RECONCILE_ENABLED = (
    _property_catalog_dev_reconcile_enabled == "true"
)
PROPERTY_CATALOG_DEV_ORGANIZATION_ID = os.getenv(
    "PROPERTY_CATALOG_DEV_ORGANIZATION_ID", ""
).strip()
PROPERTY_CATALOG_DEV_WORKSPACE_ID = os.getenv(
    "PROPERTY_CATALOG_DEV_WORKSPACE_ID", ""
).strip()
PROPERTY_CATALOG_DEV_ENVIRONMENT = os.getenv(
    "PROPERTY_CATALOG_DEV_ENVIRONMENT", ""
).strip()
PROPERTY_CATALOG_DEV_CLOUD_DEPLOYMENT = os.getenv(
    "PROPERTY_CATALOG_DEV_CLOUD_DEPLOYMENT", ""
).strip()
PROPERTY_CATALOG_DEV_IDENTITY = os.getenv("PROPERTY_CATALOG_DEV_IDENTITY", "").strip()
PROPERTY_CATALOG_DEV_SOURCE_DATABASE = os.getenv(
    "PROPERTY_CATALOG_DEV_SOURCE_DATABASE", ""
).strip()
PROPERTY_CATALOG_DEV_TARGET_DATABASE = os.getenv(
    "PROPERTY_CATALOG_DEV_TARGET_DATABASE", ""
).strip()
PROPERTY_CATALOG_DEV_ACKNOWLEDGEMENT = os.getenv(
    "PROPERTY_CATALOG_DEV_ACKNOWLEDGEMENT", ""
).strip()
PROPERTY_CATALOG_DEV_RUNTIME_FACTORY = os.getenv(
    "PROPERTY_CATALOG_DEV_RUNTIME_FACTORY",
    "tracer.services.clickhouse.v2.property_catalog.dev_runtime."
    "configured_property_catalog_dev_runtime",
).strip()
PROPERTY_CATALOG_DEV_WRITE_CH_HOST = os.getenv(
    "PROPERTY_CATALOG_DEV_WRITE_CH_HOST", ""
).strip()
_property_catalog_dev_write_ch_port_raw = os.getenv(
    "PROPERTY_CATALOG_DEV_WRITE_CH_PORT", ""
).strip()
PROPERTY_CATALOG_DEV_WRITE_CH_USER = os.getenv(
    "PROPERTY_CATALOG_DEV_WRITE_CH_USER", ""
).strip()
PROPERTY_CATALOG_DEV_WRITE_CH_PASSWORD = os.getenv(
    "PROPERTY_CATALOG_DEV_WRITE_CH_PASSWORD", ""
)
PROPERTY_CATALOG_DEV_WRITE_CH_DATABASE = os.getenv(
    "PROPERTY_CATALOG_DEV_WRITE_CH_DATABASE", ""
).strip()
PROPERTY_CATALOG_DEV_EXPECTED_WRITE_CH_HOSTNAME = os.getenv(
    "PROPERTY_CATALOG_DEV_EXPECTED_WRITE_CH_HOSTNAME", ""
).strip()
PROPERTY_CATALOG_DEV_EXPECTED_SOURCE_CH_HOSTNAME = os.getenv(
    "PROPERTY_CATALOG_DEV_EXPECTED_SOURCE_CH_HOSTNAME", ""
).strip()
PROPERTY_CATALOG_DEV_EXPECTED_WRITE_CH_HOSTNAMES = tuple(
    _split_env("PROPERTY_CATALOG_DEV_EXPECTED_WRITE_CH_HOSTNAMES")
)
PROPERTY_CATALOG_DEV_EXPECTED_SOURCE_CH_HOSTNAMES = tuple(
    _split_env("PROPERTY_CATALOG_DEV_EXPECTED_SOURCE_CH_HOSTNAMES")
)
PROPERTY_CATALOG_DEV_EXPECTED_PG_DATABASE = os.getenv(
    "PROPERTY_CATALOG_DEV_EXPECTED_PG_DATABASE", ""
).strip()
PROPERTY_CATALOG_DEV_EXPECTED_PG_USER = os.getenv(
    "PROPERTY_CATALOG_DEV_EXPECTED_PG_USER", ""
).strip()
PROPERTY_CATALOG_DEV_EXPECTED_PG_SERVER_ADDRESS = os.getenv(
    "PROPERTY_CATALOG_DEV_EXPECTED_PG_SERVER_ADDRESS", ""
).strip()
_property_catalog_dev_expected_pg_port_raw = os.getenv(
    "PROPERTY_CATALOG_DEV_EXPECTED_PG_SERVER_PORT", ""
).strip()
_property_catalog_dev_epoch_raw = os.getenv(
    "PROPERTY_CATALOG_DEV_CATALOG_EPOCH", ""
).strip()
_property_catalog_dev_projection_raw = os.getenv(
    "PROPERTY_CATALOG_DEV_PROJECTION_VERSION", ""
).strip()
PROPERTY_CATALOG_DEV_PROJECT_ALLOWLIST = tuple(
    sorted(
        {
            value.strip()
            for value in os.getenv("PROPERTY_CATALOG_DEV_PROJECT_ALLOWLIST", "").split(
                ","
            )
            if value.strip()
        }
    )
)
PROPERTY_CATALOG_DEV_SPAN_SINCE = os.getenv(
    "PROPERTY_CATALOG_DEV_SPAN_SINCE", ""
).strip()
PROPERTY_CATALOG_DEV_SPAN_UNTIL = os.getenv(
    "PROPERTY_CATALOG_DEV_SPAN_UNTIL", ""
).strip()
PROPERTY_CATALOG_DEV_HOT_PRODUCER_STREAM_ID = os.getenv(
    "PROPERTY_CATALOG_DEV_HOT_PRODUCER_STREAM_ID", ""
).strip()
PROPERTY_CATALOG_DEV_REVISION_FENCE_FILE = os.getenv(
    "PROPERTY_CATALOG_DEV_REVISION_FENCE_FILE", ""
).strip()
PROPERTY_CATALOG_DEV_DRAIN_PROOF_FILE = os.getenv(
    "PROPERTY_CATALOG_DEV_DRAIN_PROOF_FILE", ""
).strip()
PROPERTY_CATALOG_DEV_PRODUCER_RETIREMENT_FILE = os.getenv(
    "PROPERTY_CATALOG_DEV_PRODUCER_RETIREMENT_FILE", ""
).strip()
PROPERTY_CATALOG_RUNTIME_UID = _bounded_env_int(
    "PROPERTY_CATALOG_RUNTIME_UID",
    65_532,
    minimum=1,
    maximum=2_147_483_647,
)
PROPERTY_CATALOG_DEV_MUTATION_LOCK_DIRECTORY = os.getenv(
    "PROPERTY_CATALOG_DEV_MUTATION_LOCK_DIRECTORY", ""
).strip()
PROPERTY_CATALOG_DEV_SIDECAR_ACK = os.getenv(
    "PROPERTY_CATALOG_DEV_SIDECAR_ACK", ""
).strip()
PROPERTY_CATALOG_DEV_WORKSPACE_ALLOWLIST = tuple(
    sorted(
        {
            value.strip()
            for value in os.getenv(
                "PROPERTY_CATALOG_DEV_WORKSPACE_ALLOWLIST", ""
            ).split(",")
            if value.strip()
        }
    )
)
PROPERTY_CATALOG_PROD_WORKSPACE_ALLOWLIST = tuple(
    sorted(
        {
            value.strip()
            for value in os.getenv(
                "PROPERTY_CATALOG_PROD_WORKSPACE_ALLOWLIST", ""
            ).split(",")
            if value.strip()
        }
    )
)
PROPERTY_CATALOG_PROD_WORKSPACE_SCOPE_MODE = (
    os.getenv(
        "PROPERTY_CATALOG_PROD_WORKSPACE_SCOPE_MODE",
        "allowlist",
    )
    .strip()
    .lower()
)
try:
    PROPERTY_CATALOG_CH_PORT = (
        int(_property_catalog_ch_port_raw) if _property_catalog_ch_port_raw else 0
    )
except ValueError:
    PROPERTY_CATALOG_CH_PORT = 0
try:
    PROPERTY_CATALOG_DEV_WRITE_CH_PORT = (
        int(_property_catalog_dev_write_ch_port_raw)
        if _property_catalog_dev_write_ch_port_raw
        else 0
    )
except ValueError:
    PROPERTY_CATALOG_DEV_WRITE_CH_PORT = 0
try:
    PROPERTY_CATALOG_DEV_EXPECTED_PG_SERVER_PORT = (
        int(_property_catalog_dev_expected_pg_port_raw)
        if _property_catalog_dev_expected_pg_port_raw
        else 0
    )
except ValueError:
    PROPERTY_CATALOG_DEV_EXPECTED_PG_SERVER_PORT = 0
try:
    PROPERTY_CATALOG_DEV_CATALOG_EPOCH = (
        int(_property_catalog_dev_epoch_raw) if _property_catalog_dev_epoch_raw else 0
    )
except ValueError:
    PROPERTY_CATALOG_DEV_CATALOG_EPOCH = 0
try:
    PROPERTY_CATALOG_DEV_PROJECTION_VERSION = (
        int(_property_catalog_dev_projection_raw)
        if _property_catalog_dev_projection_raw
        else 0
    )
except ValueError:
    PROPERTY_CATALOG_DEV_PROJECTION_VERSION = 0
PROPERTY_CATALOG_DEV_MAX_WALL_MS = _bounded_env_int(
    "PROPERTY_CATALOG_DEV_MAX_WALL_MS",
    int(_runtime_numeric_settings["PROPERTY_CATALOG_DEV_STANDARD_MAX_WALL_MS"]),
    minimum=100,
    maximum=int(
        _runtime_numeric_settings["PROPERTY_CATALOG_DEV_INITIAL_BACKFILL_MAX_WALL_MS"]
    ),
)
PROPERTY_CATALOG_DEV_SCHEDULED_RECONCILE_WALL_MS = _bounded_env_int(
    "PROPERTY_CATALOG_DEV_SCHEDULED_RECONCILE_WALL_MS",
    int(
        _runtime_numeric_settings["PROPERTY_CATALOG_RECONCILE_DEFAULT_EXTENDED_WALL_MS"]
    ),
    minimum=100,
    maximum=int(
        _runtime_numeric_settings[
            "PROPERTY_CATALOG_DEV_SCHEDULED_RECONCILE_MAX_WALL_MS"
        ]
    ),
)

# Production lifecycle controller.  This is a distinct write-capable process,
# disabled by default, with a dedicated ClickHouse writer and server-enforced
# read-only source identities.  The management command repeats every gate.
_property_catalog_lifecycle_enabled_raw = (
    os.getenv("PROPERTY_CATALOG_LIFECYCLE_ENABLED", "false").strip().lower()
)
if _property_catalog_lifecycle_enabled_raw not in {"true", "false"}:
    raise ValueError("PROPERTY_CATALOG_LIFECYCLE_ENABLED must be exactly true or false")
PROPERTY_CATALOG_LIFECYCLE_ENABLED = _property_catalog_lifecycle_enabled_raw == "true"
_property_catalog_lifecycle_bootstrap_enabled_raw = (
    os.getenv("PROPERTY_CATALOG_LIFECYCLE_BOOTSTRAP_ENABLED", "false").strip().lower()
)
if _property_catalog_lifecycle_bootstrap_enabled_raw not in {"true", "false"}:
    raise ValueError(
        "PROPERTY_CATALOG_LIFECYCLE_BOOTSTRAP_ENABLED must be exactly true or false"
    )
PROPERTY_CATALOG_LIFECYCLE_BOOTSTRAP_ENABLED = (
    _property_catalog_lifecycle_bootstrap_enabled_raw == "true"
)
_property_catalog_lifecycle_repair_expired_raw = (
    os.getenv(
        "PROPERTY_CATALOG_LIFECYCLE_REPAIR_EXPIRED_INCOMPLETE",
        "false",
    )
    .strip()
    .lower()
)
if _property_catalog_lifecycle_repair_expired_raw not in {"true", "false"}:
    raise ValueError(
        "PROPERTY_CATALOG_LIFECYCLE_REPAIR_EXPIRED_INCOMPLETE must be exactly "
        "true or false"
    )
PROPERTY_CATALOG_LIFECYCLE_REPAIR_EXPIRED_INCOMPLETE = (
    _property_catalog_lifecycle_repair_expired_raw == "true"
)
PROPERTY_CATALOG_LIFECYCLE_ACK = os.getenv("PROPERTY_CATALOG_LIFECYCLE_ACK", "").strip()
PROPERTY_CATALOG_LIFECYCLE_IDENTITY = os.getenv(
    "PROPERTY_CATALOG_LIFECYCLE_IDENTITY", ""
).strip()
PROPERTY_CATALOG_LIFECYCLE_SOURCE_DATABASE = os.getenv(
    "PROPERTY_CATALOG_LIFECYCLE_SOURCE_DATABASE", ""
).strip()
PROPERTY_CATALOG_LIFECYCLE_TARGET_DATABASE = os.getenv(
    "PROPERTY_CATALOG_LIFECYCLE_TARGET_DATABASE", "property_catalog"
).strip()
PROPERTY_CATALOG_LIFECYCLE_WRITE_CH_HOST = os.getenv(
    "PROPERTY_CATALOG_LIFECYCLE_WRITE_CH_HOST", ""
).strip()
_property_catalog_lifecycle_write_ch_port_raw = os.getenv(
    "PROPERTY_CATALOG_LIFECYCLE_WRITE_CH_PORT", ""
).strip()
PROPERTY_CATALOG_LIFECYCLE_WRITE_CH_USER = os.getenv(
    "PROPERTY_CATALOG_LIFECYCLE_WRITE_CH_USER", ""
).strip()
PROPERTY_CATALOG_LIFECYCLE_WRITE_CH_PASSWORD = os.getenv(
    "PROPERTY_CATALOG_LIFECYCLE_WRITE_CH_PASSWORD", ""
)
PROPERTY_CATALOG_ACTIVATION_CONTROL_ACK = os.getenv(
    "PROPERTY_CATALOG_ACTIVATION_CONTROL_ACK", ""
).strip()
PROPERTY_CATALOG_ACTIVATION_CONTROL_CH_USER = os.getenv(
    "PROPERTY_CATALOG_ACTIVATION_CONTROL_CH_USER", ""
).strip()
PROPERTY_CATALOG_ACTIVATION_CONTROL_CH_PASSWORD = os.getenv(
    "PROPERTY_CATALOG_ACTIVATION_CONTROL_CH_PASSWORD", ""
)
PROPERTY_CATALOG_LIFECYCLE_EXPECTED_WRITE_CH_HOSTNAME = os.getenv(
    "PROPERTY_CATALOG_LIFECYCLE_EXPECTED_WRITE_CH_HOSTNAME", ""
).strip()
PROPERTY_CATALOG_LIFECYCLE_EXPECTED_SOURCE_CH_HOSTNAME = os.getenv(
    "PROPERTY_CATALOG_LIFECYCLE_EXPECTED_SOURCE_CH_HOSTNAME", ""
).strip()
PROPERTY_CATALOG_LIFECYCLE_EXPECTED_WRITE_CH_HOSTNAMES = tuple(
    _split_env("PROPERTY_CATALOG_LIFECYCLE_EXPECTED_WRITE_CH_HOSTNAMES")
)
PROPERTY_CATALOG_LIFECYCLE_EXPECTED_SOURCE_CH_HOSTNAMES = tuple(
    _split_env("PROPERTY_CATALOG_LIFECYCLE_EXPECTED_SOURCE_CH_HOSTNAMES")
)
PROPERTY_CATALOG_LIFECYCLE_EXPECTED_PG_DATABASE = os.getenv(
    "PROPERTY_CATALOG_LIFECYCLE_EXPECTED_PG_DATABASE", ""
).strip()
PROPERTY_CATALOG_LIFECYCLE_EXPECTED_PG_USER = os.getenv(
    "PROPERTY_CATALOG_LIFECYCLE_EXPECTED_PG_USER", ""
).strip()
PROPERTY_CATALOG_LIFECYCLE_EXPECTED_PG_SERVER_ADDRESS = os.getenv(
    "PROPERTY_CATALOG_LIFECYCLE_EXPECTED_PG_SERVER_ADDRESS", ""
).strip()
_property_catalog_lifecycle_expected_pg_port_raw = os.getenv(
    "PROPERTY_CATALOG_LIFECYCLE_EXPECTED_PG_SERVER_PORT", ""
).strip()
PROPERTY_CATALOG_LIFECYCLE_CATALOG_EPOCH = _bounded_env_int(
    "PROPERTY_CATALOG_LIFECYCLE_CATALOG_EPOCH", 0, minimum=0, maximum=65_535
)
PROPERTY_CATALOG_LIFECYCLE_PROJECTION_VERSION = _bounded_env_int(
    "PROPERTY_CATALOG_LIFECYCLE_PROJECTION_VERSION",
    0,
    minimum=0,
    maximum=65_535,
)
PROPERTY_CATALOG_LIFECYCLE_PRODUCER_STREAM_ID = os.getenv(
    "PROPERTY_CATALOG_LIFECYCLE_PRODUCER_STREAM_ID", ""
).strip()
PROPERTY_CATALOG_LIFECYCLE_REVISION_FENCE_FILE = os.getenv(
    "PROPERTY_CATALOG_LIFECYCLE_REVISION_FENCE_FILE", ""
).strip()
PROPERTY_CATALOG_LIFECYCLE_DRAIN_PROOF_FILE = os.getenv(
    "PROPERTY_CATALOG_LIFECYCLE_DRAIN_PROOF_FILE", ""
).strip()
PROPERTY_CATALOG_LIFECYCLE_PRODUCER_RETIREMENT_FILE = os.getenv(
    "PROPERTY_CATALOG_LIFECYCLE_PRODUCER_RETIREMENT_FILE", ""
).strip()
PROPERTY_CATALOG_LIFECYCLE_RUNTIME_DIRECTORY = os.getenv(
    "PROPERTY_CATALOG_LIFECYCLE_RUNTIME_DIRECTORY", ""
).strip()
PROPERTY_CATALOG_LIFECYCLE_HEALTH_FILE = os.getenv(
    "PROPERTY_CATALOG_LIFECYCLE_HEALTH_FILE", ""
).strip()
PROPERTY_CATALOG_LIFECYCLE_WORKSPACE_SCOPE_MODE = (
    os.getenv("PROPERTY_CATALOG_LIFECYCLE_WORKSPACE_SCOPE_MODE", "allowlist")
    .strip()
    .lower()
)
PROPERTY_CATALOG_LIFECYCLE_WORKSPACE_ALLOWLIST = tuple(
    sorted(
        {
            value.strip()
            for value in os.getenv(
                "PROPERTY_CATALOG_LIFECYCLE_WORKSPACE_ALLOWLIST", ""
            ).split(",")
            if value.strip()
        }
    )
)
PROPERTY_CATALOG_LIFECYCLE_POLL_SECONDS = _bounded_env_int(
    "PROPERTY_CATALOG_LIFECYCLE_POLL_SECONDS", 60, minimum=5, maximum=3_600
)
PROPERTY_CATALOG_LIFECYCLE_FAILURE_BACKOFF_SECONDS = _bounded_env_int(
    "PROPERTY_CATALOG_LIFECYCLE_FAILURE_BACKOFF_SECONDS",
    30,
    minimum=5,
    maximum=3_600,
)
PROPERTY_CATALOG_LIFECYCLE_SPAN_WINDOW_DAYS = _bounded_env_int(
    "PROPERTY_CATALOG_LIFECYCLE_SPAN_WINDOW_DAYS", 366, minimum=1, maximum=366
)
PROPERTY_CATALOG_LIFECYCLE_MAX_WALL_MS = _bounded_env_int(
    "PROPERTY_CATALOG_LIFECYCLE_MAX_WALL_MS",
    int(_runtime_numeric_settings["PROPERTY_CATALOG_DEV_STANDARD_MAX_WALL_MS"]),
    minimum=100,
    maximum=int(_runtime_numeric_settings["PROPERTY_CATALOG_DEV_STANDARD_MAX_WALL_MS"]),
)
PROPERTY_CATALOG_LIFECYCLE_SCHEDULED_RECONCILE_WALL_MS = _bounded_env_int(
    "PROPERTY_CATALOG_LIFECYCLE_SCHEDULED_RECONCILE_WALL_MS",
    int(
        _runtime_numeric_settings["PROPERTY_CATALOG_RECONCILE_DEFAULT_EXTENDED_WALL_MS"]
    ),
    minimum=int(_runtime_numeric_settings["PROPERTY_CATALOG_DEV_STANDARD_MAX_WALL_MS"])
    + 1,
    maximum=int(
        _runtime_numeric_settings[
            "PROPERTY_CATALOG_DEV_SCHEDULED_RECONCILE_MAX_WALL_MS"
        ]
    ),
)
try:
    PROPERTY_CATALOG_LIFECYCLE_WRITE_CH_PORT = (
        int(_property_catalog_lifecycle_write_ch_port_raw)
        if _property_catalog_lifecycle_write_ch_port_raw
        else 0
    )
except ValueError:
    PROPERTY_CATALOG_LIFECYCLE_WRITE_CH_PORT = 0
try:
    PROPERTY_CATALOG_LIFECYCLE_EXPECTED_PG_SERVER_PORT = (
        int(_property_catalog_lifecycle_expected_pg_port_raw)
        if _property_catalog_lifecycle_expected_pg_port_raw
        else 0
    )
except ValueError:
    PROPERTY_CATALOG_LIFECYCLE_EXPECTED_PG_SERVER_PORT = 0
del _runtime_numeric_settings
PROPERTY_CATALOG_READ_DEPLOYMENT = validate_property_catalog_read_admission(
    read_mode=PROPERTY_CATALOG_READ_MODE,
    environment_type=ENV_TYPE,
    cloud_deployment=CLOUD_DEPLOYMENT,
    dev_acknowledgement=PROPERTY_CATALOG_DEV_READ_ACK,
    prod_acknowledgement=PROPERTY_CATALOG_PROD_READ_ACK,
    database=PROPERTY_CATALOG_DATABASE,
    host=PROPERTY_CATALOG_CH_HOST,
    port=PROPERTY_CATALOG_CH_PORT,
    api_read_user=PROPERTY_CATALOG_CH_USER,
    password=PROPERTY_CATALOG_CH_PASSWORD,
    source_users={
        str(CLICKHOUSE_V2.get("CH25_USER") or "").strip(),
        str(CLICKHOUSE.get("CH_USERNAME") or "").strip(),
    }
    - {""},
    dev_workspace_allowlist=PROPERTY_CATALOG_DEV_WORKSPACE_ALLOWLIST,
    prod_workspace_allowlist=PROPERTY_CATALOG_PROD_WORKSPACE_ALLOWLIST,
    prod_workspace_scope_mode=PROPERTY_CATALOG_PROD_WORKSPACE_SCOPE_MODE,
)
PROPERTY_CATALOG_READ_WORKSPACE_ALLOWLIST = (
    PROPERTY_CATALOG_DEV_WORKSPACE_ALLOWLIST
    if PROPERTY_CATALOG_READ_DEPLOYMENT == "dev"
    else PROPERTY_CATALOG_PROD_WORKSPACE_ALLOWLIST
    if PROPERTY_CATALOG_READ_DEPLOYMENT == "prod"
    else ()
)

# Fail-closed: rollup routing requires both flag=on and window >= coverage date.
# Set COVERED_SINCE (ISO-8601) after running rebuild_dashboard_attr_rollup.
DASHBOARD_ATTR_ROLLUP_ENABLED = (
    os.getenv("DASHBOARD_ATTR_ROLLUP_ENABLED", "false").lower() == "true"
)
_dashboard_attr_rollup_covered_since = os.getenv("DASHBOARD_ATTR_ROLLUP_COVERED_SINCE")
DASHBOARD_ATTR_ROLLUP_COVERED_SINCE = (
    datetime.fromisoformat(_dashboard_attr_rollup_covered_since)
    if _dashboard_attr_rollup_covered_since
    else None
)

# Eval-logger table read by the trace/voice/user eval-config discovery queries.
# The CH25 spans cutover intentionally kept the legacy peerdb CDC table
# `tracer_eval_logger` (`_peerdb_is_deleted`/`deleted` columns); the v2 table
# `tracer_eval_logger_v2` (`is_deleted`) is its prepared replacement. Flip this
# per-deployment (default = legacy so the peerdb-backed stacks are unaffected;
# CH-direct stacks set it to `tracer_eval_logger_v2`). See
# tracer/services/clickhouse/v2/schema/011_eval_logger_v2.sql + docs/CH25_MIGRATION.md.
CH25_EVAL_LOGGER_TABLE = os.getenv("CH25_EVAL_LOGGER_TABLE", "tracer_eval_logger")

# Where the eval runner reads span data from.
#   "postgres"   — current behavior; reads from tracer_observation_span (Django ORM)
#   "clickhouse" — reads span data from CH 25.3 via the hybrid loader
#                  (tracer/services/clickhouse/v2/eval_loader.py). Django FK
#                  navigation (project, trace, end_user, …) still hits PG.
# Default is "postgres" so cutover is opt-in. Flip to "clickhouse" only after
# the backfill + validator pass and a soak period.
EVAL_SPAN_READ_SOURCE = os.getenv("EVAL_SPAN_READ_SOURCE", "postgres").lower()
