# Generated by Django 5.1.8 on 2026-06-22 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0074_canonicalize_simulate_eval_config_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='providercredentials',
            name='agent_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='simulate.agentversion'),
        ),
        migrations.AlterField(
            model_name='providercredentials',
            name='agent_definition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials_legacy', to='simulate.agentdefinition'),
        ),
    ]
