# Generated by Django 5.1.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0077_relax_simulate_eval_config_model_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdefinition',
            name='target_speaks_first',
            field=models.BooleanField(
                null=True,
                blank=True,
                help_text=(
                    'Whether the target agent speaks first (greets) in a hosted '
                    'voice simulation. True: the simulator waits for the target'
                    "'s greeting; False: the simulator opens the conversation; "
                    'null: derive from inbound/outbound. Retell targets always '
                    'let the simulator open (SDK limitation).'
                ),
            ),
        ),
    ]
