export const PERMISSIONS = {
  CREATE: "create",
  READ: "read",
  UPDATE: "update",
  DELETE: "delete",
  DEPLOY: "deploy",
  EVALUATE: "evaluate",
  VIEW: "view",
  SHARE: "share",
  VIEW_METRICS: "view_metrics",
  VIEW_LOGS: "view_logs",
  VIEW_TRACES: "view_traces",
  CREATE_EDIT_PROJECT: "create_edit_project",
  DELETE_PROJECT: "delete_project",
  ADD_TASKS_ALERTS: "add_tasks_alerts",
  CREATE_EXP: "create_exp",
  RUN_EXP: "run_exp",
  VIEW_RESULTS: "view_results",
  CREATE_NEW_WORKSPACE: "create_new_workspace",
  ADD_EDIT_OWNERS: "add_edit_owners",
  ADD_ADMINS: "add_admins",
  ADD_ADMINS_MEMBERS: "add_admins_members",
  EDIT_USER: "edit_user",
  DELETE_USER: "delete_user",
  VIEW_USER_MANAGEMENT: "view_user_management",
  SEND_REQUEST: "send_request",
  ACCEPT_REQUEST: "accept_request",
  READ_EVALS: "read_evals",
  EDIT_CREATE_DELETE_EVALS: "edit_create_delete_evals",
  CREATE_AGENT_SIMULATION: "create_agent_simulation",
  VIEW_RESULTS_RUN_TEST: "view_results_run_test",
  RUN_SIMULATION_TEST: "run_simulation_test",
};

export const ROLES = {
  OWNER: "Owner",
  ADMIN: "Admin",
  MEMBER: "Member",
  VIEWER: "Viewer",
  WORKSPACE_ADMIN: "workspace_admin",
  WORKSPACE_MEMBER: "workspace_member",
  WORKSPACE_VIEWER: "workspace_viewer",
};

export const RolePermission = {
  DATASETS: {
    [PERMISSIONS.CREATE]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.READ]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: true,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: true,
    },
    [PERMISSIONS.UPDATE]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.DELETE]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
  },
  AGENTS: {
    [PERMISSIONS.CREATE]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.READ]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: true,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: true,
    },
    [PERMISSIONS.UPDATE]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.DELETE]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
  },
  PROMPTS: {
    [PERMISSIONS.CREATE]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.READ]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: true,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: true,
    },
    [PERMISSIONS.UPDATE]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.DEPLOY]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: false,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: false,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.EVALUATE]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.DELETE]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
  },
  API_KEYS: {
    [PERMISSIONS.CREATE]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: false,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: false,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.VIEW]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: false,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: false,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.DELETE]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: false,
      [ROLES.MEMBER]: false,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: false,
      [ROLES.WORKSPACE_MEMBER]: false,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.SHARE]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: false,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: false,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
  },
  OBSERVABILITY: {
    [PERMISSIONS.VIEW_METRICS]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: true,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: true,
    },
    [PERMISSIONS.VIEW_LOGS]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: true,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: true,
    },
    [PERMISSIONS.VIEW_TRACES]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: true,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: true,
    },
    [PERMISSIONS.CREATE_EDIT_PROJECT]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.DELETE_PROJECT]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: false,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: false,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.ADD_TASKS_ALERTS]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
  },
  PROTOTYPING: {
    [PERMISSIONS.CREATE_EXP]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.RUN_EXP]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.VIEW_RESULTS]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: true,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: true,
    },
  },
  ADMIN_MANAGEMENT: {
    [PERMISSIONS.CREATE_NEW_WORKSPACE]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: null, // "-" in matrix
      [ROLES.VIEWER]: null, // "-" in matrix
      [ROLES.WORKSPACE_ADMIN]: null, // "-" in matrix — only org Owner/Admin can create
      [ROLES.WORKSPACE_MEMBER]: null, // "-" in matrix
      [ROLES.WORKSPACE_VIEWER]: null, // "-" in matrix
    },
    [PERMISSIONS.ADD_EDIT_OWNERS]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: false,
      [ROLES.MEMBER]: false,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: false,
      [ROLES.WORKSPACE_MEMBER]: false,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.ADD_ADMINS]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: false,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: false,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.ADD_ADMINS_MEMBERS]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: false,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: false,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.EDIT_USER]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: false,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: false,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.DELETE_USER]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: false,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: false,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.VIEW_USER_MANAGEMENT]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: false,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: false,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.SEND_REQUEST]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: true,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: true,
    },
    [PERMISSIONS.ACCEPT_REQUEST]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: false,
      [ROLES.MEMBER]: false,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: false,
      [ROLES.WORKSPACE_MEMBER]: false,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
  },
  EVALS: {
    [PERMISSIONS.READ_EVALS]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: true,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: true,
    },
    [PERMISSIONS.EDIT_CREATE_DELETE_EVALS]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.CREATE_AGENT_SIMULATION]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.VIEW_RESULTS_RUN_TEST]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: true,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: true,
    },
    [PERMISSIONS.EVALUATE]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.UPDATE]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
  },
  KNOWLEDGE_BASE: {
    [PERMISSIONS.CREATE]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.UPDATE]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.DELETE]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
  },
  SIMULATION_AGENT: {
    [PERMISSIONS.CREATE]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.UPDATE]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.DELETE]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.RUN_SIMULATION_TEST]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
  },
  DASHBOARDS: {
    [PERMISSIONS.CREATE]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.READ]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: true,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: true,
    },
    [PERMISSIONS.UPDATE]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
    [PERMISSIONS.DELETE]: {
      [ROLES.OWNER]: true,
      [ROLES.ADMIN]: true,
      [ROLES.MEMBER]: true,
      [ROLES.VIEWER]: false,
      [ROLES.WORKSPACE_ADMIN]: true,
      [ROLES.WORKSPACE_MEMBER]: true,
      [ROLES.WORKSPACE_VIEWER]: false,
    },
  },
};

export const RoutesName = {
  usageSummary: "usageSummary",
  members: "members",
  aiProvider: "aiProvider",
  integrations: "integrations",
  mcpServer: "mcpServer",
  planAndPricing: "planAndPricing",
  billing: "billing",
  profile: "profile",
  workspace: "workspace",
};

export const showRoleSpecific = {
  [RoutesName.usageSummary]: {
    [ROLES.OWNER]: true,
    [ROLES.ADMIN]: true,
    [ROLES.MEMBER]: true,
    [ROLES.VIEWER]: true,
    [ROLES.WORKSPACE_ADMIN]: true,
    [ROLES.WORKSPACE_MEMBER]: true,
    [ROLES.WORKSPACE_VIEWER]: true,
  },
  [RoutesName.members]: {
    [ROLES.OWNER]: true,
    [ROLES.ADMIN]: true,
    [ROLES.MEMBER]: false,
    [ROLES.VIEWER]: false,
    [ROLES.WORKSPACE_ADMIN]: true,
    [ROLES.WORKSPACE_MEMBER]: true,
    [ROLES.WORKSPACE_VIEWER]: false,
  },
  [RoutesName.aiProvider]: {
    [ROLES.OWNER]: true,
    [ROLES.ADMIN]: true,
    [ROLES.MEMBER]: true,
    [ROLES.VIEWER]: false,
    [ROLES.WORKSPACE_ADMIN]: true,
    [ROLES.WORKSPACE_MEMBER]: true,
    [ROLES.WORKSPACE_VIEWER]: false,
  },
  [RoutesName.integrations]: {
    [ROLES.OWNER]: true,
    [ROLES.ADMIN]: true,
    [ROLES.MEMBER]: false,
    [ROLES.VIEWER]: false,
    [ROLES.WORKSPACE_ADMIN]: true,
    [ROLES.WORKSPACE_MEMBER]: false,
    [ROLES.WORKSPACE_VIEWER]: false,
  },
  [RoutesName.mcpServer]: {
    [ROLES.OWNER]: true,
    [ROLES.ADMIN]: true,
    [ROLES.MEMBER]: true,
    [ROLES.VIEWER]: false,
    [ROLES.WORKSPACE_ADMIN]: true,
    [ROLES.WORKSPACE_MEMBER]: true,
    [ROLES.WORKSPACE_VIEWER]: false,
  },
  [RoutesName.planAndPricing]: {
    [ROLES.OWNER]: true,
    [ROLES.ADMIN]: true,
    [ROLES.MEMBER]: false,
    [ROLES.VIEWER]: false,
    [ROLES.WORKSPACE_ADMIN]: true,
    [ROLES.WORKSPACE_MEMBER]: false,
    [ROLES.WORKSPACE_VIEWER]: false,
  },
  [RoutesName.billing]: {
    [ROLES.OWNER]: true,
    [ROLES.ADMIN]: true,
    [ROLES.MEMBER]: false,
    [ROLES.VIEWER]: false,
    [ROLES.WORKSPACE_ADMIN]: true,
    [ROLES.WORKSPACE_MEMBER]: false,
    [ROLES.WORKSPACE_VIEWER]: false,
  },
  [RoutesName.profile]: {
    [ROLES.OWNER]: true,
    [ROLES.ADMIN]: true,
    [ROLES.MEMBER]: true,
    [ROLES.VIEWER]: true,
    [ROLES.WORKSPACE_ADMIN]: true,
    [ROLES.WORKSPACE_MEMBER]: true,
    [ROLES.WORKSPACE_VIEWER]: true,
  },
  [RoutesName.workspace]: {
    [ROLES.OWNER]: true,
    [ROLES.ADMIN]: true,
    [ROLES.MEMBER]: false,
    [ROLES.VIEWER]: false,
    [ROLES.WORKSPACE_ADMIN]: false,
    [ROLES.WORKSPACE_MEMBER]: false,
    [ROLES.WORKSPACE_VIEWER]: false,
  },
};
