TASK_CATEGORIES = {
    "Reading comprehension": {
        "sub_skills": [
            "Main idea identification",
            "Detail extraction",
            "Inference making",
            "Context understanding",
            "Summarization",
            "Fact vs opinion differentiation",
            "Author's purpose/tone analysis",
            "Vocabulary in context",
            "Sequential comprehension",
            "Critical analysis",
        ],
        "dataset_characteristics": [
            "Text complexity level",
            "Topic diversity",
            "Text length variation",
            "Genre variety",
            "Question types coverage",
            "Cultural context range",
            "Vocabulary range",
            "Structure variety",
            "Reading level indicators",
            "Subject matter breadth",
        ],
    },
    "Text modification": {
        "sub_skills": [
            "Paraphrasing",
            "Style transfer",
            "Text simplification",
            "Format conversion",
            "Grammar correction",
            "Tone adjustment",
            "Content expansion",
            "Text summarization",
            "Language translation",
            "Text normalization",
        ],
        "dataset_characteristics": [
            "Style diversity",
            "Text complexity range",
            "Domain coverage",
            "Language register variety",
            "Format diversity",
            "Length variation",
            "Source-target pairs",
            "Context examples",
            "Modification complexity",
            "Genre representation",
        ],
    },
    "Coding": {
        "sub_skills": [
            "Code generation",
            "Bug fixing",
            "Code optimization",
            "Code explanation",
            "Code completion",
            "Refactoring",
            "Algorithm design",
            "Documentation writing",
            "Test case generation",
            "Code review",
        ],
        "dataset_characteristics": [
            "Language diversity",
            "Problem complexity levels",
            "Code style variations",
            "Documentation quality",
            "Edge cases coverage",
            "Algorithm variety",
            "Error type diversity",
            "Code pattern examples",
            "Best practices alignment",
            "Performance scenarios",
        ],
    },
    "Retrieval-augmented generation (RAG)": {
        "sub_skills": [
            "Document retrieval",
            "Context integration",
            "Source citation",
            "Fact verification",
            "Query reformulation",
            "Information synthesis",
            "Relevance ranking",
            "Multi-document reasoning",
            "Knowledge grounding",
            "Source comparison",
        ],
        "dataset_characteristics": [
            "Document diversity",
            "Query complexity",
            "Context length variation",
            "Information density",
            "Source reliability levels",
            "Cross-reference examples",
            "Citation formats",
            "Multi-source scenarios",
            "Domain coverage",
            "Temporal relevance",
        ],
    },
    "Creative writing": {
        "sub_skills": [
            "Story generation",
            "Character development",
            "Plot construction",
            "Dialogue writing",
            "Setting description",
            "Poetry composition",
            "Narrative perspective",
            "Theme development",
            "Creative adaptation",
            "Style imitation",
        ],
        "dataset_characteristics": [
            "Genre diversity",
            "Writing style variety",
            "Plot complexity",
            "Character depth",
            "Setting richness",
            "Narrative techniques",
            "Literary devices",
            "Emotional range",
            "Cultural elements",
            "Creative techniques",
        ],
    },
    "Tool/API usage": {
        "sub_skills": [
            "API integration",
            "Parameter handling",
            "Error management",
            "Data formatting",
            "Authentication",
            "Request optimization",
            "Response parsing",
            "Rate limiting",
            "Webhook handling",
            "Documentation usage",
        ],
        "dataset_characteristics": [
            "API types variety",
            "Authentication methods",
            "Request/response patterns",
            "Error scenarios",
            "Rate limit cases",
            "Data format diversity",
            "Integration complexity",
            "Security considerations",
            "Performance patterns",
            "Documentation coverage",
        ],
    },
    "Analytical reasoning": {
        "sub_skills": [
            "Logic puzzles",
            "Pattern recognition",
            "Deductive reasoning",
            "Data analysis",
            "Hypothesis testing",
            "Problem decomposition",
            "Causal analysis",
            "Statistical interpretation",
            "Decision making",
            "Systems thinking",
        ],
        "dataset_characteristics": [
            "Problem complexity",
            "Logic types",
            "Data structure variety",
            "Solution approaches",
            "Abstract reasoning cases",
            "Quantitative elements",
            "Qualitative aspects",
            "Time constraints",
            "Resource limitations",
            "Decision scenarios",
        ],
    },
    "Brain teasers": {
        "sub_skills": [
            "Mathematical puzzles",
            "Word problems",
            "Lateral thinking",
            "Sequence completion",
            "Spatial reasoning",
            "Riddles",
            "Logic games",
            "Pattern matching",
            "Visual puzzles",
            "Probability problems",
        ],
        "dataset_characteristics": [
            "Puzzle complexity",
            "Problem types",
            "Solution methods",
            "Cognitive demands",
            "Visual elements",
            "Numerical components",
            "Logical sequences",
            "Pattern variations",
            "Time pressure scenarios",
            "Creative thinking requirements",
        ],
    },
    "Data-to-text generation": {
        "sub_skills": [
            "Table interpretation",
            "Chart description",
            "Statistical reporting",
            "Trend analysis",
            "Data summarization",
            "Metric explanation",
            "Comparative analysis",
            "Time series narration",
            "Technical writing",
            "Visual data translation",
        ],
        "dataset_characteristics": [
            "Data format variety",
            "Visualization types",
            "Statistical complexity",
            "Domain diversity",
            "Numerical ranges",
            "Trend patterns",
            "Context requirements",
            "Technical depth",
            "Audience levels",
            "Report styles",
        ],
    },
    "Text classification and extraction": {
        "sub_skills": [
            "Entity recognition",
            "Sentiment analysis",
            "Topic classification",
            "Intent detection",
            "Key phrase extraction",
            "Named entity extraction",
            "Document categorization",
            "Semantic role labeling",
            "Relation extraction",
            "Feature classification",
        ],
        "dataset_characteristics": [
            "Label diversity",
            "Text complexity",
            "Entity types",
            "Domain coverage",
            "Language variety",
            "Annotation quality",
            "Context dependency",
            "Edge cases",
            "Ambiguity levels",
            "Classification granularity",
        ],
    },
    "Few-shot reasoning": {
        "sub_skills": [
            "Pattern adaptation",
            "Example generalization",
            "Task transfer",
            "Rule inference",
            "Template matching",
            "Context learning",
            "Analogical reasoning",
            "Quick adaptation",
            "Meta-learning",
            "Prototype recognition",
        ],
        "dataset_characteristics": [
            "Example diversity",
            "Task complexity",
            "Pattern variety",
            "Context richness",
            "Adaptation requirements",
            "Generalization scope",
            "Learning curves",
            "Transfer scenarios",
            "Rule complexity",
            "Solution flexibility",
        ],
    },
    "Conversational tasks": {
        "sub_skills": [
            "Dialogue management",
            "Context tracking",
            "Response generation",
            "Intent understanding",
            "Emotion recognition",
            "Turn taking",
            "Personality consistency",
            "Social appropriateness",
            "Clarification handling",
            "Conversation flow",
        ],
        "dataset_characteristics": [
            "Conversation flow variety",
            "Context complexity",
            "Speaker diversity",
            "Topic coverage",
            "Turn-taking patterns",
            "Dialogue acts",
            "Emotional range",
            "Cultural contexts",
            "Social scenarios",
            "Intent variations",
        ],
    },
    "Emotional intelligence evaluation": {
        "sub_skills": [
            "Emotion recognition",
            "Empathy expression",
            "Social awareness",
            "Conflict resolution",
            "Mood interpretation",
            "Cultural sensitivity",
            "Emotional regulation",
            "Interpersonal skills",
            "Situational awareness",
            "Relationship management",
        ],
        "dataset_characteristics": [
            "Emotional complexity",
            "Cultural diversity",
            "Situation variety",
            "Response types",
            "Social contexts",
            "Relationship dynamics",
            "Communication styles",
            "Conflict scenarios",
            "Empathy levels",
            "Behavioral patterns",
        ],
    },
    "Content Safety evaluation": {
        "sub_skills": [
            "Toxicity detection",
            "Hate speech identification",
            "Bias recognition",
            "Harmful content filtering",
            "Profanity detection",
            "Misinformation identification",
            "Harassment detection",
            "Content moderation",
            "Safety compliance",
            "Ethical content analysis",
            "Personal information protection",
            "Privacy compliance",
            "Data protection",
            "Legal compliance",
        ],
        "dataset_characteristics": [
            "Content type diversity",
            "Severity levels",
            "Cultural contexts",
            "Language variations",
            "Intent patterns",
            "Edge cases",
            "Platform specificity",
            "Time sensitivity",
            "Regulatory compliance",
            "Ethical considerations",
        ],
    },
}
