# Generated by Django 5.1.8 on 2026-07-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_create_missing_org_memberships'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSLoginProxy',
            fields=[
            ],
            options={
                'verbose_name': 'SOS Login',
                'verbose_name_plural': 'SOS Login (impersonate user)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
    ]
